### ISSUE TITLE
Minecraft 1.9 / 1.10

### ISSUE THREAD

**Issue by TheDiamondYT1** [DragonetMC/DragonProxy#1]
I think we should update to 1.9 and 1.10, but in seperate branches.

For example the master branch is 1.8, then we have 1.9 and 1.10 branches.

**Comment by TheDiamondYT1** [comment]
@DragonetMC/developers Thoughts?

**Comment by Pet0203** [comment]
I'll try to make an update for 1.10, if I succeed then maybe I'll make one for 1.9 too. Then maybe we should make some kind of protocol that works with 1.8/1.9/1.10

**Comment by TheDiamondYT1** [comment]
I will make a 1.10 branch tommorow

**Comment by Pet0203** [comment]
Okay, I've got 1.10.2 kind of working. You can connect to a 1.10 server, the inventory loads and the chat messages too, chunks aren't loading tho and it causes some kind of crash that freezes the whole proxy and pushes the cpu  usage to 100%. Will work more on it tomorrow. And please check my fork and see if everything is right.

**Comment by TheDiamondYT1** [comment]
@Pet0203 Please make a PR to the 1.10-testing branch

**Comment by TheDiamondYT1** [comment]
@DragonetMC/developers Nobody merge the 1.10-testing branch.

**Comment by Pet0203** [comment]
Is there anyone who will or is working with 1.10? Because chunkloading doesn't work and i can't fix it.

**Comment by wgaylord** [comment]
You could look at https://github.com/ProtocolSupport/ProtocolSupport for help with support multiple versions of PC Servers. Granted its a bukkit plugin but it could give you some in sight.

**Comment by TheDiamondYT1** [comment]
Im changing the whole project structure currently

**Comment by Pet0203** [comment]
Well, i fixed the freezing thingy but now it just generates a bunch of random spruce wood blocks over the chunks xD, will check more on the block translator soon.

**Comment by pspupsp** [comment]
Oh,I wait 1.10.2 for a long time, if you want to update to 1.10.2,it's great!That's because my sever is running in 1.10.2.XD

**Comment by Pet0203** [comment]
The 1.10 branch has been removed, dunno why. And I can't build the new maven modules thingy so I can't update it again.

**Comment by TheDiamondYT1** [comment]
@Pet0203  Use maven from command line and package the proxy module

**Comment by Pet0203** [comment]
@TheDiamondYT1 Already tried, doesn't work for me
EDIT: [These are the errors](http://pastebin.com/2kruNi0u)

**Comment by TheDiamondYT1** [comment]
Show me your command line in pastebin

**Comment by Pet0203** [comment]
Thoughts? @TheDiamondYT1

**Comment by TheDiamondYT1** [comment]
Not the errors, what you type on the command line.

What command do you build with? What directory?

**Comment by ZedCee** [comment]
Beware of the client errors with PE 0.15.x handling maps from anything after PC 1.8.9.
Pocketmine and it's derivatives have seen this:
https://github.com/iTXTech/Genisys/issues/1206
https://github.com/PocketMine/PocketMine-MP/issues/4216

In my testing with custom anvil maps I discovered what worked and what didn't.  The only blocks I can confirm give issues would be GrassPath, beetroots, probably the bone block (if that's actually in there), and there's a bit of a mystery as to what else.

Using [pmImporter](https://github.com/Muirfield/pmimporter) Could confirm some of what was removed.  Tested with MCEdit, PC 1.9 and later, villages (even from surface schematics) crash the client.  
If unchanged and left to corrupt chunks and delete them (repeated logins gain you a few ticks to move), whole villages and portions at the base of mountains get deleted (the map chunks).

 Villagers and other mobs do not seem to be the problem.

---

My build also failed with the same error above attempting to build from `master`.  Followed the wiki to a tee.

**Comment by Pet0203** [comment]
@TheDiamondYT1 I did the same as @ZedCee (followed the wiki)

**Comment by TheDiamondYT1** [comment]
It works for me

**Comment by ahmedyounes** [comment]
I dont know if im hoping too much after 3 years im asking if there is any support for the current minecraft PE version .. appreciate your efforts guys

**Comment by SupremeMortal** [comment]
@ahmedyounes This post is 3 years old because it's related to Java Edition 1.9 and 1.10. Bedrock Edition 1.10 only released this year.
