### ISSUE TITLE
Generate protocol using external data

### ISSUE THREAD

**Issue by jlirochon** [DragonetMC/DragonProxy#1]
Here is a project which maintains Minecraft protocol data as json files:
https://github.com/PrismarineJS/minecraft-data

Browsable version here:
http://prismarinejs.github.io/minecraft-data/

A prototol generator exists for Java:
https://github.com/Johni0702/ProtocolGen

We should use this to keep Minecraft protocol up to date.

We should start and maintain the same stuff for Minecraft PE protocol, making it easy for us (and other projects) to keep protocol up to date.

**Comment by DefinitlyEvil** [comment]
Let's just use MCProtocolLib for now. ;)
