### ISSUE TITLE
Try sending the AddEntityPacket after the player has joined, not before.

### ISSUE THREAD

**Issue by MrPowerGamerBR** [DragonetMC/DragonProxy#10]
There is two conditions that what happens with the AddEntityPacket:
1. The packet is sent before the player joins (the world is loaded) the server, this causes a crash.
2. The packet is sent after the player joins the game, this doesn't cause a crash and the entity is displayed for the MCPE client.

I found this while testing, I spawned a mob and the mob was displayed for the MCPE client, after relogging the MCPE client crashed until I killed every mob in the MCPE initial view distance.

I think a workaround would be adding the AddEntityPacket to a ArrayList until all the initial packets are sent, after everything is sent, send the AddEntityPackets.

**Comment by DefinitlyEvil** [comment]
Nice, I think we need a cache. But it didn't crash before when I send such packets, maybe didn't translated well?
