### ISSUE TITLE
sign and entity meta

### ISSUE THREAD

**Issue by KangYui** [DragonetMC/DragonProxy#10]
i cant see any sign or hologram..

**Comment by DefinitlyEvil** [comment]
We must get name-tag of mobs working, so here's the to-do list for this issue:
- [ ] Entity meta translator
- [ ] Sign detail update

**Comment by KangYui** [comment]
Thanks! You are good developer!

**Comment by DefinitlyEvil** [comment]
@KangYui But it seems that after update client can't even join the server lol. xD
