### ISSUE TITLE
Client outdated

### ISSUE THREAD

**Issue by commanderbass** [DragonetMC/DragonProxy#100]
I got the Minecraft version Windows 10 Edition Beta 0.13.2 and the server is 0.13.1 .... so on connect it say client outdated..... is there any protocol hack or fix?

**Comment by Pet0203** [comment]
We aren't making any development on 0.13.2 because we are jumping to the 0.14.0 directly. Do you want me to make a build for you which works with 0.13.2 (Unstable doe)?

**Comment by commanderbass** [comment]
can you add a setting (only for development) that you can set the protocol number for the PE client in the settings?

0.13.2 has only bug fixes and the western skin pack so like normal it should compitable to 0.13.1

**Comment by Pet0203** [comment]
Aha, okay. To add a setting with protocol number is ineffective because you would eventually need to change the packets. I'll build a dragonproxy with support for 0.13.2 as soon as I'm home.

**Comment by DefinitlyEvil** [comment]
Duplicated issue.
