### ISSUE TITLE
Plugin Channel and Settings packet

### ISSUE THREAD

**Issue by tr7zw** [DragonetMC/DragonProxy#100]
Clients connecting with DragonProxy should send Plugin Channel messages like vanilla Clients. Most important:
MC|Brand stating that it's a Dragon Proxy Client
http://wiki.vg/Plugin_channels

Also, the Client Settings packet would be nice: http://wiki.vg/Protocol#Client_Settings
Without that the language on the Bungeecords/Spigot is null, which can cause problems.

**Comment by DefinitlyEvil** [comment]
but it's not necessary to send those `MC|Brand` stuffs right? :P

**Comment by mikroskeem** [comment]
Well it would be nice to have, as it was stated it could cause problems when not present.

**Comment by HoverEpic** [comment]
I'll do that in next iteration, client settings too.

**Comment by tr7zw** [comment]
Yea not sending th MC|Brand packet caused problems on our side and marks the client as suspicious. Same thing with the settings packet. Possible that some networks temp ban users for joining with such a "incomplete" client.
