### ISSUE TITLE
Hung on Generating world > Locating server

### ISSUE THREAD

**Issue by karlvr** [DragonetMC/DragonProxy#103]
Using MC PE v0.14.0 on iOS. Using HEAD of master of DragonProxy (51c81db2638c8567816172ce8e3891342d5a9188). Using vanilla `minecraft_server.1.8.9.jar`.

I see this in the console log of DragonProxy:
```
11:57:54 [INFO] Saving console output enabled
11:57:54 [INFO] Starting up DragonProxy, version: 0.0.3-preR4 ... 
11:57:54 [INFO] Supported version of Minecraft PC/Mac: 1.8.9
11:57:54 [INFO] Supported version of Minecraft: Pocket/Windows 10 Edition: 0.14.0.x
11:57:54 [INFO] This is a development build. It may contain bugs. Do not use on production
11:57:54 [INFO] Creating thread pool(Size:16)... 
11:57:54 [INFO] Binding on 0.0.0.0:19132 ... 
11:57:54 [INFO] Server started! 
11:58:00 [INFO] Player me[/192.168.1.131:19132] connected! 
11:58:02 [INFO] Bridge established for player me[/192.168.1.131:19132]! 
```

And on the console log of Minecraft server:
```
[11:58:06] [Server thread/INFO]: com.mojang.authlib.GameProfile@11fbf87[id=<null>,name=me,properties={},legacy=false] (/127.0.0.1:45261) lost connection: Disconnected
```

I can debug further, and would appreciate some pointers of where I should look.

**Comment by karlvr** [comment]
Appears similar to #16, which was closed in December.

**Comment by DefinitlyEvil** [comment]
Do not use the latest master branch which is not completely updated now.

**Comment by TheDiamondYT1** [comment]
If you want to use this software, wait for us to update or go back to 0.13 and download the [latest release](https://github.com/dragonetmc/dragonproxy/releases)

**Comment by karlvr** [comment]
@TheDiamondYT1 Thanks, I am currently waiting. Go back isn't a supported concept on iOS :-)
