### ISSUE TITLE
config.yml parsing is broken in master?

### ISSUE THREAD

**Issue by karlvr** [DragonetMC/DragonProxy#104]
I am not sure where to find an example `config.yml`. The one I found is in `src/main/resources/resources/config.yml`. However it doesn't appear to be compatible with the current `ServerConfig` class.

Particularly:

- no `@Setter` annotations
- invalid bind structure
- `RemoteServer` subclass specification doesn't appear to work

I feel like HEAD of master may be in an in-between state? I've made some patches to at least get it working for me (issue of actually getting it working not withstanding! #103). I'm not sure if these changes are useful at all, or if I'm off on the wrong track. https://github.com/karlvr/DragonProxy/tree/fix-config

**Comment by DefinitlyEvil** [comment]
Thanks for noticing. xD 
Just one thing, Config do not need Setter anootations.

**Comment by karlvr** [comment]
Closing as anything useful has been merged in #105.
