### ISSUE TITLE
Can i use it without your cls

### ISSUE THREAD

**Issue by darkspive** [DragonetMC/DragonProxy#106]
2:17:37 [INFO] Server started!
22:17:50 [INFO] Player Darkspive[/178.236.214.217:19132] connected!
22:17:51 [WARNING] Failed to find a usable hardware address from the network interfaces; using random bytes: d0:c3:ea:b8:58:d0:af:e2
22:17:52 [INFO] Bridge established for player Darkspive[/178.236.214.217:19132]!

When i use online mode

**Comment by TheDiamondYT1** [comment]
Online mode is currently buggy. And may I ask why you do not want to use CLS?

**Comment by DefinitlyEvil** [comment]
This is not a forums, we have a forums here at http://forums.dragonet.org . If you post here again you will be banned from our repo.

**Comment by TheDiamondYT1** [comment]
Lol he only asked a question

**Comment by DefinitlyEvil** [comment]
@TheDiamondYT1 Questuons are not issues.

**Comment by TheDiamondYT1** [comment]
By that logic saying 

"Why is it showing this error? Can somebody help" is bad.
