### ISSUE TITLE
Cant login in cls

### ISSUE THREAD

**Issue by darkspive** [DragonetMC/DragonProxy#107]
Can u add russian, korean, ... support?
![screenshot_2016-02-21-13-12-26](https://cloud.githubusercontent.com/assets/14966273/13201659/091c84a8-d89d-11e5-9f8a-788dd8d2ca9a.png)
![screenshot_2016-02-21-13-12-42](https://cloud.githubusercontent.com/assets/14966273/13201660/11c004a4-d89d-11e5-8f60-8a8bf29d4c4f.png)
![screenshot_2016-02-21-13-12-32](https://cloud.githubusercontent.com/assets/14966273/13201661/17ee980e-d89d-11e5-9813-b9910ab9f458.png)

**Comment by darkspive** [comment]
And bug
![screenshot_2016-02-21-13-15-50](https://cloud.githubusercontent.com/assets/14966273/13201663/4a15f3a4-d89d-11e5-9532-9dbd01cace43.png)

**Comment by darkspive** [comment]
Sorry for my english

**Comment by TheDiamondYT1** [comment]
Stop posting issues asking questions.

**Comment by darkspive** [comment]
It is not question. It is bug

**Comment by TheDiamondYT1** [comment]
So you're saying "Can you add Russian translation?" Isint a question?!

**Comment by darkspive** [comment]
Main bug : cant login in cls....

**Comment by DefinitlyEvil** [comment]
@darkspive You are faild to login to Minecraft account but NOT CLS, so check your credentials again.
