### ISSUE TITLE
Donate site problem

### ISSUE THREAD

**Issue by ghost** [DragonetMC/DragonProxy#108]
Can't see DragonProxy donate site!

**Comment by DefinitlyEvil** [comment]
donations are currently disabled :/ but we really need donations, like a demo server.

**Comment by DefinitlyEvil** [comment]
All kinds of donations are appreciated. ;)

**Comment by yoft** [comment]
I've sent you a request on Discord, I can talk there about setting up a
test server?

**Comment by ghost** [comment]
@DefinitlyEvil What is the demo server?
@yoft Me?

**Comment by yoft** [comment]
@DefinitlyEvil I'm sorting out a free demo server :D
@cloud9350 Sorry, was talking to Evil

**Comment by DefinitlyEvil** [comment]
@cloud9350 we need a server to be a public DragonProxy server as a demonstration.

**Comment by ghost** [comment]
@DefinitlyEvil If I find a server that can run DragonProxy, I will contact you again.

**Comment by DefinitlyEvil** [comment]
thanks

**Comment by yoft** [comment]
I have a Bungeecord server running on **tascraft.net**. There is also the latest commit of DragonProxy for this server running at the same address.
MC:BE clients do not require a MC:JE login, however MC:JE clients do.
If you have any queries contact me on Discord **Yoft#9958**

**Comment by Creeperface01** [comment]
I think I could host dragon proxy

**Comment by DefinitlyEvil** [comment]
@yoft I just added you
