### ISSUE TITLE
Cannot connect to server

### ISSUE THREAD

**Issue by Delimer** [DragonetMC/DragonProxy#109]
Hi,
I Use client MCPE 0.14, and server Spigot 1.8.8. I download dragonproxy-0.0.3-preR4.jar and start it (with right config). Dragonet proxy start and I see in client server, but when I try connect to server I see "connecting..." and connect not establishment. I try other servers but not one connected.

config.yml
`udp_bind_ip: '0.0.0.0'
udp_bind_port: 19132
motd: 'Test Drogonet'
default_server: 'test_pc_server'

remote_servers:
  test_pc_server:
    !!org.dragonet.proxy.DesktopServer
    remote_addr: '167.114.117.232'
    remote_port: 25565
  my_pc_server:
    !!org.dragonet.proxy.DesktopServer
    remote_addr: '127.0.0.1'
    remote_port: 25565
  my_pe_server:
    !!org.dragonet.proxy.PocketServer
    remote_addr: 'your.mcpe.server.com'
    remote_port: 19132

mode: offline
command_prefix: '/'
max_players: 5
log_console: true
thread_pool_size: 16`

**Comment by DefinitlyEvil** [comment]
The current code-base broken, please download from a release instead pulling directly from master. 
Thanks! ;)

**Comment by Delimer** [comment]
> please download from a release
I download last release from https://github.com/DragonetMC/DragonProxy/releases
and proxy not work. When I try connect to server I see "connecting..." and connect not establishment.

**Comment by DefinitlyEvil** [comment]
Use MCPE 0.13.1 for those releases, we didn't release for 0.14.x yet.
