### ISSUE TITLE
Drone.io releases problem

### ISSUE THREAD

**Issue by TheDiamondYT1** [DragonetMC/DragonProxy#11]
@DefinitlyEvil We should host the release builds on the http://dragonet.org site because http://drone.io overwrites the artifacts to the latest build. It even updates the artifact with code from OTHER BRANCHES, so it just merged the 1.10 code into the 1.8 master branch artifact. _Great._

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil Please create a releases directory on the site so its like http://dragonet.org/releases/dragonproxy-x.x.x.jar

**Comment by TheDiamondYT1** [comment]
You  need to configure it properly

**Comment by TheDiamondYT1** [comment]
This could maybe be fixed by adding the line <code>git checkout origin/master</code> before the mvn build commands.

**Comment by TheDiamondYT1** [comment]
Okay i have fixed the releases problem by uploading straight to github

**Comment by DefinitlyEvil** [comment]
Fixed to only fetch master branch.

**Comment by TheDiamondYT1** [comment]
Thanks and also lets leave it on 0.0.5 for now and keep adding to the release
