### ISSUE TITLE
Packet decode fail

### ISSUE THREAD

**Issue by debil9877654321** [DragonetMC/DragonProxy#110]
All times it fail to decode packets after logging in.
decode fail
can not decode for pid 0x2c
decode fail
can not decode for pid 0x18
decode fail
can not decode for pid 0x2c
decode fail
can not decode for pid 0x18
decode fail
can not decode for pid 0x2c
decode fail
can not decode for pid 0x18

**Comment by debil9877654321** [comment]
My PE Server is set up. Must I change any settings or something?

**Comment by HoverEpic** [comment]
These are not handled packets, that's not an error, they are just not handled for now.

0x2c = Animate packet
0x18 = Level Sound Event packet

**Comment by debil9877654321** [comment]
Ok, thx
