### ISSUE TITLE
Login system extensions

### ISSUE THREAD

**Issue by GeARCraft1** [DragonetMC/DragonProxy#110]
Hi, Good Night.

I was searching on how to implement MCPE on my Brazilian server (http://craftygaming.me) when I saw this awesome proxy!!! Well, I just thought that a custom login system, like MongoDB as an auth option. This would be awesome!!! If I find the login class and if I can adapt it, I Will send a pull request. 

Thank you,
Gabriel

**Comment by DefinitlyEvil** [comment]
Yeah, this is a good idea. It will be considered to be implememented in the future.

**Comment by GeARCraft1** [comment]
Sorry to ask, but, what is the class that handles cls login??

**Comment by DefinitlyEvil** [comment]
Mainly inside MCPE Downstream class.

**Comment by GeARCraft1** [comment]
Thanks, I found it! But to make a MongoDB extension system I need to port it to NodeJS, so, could you send me a copy of the API (http://api.dragonet.org/) PHP Scripts?? My E-Mail address is enricorocha1@hotmail.com

Thank you very much,

Gabriel

**Comment by DefinitlyEvil** [comment]
I meant to make an API for login such as `mode=custom` and it will try to load a JAR file called `login_extension.jar` in the same directory.

**Comment by GeARCraft1** [comment]
Sorry, I think I was doing it in a different way :-/
I was using like a custom auth server instead of a extension JAR, ( like this:
    mode=custom
    url=10.0.0.x
), That's why I need a copy of the CLS API PHP Scripts. 

Thank you for the time,
  Gabriel

**Comment by DefinitlyEvil** [comment]
Hmm that will be easier but my scripts used a lot of SQL queries and very messy (HTML+PHP mixed). 
Well maybe I will post the authentication procedure to the wiki. Btw they are all done by JSON.

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil email me the scripts so i can edit and document them

**Comment by DefinitlyEvil** [comment]
@TheDiamondYT1 I'm sure you don't want to look at that shit, I just posted it on project wiki.

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil i can assure you i do. I can make the code nicer and add some more api's

**Comment by DefinitlyEvil** [comment]
@TheDiamondYT1 
Okay, will send it tomorrow. 
It's kinda late here. xD

**Comment by TheDiamondYT1** [comment]
take ur time xD

goldowl37@gmail.com

**Comment by DefinitlyEvil** [comment]
@TheDiamondYT1 http://files.dragonet.org/CLSHandler.zip

**Comment by TheDiamondYT1** [comment]
can i have the website code im gonna change it a bit i will explain later

**Comment by DefinitlyEvil** [comment]
@TheDiamondYT1 Change about what? 
I'm not a t home so will send later. xD

**Comment by TheDiamondYT1** [comment]
add global logins, make css less large, custom forums and support and
donate pages, about us page, cls page changes. You know, just the
small stuff xD

**Comment by TheDiamondYT1** [comment]
*eventually add premium accounts and im making an analdroid app.

**Comment by DefinitlyEvil** [comment]
@TheDiamondYT1 Hmm, why premium CLS accounts? xD

**Comment by TheDiamondYT1** [comment]
not cls but global accounts

**Comment by TheDiamondYT1** [comment]
in sch lol

**Comment by DefinitlyEvil** [comment]
What global acc?

**Comment by TheDiamondYT1** [comment]
...

http://lmgtfy.com/?q=global+definition

**Comment by DefinitlyEvil** [comment]
@TheDiamondYT1 Dude I know what does global mean, I just don't know why we need a global account, and global in which area?

**Comment by TheDiamondYT1** [comment]
for custom forums, support area, cls, editing the wiki.

i wont do this all straightaway i need to get my tablet internet

**Comment by TheDiamondYT1** [comment]
and team chat

**Comment by DefinitlyEvil** [comment]
@TheDiamondYT1 So you mean we should switch to github authentication?

**Comment by TheDiamondYT1** [comment]
wtf no

you can login on one page for access to  all pages that require login.
e.g. logged in means cls access and forums logged in

**Comment by DefinitlyEvil** [comment]
well that should be difficult they already have different account system and have many users registered.

**Comment by TheDiamondYT1** [comment]
Can u jus send me website

**Comment by DefinitlyEvil** [comment]
Sure, will do tomorrow.

**Comment by TheDiamondYT1** [comment]
*next day*

**Comment by TheDiamondYT1** [comment]
*Still waits* @definitlyevil

**Comment by DefinitlyEvil** [comment]
@TheDiamondYT1 Sry I was away, could u plz post ur mail address again? sry.

**Comment by TheDiamondYT1** [comment]
goldowl37@gmail.com

**Comment by TheDiamondYT1** [comment]
After, im gonna cleanup the github. Also mail me mcforums login,
thread needs updat

**Comment by TheDiamondYT1** [comment]
@definitlyevil

**Comment by TheDiamondYT1** [comment]
Sry im rushing

**Comment by DefinitlyEvil** [comment]
@TheDiamondYT1 Poop I forgot the password of MCForums.

**Comment by TheDiamondYT1** [comment]
Well still I need the site

**Comment by TheDiamondYT1** [comment]
*3 days later*

**Comment by TheDiamondYT1** [comment]
Sorry for being a pain in the ass, but i need vps login to edit phpbb
code to make it fit with the website theme

**Comment by DefinitlyEvil** [comment]
@TheDiamondYT1 Sry to be slow, this year is quite important to me because I get several exams to prepare which are really important.

**Comment by TheDiamondYT1** [comment]
Work on this can be found in the [dev](https://GitHub.com/dragonetmc/dragonproxy/tree/dev) branch.
