### ISSUE TITLE
Does not work offline mode

### ISSUE THREAD

**Issue by ghost** [DragonetMC/DragonProxy#111]
I bought only PE and I do not have an account because I do not buy PC version.
If set mode: offline in config.yml, you will not be able to connect to the server.

OS : Ubuntu 17.04
Java : Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
DragonProxy Version : commit https://github.com/DragonetMC/DragonProxy/commit/f0cdf760b28d1c5e488b73d72ba0483a238675aa (self compiled)

**Comment by yoft** [comment]
You either need to find an offline server, or create your own.

**Comment by yoft** [comment]
Or try **tascraft.net**

**Comment by ghost** [comment]
@yoft It's work on MC:BE(Android) Client!

**Comment by yoft** [comment]
Awesome to hear! I've got a plugin on my bungeecord server to allow MC:BE
to connect through the dragonproxy on the same server without Mojang
authentication.

**Comment by HoverEpic** [comment]
I plan  making a bungeecord plugin to allow connecting from a single address, for example a DragonProxy server. But first we need to be sure the account is authentic. We need also a skin translator to be able to see pc players skins.
I don't think pc players will be able to see pe skins.

**Comment by DefinitlyEvil** [comment]
@HoverEpic nope PE players will not see PE skins due to they fetch from Mojang's server.

**Comment by HoverEpic** [comment]
Nope nope pe skin is in login payload and can be sent to other pe people. For pe players be able to see pc skins, DP has to get and decode skin section from the profile then download the skin png, then just send it to pe players.

**Comment by DefinitlyEvil** [comment]
yea i had a typo there, i mean we have to do it on DP and encode it into PE format.

**Comment by HoverEpic** [comment]
We can probably make a minecraft forge mod to be able to see PE skins on PC players =)
But it's not for now =)
