### ISSUE TITLE
upload a default config.yml

### ISSUE THREAD

**Issue by ehasting** [DragonetMC/DragonProxy#114]
Hello,

I am trying to figure out a working config.yml.  
i am struggeling with the remote_servers part.  could you upload a default config, or hint about how it should be structured?

**Comment by MeltedLux** [comment]
https://github.com/DragonetMC/DragonProxy/blob/master/src/main/resources/resources/config.yml

**Comment by DefinitlyEvil** [comment]
We didn't fix the default generation stuff, will do that later. 
Closed due to duplicated.
