### ISSUE TITLE
Unable to compile .jar

### ISSUE THREAD

**Issue by DevCraftProductions** [DragonetMC/DragonProxy#117]
When I try to compile the source into a .jar, it does not let me because there are 100 errors and 1 warning. Any help?

**Comment by sgdc3** [comment]
Probably you are missing some dependencies. You should import the project with maven, it should set up all the required dependencies automatically. ;)

**Comment by TheDiamondYT1** [comment]
Tell us how you compiled it

**Comment by DevCraftProductions** [comment]
I just did what it said in README.md. I opened it up in IntelliJ IDEA, tried to compile it, and it would not let me
