### ISSUE TITLE
Host to IP on MCPE connection?

### ISSUE THREAD

**Issue by Encritary** [DragonetMC/DragonProxy#12]
Works only number IPs, domains not working

**Comment by DefinitlyEvil** [comment]
Your DNS problem.

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil Can you make a custom logger with the function warning, info, debug etc?

**Comment by TheDiamondYT1** [comment]
So we dont have to do 

``` java
if(proxy.isDebug()) System.out.println(etc)
```

**Comment by ethsmith** [comment]
Why don't you just use regular logger?

**Comment by TheDiamondYT1** [comment]
@TekkitCommando No debug function and theres not a way to make debug messages gray

**Comment by ethsmith** [comment]
@TheDiamondYT1 Ah ok. So you are gonna make your own Logger class?

**Comment by ethsmith** [comment]
@TheDiamondYT1 It shouldn't be that hard :)

**Comment by TheDiamondYT1** [comment]
@TekkitCommando Ik its really easy but i wanna know if its ok with def

**Comment by ethsmith** [comment]
@TheDiamondYT1 Alright.

**Comment by DefinitlyEvil** [comment]
@TheDiamondYT1 You cal call getLogger() on DragonProxy instance, I am just too layzee. xD

**Comment by DefinitlyEvil** [comment]
@TheDiamondYT1 You cal call getLogger() on DragonProxy instance, I am just too layzee. xD

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil Idk how to do it with the date handler and console file etc
