### ISSUE TITLE
what rail means?

### ISSUE THREAD

**Issue by KangYui** [DragonetMC/DragonProxy#12]
i see rails many case, but i cant know why rail.

**Comment by DefinitlyEvil** [comment]
Where?

**Comment by KangYui** [comment]
https://youtu.be/3DfNjSxGSDM
2015. 12. 19. 오전 1:56에 "The Evil Man" <notifications@github.com>님이 작성:

**Comment by DefinitlyEvil** [comment]
Will be checked.

**Comment by DefinitlyEvil** [comment]
@KangYui So what block that should be on PC instead of rails on PE?

**Comment by KangYui** [comment]
Slab.

**Comment by DefinitlyEvil** [comment]
@KangYui Is that a mis-translation? ;P
