### ISSUE TITLE
[Solved] Can't Connect on Win10 edition

### ISSUE THREAD

**Issue by Waooto** [DragonetMC/DragonProxy#120]
The server is on my localhost machine (On Windows10)
When i Start Minecraft: Windows 10 edition, the DragonProxy does not show up in the Friends tab, and the DragonProxy cmd does not say "Ping"

When I add the server (0.0.0.0:19132) to the server list and try to connect, it says Unable to connect to world.

I am using the latest DragonProxy

**Comment by HoverEpic** [comment]
try http://pmmp.readthedocs.io/en/rtfd/faq/connecting/win10localhostcantconnect.html

**Comment by Waooto** [comment]
Thanks.

**Comment by DefinitlyEvil** [comment]
me tried to fix this too nice!
