### ISSUE TITLE
1.9?

### ISSUE THREAD

**Issue by Pet0203** [DragonetMC/DragonProxy#120]
Guys? Is it time to update to MCProtocolLib 1.9 or should we wait with it? I have already tried doe but I'm too noob to figure out wth I should do to make the chunks load, because MultiChunkLoadPacket was removed. It does connect to the server doe haha xD

**Comment by zaptrem** [comment]
The current build is broken anyway. Even when on 1.8.3 (latest Spigot) the player doesn't receive chunk updates beyond the ones sent when they initially join the game.

**Comment by DefinitlyEvil** [comment]
@Pet0203 Let's wait for MCProtocolLib to be stable.

**Comment by zaptrem** [comment]
It will also take a bit of time to figure out how to deal with the new
combat mechanics and blocks/potion effects/monsters.

**Comment by TekkitCommando** [comment]
Yeah 1.9 is gonna be tricky.

**Comment by Pet0203** [comment]
When will the development start again?

**Comment by TheDiamondYT1** [comment]
Soon

**Comment by DefinitlyEvil** [comment]
I am getting a new powerful PC with `i7-6700k, 32GB RAM, 500GB SSD, double NVidea Titan X`, once I get that I will start the development again. ;)

**Comment by Pet0203** [comment]
Ma brain just got blown *Too much coolness*

**Comment by zaptrem** [comment]
If I were you I would hold out for the new cards this spring from
AMD/Nvidia. Even if you don't, it seems like it is going to be one of a few
that is faster than my SLI 970 rig!

**Comment by Pet0203** [comment]
Yes, I'm waiting for the new generation too.

**Comment by TekkitCommando** [comment]
@DefinitlyEvil Holy crap, you plan to run 50 instances of GTA V with thing

**Comment by DefinitlyEvil** [comment]
I plan to get Unreal Engine 4 working with full features. xD And I will consider playing GTA V if that's really interesting.

**Comment by TekkitCommando** [comment]
Lol nice

**Comment by TekkitCommando** [comment]
@DefinitlyEvil I can't add you to the staff page on Byte Powered if I don't know your real name xD so please skype me that. @TheDiamondYT1 you too.

**Comment by Pet0203** [comment]
So, should we create a new 1.9 branch or use the dev brach

**Comment by DefinitlyEvil** [comment]
Use DEV branch please. @Pet0203

**Comment by Pet0203** [comment]
Okay, I'll make a PR with everything updated but the chunk loading later today.

**Comment by zaptrem** [comment]
How do you plan on dealing with the new items and features (such as elytra
and the new combat mechanics) while at the same time using the old
mechanics with PE players?

**Comment by Pet0203** [comment]
I only meant updating to new protocollib. I don't think there is any way to implent the new features without modifing the client.

**Comment by zaptrem** [comment]
How will that work? Everything relating to combat had probably been
refactored and there is likely quite a few new packet types/calls to handle.

**Comment by TheDiamondYT1** [comment]
Luke Wyatt

**Comment by TheDiamondYT1** [comment]
@TekkiitCommando

**Comment by TekkitCommando** [comment]
@TheDiamondYT1 Thank you sir :) @DefinitlyEvil 's turn

**Comment by TekkitCommando** [comment]
@TheDiamondYT1 I invited you to the Byte Powered org on Github so you can be as cool as @DefinitlyEvil  xD

**Comment by finalchild** [comment]
I have been fixing bugs for ProtocolLib, and I think the latest version of ProtocolLib is stable.

**Comment by DefinitlyEvil** [comment]
@finalchild Gonna try to integrate soon. ;D

**Comment by TheDiamondYT1** [comment]
Lets skip 1.9 and go to 1.10.

**Comment by TheDiamondYT1** [comment]
Or just keep on 1.8 to be comptible with many servers.

**Comment by File14** [comment]
Well, right now the best version is 1.8 because it matche MCPE 0.15 most. The only thing is that it hasn't got all 1.8 blocks etc.
