### ISSUE TITLE
Help setting up DragonProxy

### ISSUE THREAD

**Issue by AryToNeX** [DragonetMC/DragonProxy#121]
Hi!

I want to set up this Proxy with 4 MCPE servers.
I want them to be joinable from both MCPE and MCPC clients and I also want to use /server command like BungeeCord.

How can I do this?

**Comment by TheDiamondYT1** [comment]
we will do this soon.

**Comment by DefinitlyEvil** [comment]
You just have to point DragonProxy to your BungeeCord.

**Comment by TheDiamondYT1** [comment]
@definitlyevil would it be possible to save chat log?

**Comment by DefinitlyEvil** [comment]
@TheDiamondYT1 You can't, but you can do it on BungeeCord.

**Comment by TheDiamondYT1** [comment]
Really? It could be done with a client mod. Gonna contact @SmartDEVTeam to help.

**Comment by robske110** [comment]
Is there anyway to use this to transfer between MCPE servers
The whole MCPE community is searching for that

**Comment by Pet0203** [comment]
That would be the idea, yes.

**Comment by AryToNeX** [comment]
@DefinitlyEvil I want to use DragonProxy LIKE BungeeCord. I don't have BungeeCord or MCPC servers.

**Comment by TheDiamondYT1** [comment]
@AryToNeX That is not the purpose of DragonProxy. The purpose is to allow people on mcpe to join PC servers.

**Comment by MrPowerGamerBR** [comment]
@AryToNeX that's not what is said in the README file.

"A proxy for Minecraft: Pocket Edition/Windows 10 Edition connecting to multiple Minecraft PC/Mac **or Pocket Edition servers**. It works like BungeeCord but much more powerful than that. ;) "

**Comment by TheDiamondYT1** [comment]
Well idk but to do what he wants like bungeecord it would have to be server plugin / software as definitly evil stated above that we can't execute DragonProxy commands from the client when on a server

**Comment by DefinitlyEvil** [comment]
@robske110 You will be able to do that.

**Comment by DefinitlyEvil** [comment]
@TheDiamondYT1 Well I added a command prefix for Dragonet (to prevent from conflict with BungeeCord one) and players CAN transfer between servers even PC<->PE servers.

**Comment by robske110** [comment]
This sounds cool, but you need to programm an php plugin for pocketmine, if you want transfer from MCPE server to MCPE server

**Comment by robske110** [comment]
I could help out with that, but I'm not a professional in handling packets

**Comment by Pet0203** [comment]
@robske110 I don't think that would be needed. If you don't need a plugin to connect to bulk it why would you need one for pocketmine? The only thing DragonProxy needs to do is switching to MCPE protocol instead of MCPC

**Comment by robske110** [comment]
Bungee cord has to be installed on all servers i think.
Look, if you want a TRANSFER between two pocket servers:
You connect to DragonProxy, it will redirect all Packets to Server 1, now if the client presses a sign on Server1 the plugin will send the DragonProxy 'Transfer player 999.999.999.999 to Server2 with the name JAhdz' and the dragon proxy sends this data to the plugin on Server2. And now the magic: the plugin on server two must just start to send chunk packets. Nothing else. The server cannot except to get the protocol version, because the client thinks it is still connected to the old server. It's like an world change. Of course this will result into weired chunks, but they'll update after some time.

**Comment by robske110** [comment]
Or whats our theory

**Comment by Pet0203** [comment]
Why not just make a command that unloads all chunks and connects to the second server?

**Comment by robske110** [comment]
How do you want to tell the secound server that the client won't send NAME, PROTOCOL and other initial needed packets

**Comment by Pet0203** [comment]
Why wouldn't it? Just tell DragonProxy to disconnect and then connect to the other server, the client still thinks it is a world change?

**Comment by robske110** [comment]
But the target server won't understand what's happening. Then for example waits/sends the ChunkRadiusPacket->RakLibCrash/ClientCrash

**Comment by Pet0203** [comment]
You don't need a plugin for transferring. Just a command for dragon proxy that disconnects from server1 and makes a whole new connection to server2 with login packets etc.

**Comment by robske110** [comment]
Have fun with that :P

**Comment by TheDiamondYT1** [comment]
once conmected to pc server, clients cant execute dragonproxy commands.

**Comment by TheDiamondYT1** [comment]
im gonna make new  branches

**Comment by TheDiamondYT1** [comment]
@definitlyevil make master branch called 'pc'

**Comment by TheDiamondYT1** [comment]
i also need DragonProxy-app repo

**Comment by Creeperface01** [comment]
I can make transfer plugin for nukkit and pocketmine. I think transfering is based on some special packet. And when bungeecord receive this packet, so transfer player to the specified server.

**Comment by Pet0203** [comment]
@TheDiamondYT1 you could, if you open up every chat packet going towards the server, or am I totally wrong? DragonProxy would be much better if it didn't needed to have anything to do with the server (plugins etc.)

**Comment by robske110** [comment]
Don't use plugins

**Comment by DefinitlyEvil** [comment]
No plugins needed, we can simulate MCPE login on DragonProxy just like BungeeCord does.

**Comment by TheDiamondYT1** [comment]
We will soon add an article over on the [wiki](https://GitHub.com/DragonetMC/DragonProxy/wiki). For now there should be a simple guide in the [README](README.md)
