### ISSUE TITLE
Connecting To Mojang

### ISSUE THREAD

**Issue by Waooto** [DragonetMC/DragonProxy#122]
I can connect to the server, but when it asks for my email & password, and i type it in (the correct email & password) 

it says "Connecting to Mojang", and then it immediately kicks me with the message "Failed to login"

i have tried restarting my Machine, but it still says this. How can I fix this ?

**Comment by DefinitlyEvil** [comment]
do not repeat it too often, Mojang will ban your IP for an hour if you logged to many times within an hour.
