### ISSUE TITLE
Taking more clientside damage and dieing clientside

### ISSUE THREAD

**Issue by tr7zw** [DragonetMC/DragonProxy#123]
After taking damage the client keeps showing that it's losing health until you die clientside, but not serverside. You can't respawn, until you die serverside.
http://tr7zw.de/u/1513019141.gif

**Comment by HoverEpic** [comment]
I'll take a look next coding day. Thanks for report.

**Comment by DefinitlyEvil** [comment]
It's probably caused by changed max health value.

**Comment by tr7zw** [comment]
Tested with release build on an empty 1.12.2 spigot server without plugins.

**Comment by DefinitlyEvil** [comment]
Hmm :/

**Comment by HoverEpic** [comment]
I'll take a look, this is in entity meta translator.
