### ISSUE TITLE
Bad work with spigot 1.8.x

### ISSUE THREAD

**Issue by Delimer** [DragonetMC/DragonProxy#124]
I start Spigot 1.8.9 server, and DragonProxy 0.0.4, then connect to server, client 0.14
1) Breakin block lag
2) Crafting Table in inventory not work
3) Crafting Table not work
4) Chest not work
5) Furnace not work
6) In creative mode creative inventory empty

Also I try connect to other 1.8.x servers and has thats problems

**Comment by Pet0203** [comment]
Duplicate issue doe, take a look at the other issues before posting a new. 

The problem is not spigot, it's just that DragonProxy isn't completely finished, that's why it is a beta snapshot. Different Windows like the chest and crafting table hasn't been implented yet.

**Comment by TheDiamondYT1** [comment]
Dupl #91 #69
