### ISSUE TITLE
[bug] Punching Client

### ISSUE THREAD

**Issue by Waooto** [DragonetMC/DragonProxy#126]
Right clicking on PE will not do anything, but when a PC player is looking at a PE player right clicking on the floor, it will look like the PE player is punching the floor.

When the PE player is actually punching the floor with the hand (Left click) the PC player won't see the PE player punch the floor.

So the Punching is swapped basically.

**Comment by DefinitlyEvil** [comment]
not implemented yet, do not spam those pointless issues!

**Comment by Waooto** [comment]
Ok, sorry i didn't know they were **not implemented**
