### ISSUE TITLE
Latest circleci version won't run

### ISSUE THREAD

**Issue by kam187** [DragonetMC/DragonProxy#129]
Hi,

I downloaded the latest build from circleci but I get this error:

14:43:10 [INFO] Saving console output enabled
14:43:10 [WARNING] Exception in thread "main" 
14:43:10 [WARNING] java.lang.NullPointerException
14:43:10 [WARNING] 	at java.util.Properties$LineReader.readLine(Properties.java:434)
14:43:10 [WARNING] 	at java.util.Properties.load0(Properties.java:353)
14:43:10 [WARNING] 	at java.util.Properties.load(Properties.java:341)
14:43:10 [WARNING] 	at org.dragonet.proxy.configuration.PropertiesConfig.<init>(PropertiesConfig.java:30)
14:43:10 [WARNING] 	at org.dragonet.proxy.configuration.Lang.<init>(Lang.java:91)
14:43:10 [WARNING] 	at org.dragonet.proxy.DragonProxy.run(DragonProxy.java:119)
14:43:10 [WARNING] 	at org.dragonet.proxy.DragonProxy.main(DragonProxy.java:38)

It looks like the default config file is not correct for this version any more?

On a side note, I tried to compile dragonproxy myself, but when I load it into inteliJ there's nothing to build .  How exactly do I build it?

**Comment by TekkitCommando** [comment]
You can use maven to build the project with all its dependencies.

**Comment by kam187** [comment]
Thanks i managed to do that just fine.  But the bug above still exists.

Does it work for you?  Do i need any other directory structure or just the jar?  The old version would create the config for you if it wasn't present.

**Comment by TekkitCommando** [comment]
@TheDiamondYT1 or @DefinitlyEvil would know, I am here for other reasons and don't personally work on coding DragonProxy.
