### ISSUE TITLE
Switch to maven modules

### ISSUE THREAD

**Issue by TheDiamondYT1** [DragonetMC/DragonProxy#13]
Ive been experimenting with maven modules and we will switch the project to having 2 modules (and a 3rd when we work on the API).

Ive also changed some package names. I will push the changes to the maven-modules branch either today, tommorow, or on the weekend.

@DragonetMC/developers Thoughts?

**Comment by TheDiamondYT1** [comment]
I call it a huge change because alot of the package names are changing to org.dragonet.proxy instead of org.dragonet, and because im switching to modules your ide might have a tantrum

**Comment by TheDiamondYT1** [comment]
Okay, here it is https://github.com/DragonetMC/DragonProxy/tree/maven-modules

@DefinitlyEvil

**Comment by DefinitlyEvil** [comment]
Ye, I think some package renaming would be good since current ones are confusive.

**Comment by TheDiamondYT1** [comment]
Yeah it should all be org.dragonet.prixy
