### ISSUE TITLE
Wiki is not working

### ISSUE THREAD

**Issue by Yuns92** [DragonetMC/DragonProxy#130]
http://wiki.dragonet.org/ cannot be found.

**Comment by robske110** [comment]
*cough* https://github.com/DragonetMC/DragonProxy/wiki

**Comment by TheDiamondYT1** [comment]
This issue is ***not*** fixed, as the wiki navbar link stills needs to an unknown domain. 

@TekkitCommando Can you create `wiki.dragonet.org` then redirect it to the wiki on GitHub?

**Comment by DefinitlyEvil** [comment]
@TheDiamondYT1 That's my job.

**Comment by TheDiamondYT1** [comment]
Is it? He created http://blog.dragonet.org for me. (By the way please don't touch it yet, I'm gonna update it with a new theme and add admin accounts.
