### ISSUE TITLE
build #297 error when starting

### ISSUE THREAD

**Issue by TonyWAV** [DragonetMC/DragonProxy#131]
**when i start the build #297 I got this error:**
2016/04/23 12:13:49 [WARNING] Exception in thread "main" 
2016/04/23 12:13:49 [WARNING] java.lang.NullPointerException
2016/04/23 12:13:49 [WARNING] 	at java.util.Properties$LineReader.readLine(Unknown Source)
2016/04/23 12:13:49 [WARNING] 	at java.util.Properties.load0(Unknown Source)
2016/04/23 12:13:49 [WARNING] 	at java.util.Properties.load(Unknown Source)
2016/04/23 12:13:49 [WARNING] 	at org.dragonet.proxy.configuration.PropertiesConfig.<init>(PropertiesConfig.java:30)
2016/04/23 12:13:49 [WARNING] 	at org.dragonet.proxy.configuration.Lang.<init>(Lang.java:91)
2016/04/23 12:13:49 [WARNING] 	at org.dragonet.proxy.DragonProxy.run(DragonProxy.java:119)
2016/04/23 12:13:49 [WARNING] 	at org.dragonet.proxy.DragonProxy.main(DragonProxy.java:38)

**Comment by EnragedViper** [comment]
Tested and confirmed, identical error:
```java
2016/04/23 21:37:49 [INFO] Saving console output enabled
2016/04/23 21:37:49 [WARNING] Exception in thread "main"
2016/04/23 21:37:49 [WARNING] java.lang.NullPointerException
2016/04/23 21:37:49 [WARNING] 	at java.util.Properties$LineReader.readLine(Unknown Source)
2016/04/23 21:37:49 [WARNING] 	at java.util.Properties.load0(Unknown Source)
2016/04/23 21:37:49 [WARNING] 	at java.util.Properties.load(Unknown Source)
2016/04/23 21:37:49 [WARNING] 	at org.dragonet.proxy.configuration.PropertiesConfig.<init>(PropertiesConfig.java:30)
2016/04/23 21:37:49 [WARNING] 	at org.dragonet.proxy.configuration.Lang.<init>(Lang.java:91)
2016/04/23 21:37:49 [WARNING] 	at org.dragonet.proxy.DragonProxy.run(DragonProxy.java:119)
2016/04/23 21:37:49 [WARNING] 	at org.dragonet.proxy.DragonProxy.main(DragonProxy.java:38)
```
The commit in question :) 7c560e3628d3e93a080c52f4a6ac0b779dd1c637

**Comment by TheDiamondYT1** [comment]
@EnragedViper Let's leave @DefinitlyEvil to fix that. 

Also, why did you use \```java for console text? Anyway, the highlighting looks nice.

**Comment by DefinitlyEvil** [comment]
@TheDiamondYT1 Idk why CircleCI isn't fetching latest commits, could u plz look into that?

**Comment by DefinitlyEvil** [comment]
@TheDiamondYT1 Nvm, forgot to do `push`. xD
