### ISSUE TITLE
Input frame for online mode servers

### ISSUE THREAD

**Issue by HoverEpic** [DragonetMC/DragonProxy#131]
We can make a minecraft bedrock input frame for logging in minecraft pe account instead of typing in console.
To make a more friendly thing, we could also create a fake chunk of a room with some explanations or server selector (different minecraft network i mean).

**Comment by yoft** [comment]
Could you include the server selector as part of the gui, after you log in?

**Comment by lukeeey** [comment]
@yoft This would be possible 

Maybe we can send a Text Packet executing /server (which usually lists all servers in BungeeCord) and then sort through those and create a button for each one in the GUI.

**Comment by yoft** [comment]
Or use a plugin and pass plugin messages?

**Comment by lukeeey** [comment]
That's not really the point of this project. We can't go and ask Hypixel to install our plugin, can we?

**Comment by yoft** [comment]
True :p

**Comment by HoverEpic** [comment]
Yes make a GUI for selecting a server can be done : 
- if the server is online mode, just ask creadentials in a GUI then login
- if the server is offline mode, just send the player to it and the login process is made there
- if the server has our custom plugin, the player is dirrectly logged in

That's just an idea and needs to be think carrefully =)

**Comment by DefinitlyEvil** [comment]
custom GUI is possible for PE, it uses some format of JSON objects.
