### ISSUE TITLE
Move to GitLab

### ISSUE THREAD

**Issue by TheDiamondYT1** [DragonetMC/DragonProxy#134]
**Why?**
* We can host it ourselves, so we have complete control over it.  
* It has a clean, flat interface and many GitHub features.  
* It has built-in ci.  
* It has a wiki area, issues, and pull requests tabs.  
* **Unlimited private repos**.  
* https://about.gitlab.com/features/

Comment your suggestions below.

**Comment by TekkitCommando** [comment]
I had it at one point, it works just like GitHub only self hosted and has a pretty awesome downloads manager.

**Comment by TekkitCommando** [comment]
The only problem is that requires another VPS/Dedi which at this point  Byte Powered isn't bringing in the necessary income for more servers. However maybe this summer that will change with the release of other Byte Powered projects. My suggestion is we get in a conference call on Skype and work out sponsors/partners and maybe a link to donating on the readme. I can't promise anything but there should be an income boost for Byte Powered in June or July if everything goes according to plan. Another thing to talk about it whether we want to get the peeps in Byte Powered with PHP experience to work together on some freelance projects to acquire the funds we need.

**Comment by TekkitCommando** [comment]
@DefinitlyEvil @TheDiamondYT1 What are your thoughts my young business apprentices.

**Comment by TheDiamondYT1** [comment]
@TekkitCommando I've never used the self-hosted version, but I've looked at all the features of the online one.

**Comment by TheDiamondYT1** [comment]
Firstly, let me have the dragonet website code.

**Comment by TekkitCommando** [comment]
@TheDiamondYT1 I do love the self hosted version a lot though. @TheDiamondYT1 Yeah sure let me get you that.

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil Give @TekkitCommando your pass to the cPanel (He will get it in a few hours so if its been that long just leave it)

**Comment by Slind14** [comment]
Besides adding another layer of signup to contribute and create issues I don't seen any advantage. You can auto deploy to github with travis, too. Unless you want to make it private.

**Comment by sgdc3** [comment]
Why not just mirroring? Gitlab is able to mirror any changes from github ;)

**Comment by TekkitCommando** [comment]
^

**Comment by TheDiamondYT1** [comment]
But then what would be the point of GitLab?

**Comment by TekkitCommando** [comment]
^

**Comment by DefinitlyEvil** [comment]
What is self-hosted? We must host code on our own? I think that will be unstable. xD Github has better servers.

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil Of course GitHub has better servers but hosting yourself is good. It probably won't be unstable. I also need the dragonet website source. @TekkitCommando doesn't have the admin pass right now.

**Comment by jython234** [comment]
Why not use online gitlab? Besides, why do you qant to host yourself?

**Comment by TheDiamondYT1** [comment]
It looks more professional in my opinion. We can use custom URLs and edit it how we like.

**Comment by DefinitlyEvil** [comment]
It just looks cool. xD

**Comment by sgdc3** [comment]
gitlab.com is hosted by gitlab itself

**Comment by sgdc3** [comment]
the self-hosting is optional xD

**Comment by sgdc3** [comment]
In my opinion you should mirror to github but keep the main repo on github

**Comment by sgdc3** [comment]
Github is more collaborative-oriented

**Comment by sgdc3** [comment]
collaboration-oriented, sorry

**Comment by TheDiamondYT1** [comment]
Mirroring from gitlab but main repo on github... What's the point??

**Comment by sgdc3** [comment]
@TheDiamondYT1 free CI service ;)

**Comment by TheDiamondYT1** [comment]
@sgdc3 https://travis-ci.org

**Comment by sgdc3** [comment]
Travis:
- slower
- it gets stucked very often
- it doesn't have free space to store artifacts

**Comment by sgdc3** [comment]
Travis:
-slower
-it gets stucked very often
-it doesn't have any feature able to store and host artifacts

**Comment by DefinitlyEvil** [comment]
@sgdc3 But it's free.

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil So is gitlab

**Comment by sgdc3** [comment]
Lol nobody here has a clear idea about gitlab xD 
- It allows you to host unlimited private or public projects on gitlab.io itself (and use the builtin CI service) for free! 
- If you want to host your gitlab server you can download gitlab ce and run it in your server. 
- You can mirror another git repository on another svc service like github.

**Comment by jriwanek** [comment]
For note, Github also supports Travis CI integration ... for free.

**Comment by sgdc3** [comment]
Travis is slow, atm the best solution with github is circleci, but i'm sure that gitlab's one faster and obviously more integrated with the web interface.

P.S: I'm a github fun and i'll keep my project on it, but i think that a mirror repo on gitlab could be useful as backup and build service.
