### ISSUE TITLE
1.2.7 Support

### ISSUE THREAD

**Issue by TheGameratorT** [DragonetMC/DragonProxy#134]
Protocol has changed to 160 in this version so it's not compatible with it.

**Comment by DefinitlyEvil** [comment]
huh it evolves very fast xD

**Comment by HoverEpic** [comment]
No commit in MiNET protocole, so I think just changing version is ok.

**Comment by HoverEpic** [comment]
Fixed in https://github.com/DragonetMC/DragonProxy/commit/76929873883e8568115cf0256ab6abc51283ca17
