### ISSUE TITLE
Blocks ID error?

### ISSUE THREAD

**Issue by the-eric-kwok** [DragonetMC/DragonProxy#135]
![MCPE](https://user-images.githubusercontent.com/16463312/34031621-33daa196-e1ad-11e7-9b1f-8f39b41ce3e0.jpg)
![MC Java Version](https://user-images.githubusercontent.com/16463312/34031624-34305d7a-e1ad-11e7-8287-2fa6042486ac.png)
### Describe
The dirt blocks don't seem to be right. 
### Version Informations:
The server is running CraftBukkit version git-Spigot-549c1fa-2ee49b4 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
And the DragonProxy version is dragonproxy-0.2.2.1.jar
MC Java: 1.12.2
MCPE: 1.2.6
### Logs
Here's the log:
spigot: [latest.log](https://github.com/DragonetMC/DragonProxy/files/1561936/latest.log)

**Comment by HoverEpic** [comment]
Fixed in dev branch. Will be ok on next release.
