### ISSUE TITLE
Bungeecord ip_forward  implementation

### ISSUE THREAD

**Issue by andris155** [DragonetMC/DragonProxy#136]
```
[14:23:06] [User Authenticator #47/INFO]: UUID of player Saii3 is cda5e382-d4e7-3de0-be46-17e0bf513954
[14:23:07] [Server thread/INFO]: Saii3[/127.0.0.1:54383] logged in with entity id 159 at ([world]-208.31039428710938, 18.0, -178.4748992919922)
```

**Comment by HoverEpic** [comment]
We do not implements ip forwarding for now.

**Comment by lukeeey** [comment]
@HoverEpic RFC means Request For Comments, but you just said you wont implement it. Well done 👏 

We've discussed IP forwarding before, and havent found a solution yet.

**Comment by k-jiang** [comment]
> We've discussed IP forwarding before, and havent found a solution yet.

You have spigot and bungeecord plugin right? Maybe some custom socket will help.
Or if you don't want to go through a rabbit hole, you could use redis just like [RedisBungee](https://github.com/minecrafter/RedisBungee/wiki).

**Comment by HoverEpic** [comment]
IP forwarding is not working as Bungeecord implements it, but ive tried something here https://github.com/DragonetMC/DragonProxy/blob/master/proxy/src/main/java/org/dragonet/proxy/network/PCDownstreamSession.java#L71 and in the Bungeecord plugin here https://github.com/DragonetMC/DragonProxy/blob/master/plugin/bungee/src/main/java/org/dragonet/plugin/bungeecord/DPAddonBungee.java#L92
AND I JUST SEE I NEVER USE xboxliveProfileParts[0] as the IP, and that's the problem.
