### ISSUE TITLE
Error while executing command console flood

### ISSUE THREAD

**Issue by andris155** [DragonetMC/DragonProxy#137]
![kepkivagas](https://user-images.githubusercontent.com/8324198/34071646-7095fcbc-e279-11e7-8318-070ee1f41af5.PNG)

**Comment by coolnickname** [comment]
It doesn't happen for me. Please try the following:

- Post your Java arguments
- Post the _whole_ log, not just a screenshot of a small part. Copy it and paste into a code tag.
- Make sure you're on the latest release
- Try outside of MultiCraft

I think Multicraft might have something to do with it.

EDIT: Also specify which command you're using.

**Comment by Creeperface01** [comment]
Its not only multicraft if you run dragonproxy in IntelliJ or netbeans you will get the same result

**Comment by coolnickname** [comment]
Mhhm. I've read some things about IDEs messing with console input, which might explain why it doesn't work in there. If the error is identical to the one posted above MultiCraft probably has the same interference as IntelliJ that causes the error.

I've tried to launch it myself on Windows from a cmd and it worked fine.

**Comment by lukeeey** [comment]
It *is* an error with multicraft and IDEs. I think we've had this issue before.
