### ISSUE TITLE
Can't Build, Can't Craft, Can't see any Players

### ISSUE THREAD

**Issue by WoweePaw** [DragonetMC/DragonProxy#14]
Using Spigot 1.8.8 and R6 of DragonProxy

Minecraft 1.8.8 can see 0.15.4 Players but 0.15.4 can't see Minecraft (Java) Players. I'm also not allowed to craft and/or build anything. :/

Sorry if this is not yet implemented. Then I understood that wrong. I liked the idea much so hopefully this is (if not already done and implemented) a Feature in the future and again if this is already implemented then it's not working. :)

**Comment by TheDiamondYT1** [comment]
Can you connect to the PC server on 0.15.4? I cant

**Comment by WoweePaw** [comment]
I connected w/o Problems, my 0.15.4 Client is visible on Java Minecraft but Java Minecraft is not visible on 0.15.4 and all the stuff above (no Building, no block breaking etc.)

**Comment by TheDiamondYT1** [comment]
For me the server doesnt recognize the login packet

**Comment by TheDiamondYT1** [comment]
@D3thw0lf What's the IP? i get client crash on offline mode servers

**Comment by WoweePaw** [comment]
It's localhosted ;)

http://pastebin.com/v1FgxAbS <- Dragonproxy Config
http://pastebin.com/ZasHDk7i <- Server Properties (it's just a default config)

Dragonproxy used: dragonproxy-0.0.6-preR1 (04.08.2016 18:35)

Found the java error in console log
`[37m
[36m[2016/08/04 19:35:11][37m [WARNUNG] java.lang.ClassCastException: java.lang.Byte cannot be cast to org.spacehq.mc.protocol.data.game.ItemStack[37m
[36m[2016/08/04 19:35:11][37m [WARNUNG]   at org.dragonet.proxy.network.translator.pc.PCEntityMetadataPacketTranslator.translate(PCEntityMetadataPacketTranslator.java:37)[37m
[36m[2016/08/04 19:35:11][37m [WARNUNG]   at org.dragonet.proxy.network.translator.pc.PCEntityMetadataPacketTranslator.translate(PCEntityMetadataPacketTranslator.java:25)[37m
[36m[2016/08/04 19:35:11][37m [WARNUNG]   at org.dragonet.proxy.network.PacketTranslatorRegister.translateToPE(PacketTranslatorRegister.java:131)[37m
[36m[2016/08/04 19:35:11][37m [WARNUNG]   at org.dragonet.proxy.network.PCDownstreamSession$1.packetReceived(PCDownstreamSession.java:109)[37m
[36m[2016/08/04 19:35:11][37m [WARNUNG]   at org.spacehq.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:50)[37m
[36m[2016/08/04 19:35:11][37m [WARNUNG]   at org.spacehq.packetlib.tcp.TcpSession.callEvent(TcpSession.java:131)[37m
[36m[2016/08/04 19:35:11][37m [WARNUNG]   at org.spacehq.packetlib.tcp.TcpSession$3.run(TcpSession.java:324)[37m
[36m[2016/08/04 19:35:11][37m [WARNUNG]   at java.lang.Thread.run(Unknown Source)[37m`

Using Spigot 1.8.8 (fresh compiled from source) but Java Minecraft (Vanilla) Server works, too with that copy of Dragonproxy instead of the stuff i've written earlier.

**Comment by DefinitlyEvil** [comment]
@D3thw0lf You are using offline mode(No premium authentication) on DP but you didn't edit Bukkit config so it will crash.

**Comment by WoweePaw** [comment]
@DefinitlyEvil It hasn't crashed for me (yet) and I've edited offline mode in spigot config. 

I've never written that it Crashs for me. Please read my first post!

**Comment by DefinitlyEvil** [comment]
And yes, there are lots of things not updated to 0.15.x yet. xD soz

**Comment by ZedCee** [comment]
DragonProxy 0.0.5 allows login with `online-mode` off.
Can confirm no building/breaking, behaves suspiciously like spectator mode regardless of gamemode.  Saw a chat message that I was not allowed to place blocks, cannot reproduce it though.

OS: Arch Linux
Client: 0.15.6 iOS

**Comment by TheDiamondYT1** [comment]
I will reimplement console log saving and make it strip colour codes

**Comment by ZedCee** [comment]
Started showing up again.  "You cannot place blocks here"

**Comment by WoweePaw** [comment]
^ this

**Comment by TheDiamondYT1** [comment]
Idk where that message comes from... The server? Proxy?

**Comment by Pet0203** [comment]
Disable chat translating from PC to PE and then you will know
