### ISSUE TITLE
Can't change to another world

### ISSUE THREAD

**Issue by KangYui** [DragonetMC/DragonProxy#14]
used too many times to load map.. world change is more severe.

**Comment by DefinitlyEvil** [comment]
When you in online-mode, server take time to validate your token so it will be longer. And if it doesn't load after a long time(like 20secs), you may re-connect. xD

**Comment by KangYui** [comment]
https://youtu.be/3DfNjSxGSDM
2015. 12. 19. 오전 1:55에 "The Evil Man" <notifications@github.com>님이 작성:
