### ISSUE TITLE
I cannot download any builds from Circle CI

### ISSUE THREAD

**Issue by MinecraftDash23** [DragonetMC/DragonProxy#144]

**Comment by destruc7i0n** [comment]
You need to be signed in to be able to download artifacts.

**Comment by TheDiamondYT1** [comment]
Please login with your Github Account and then download

**Comment by MinecraftDash23** [comment]
The thing is... I'm signed in! No download button anywhere. I've tried on my iPhone and on my PC

**Comment by destruc7i0n** [comment]
Go to the "artifacts" tab.
Ex: https://circleci.com/gh/DragonetMC/DragonProxy/311#artifacts
