### ISSUE TITLE
ViaVersion : the same with DragonProxy ?

### ISSUE THREAD

**Issue by TheIntelloBox** [DragonetMC/DragonProxy#144]
Hello !

Could you do DragonProxy like ViaVersion : you can put the plugin on the server, and then th players can connect to the server with their PE Edition ?

Thanks !

**Comment by DefinitlyEvil** [comment]
sorry we can't

**Comment by ghost** [comment]
It can't be a plugin because Java edition and Bedrock edition use completely different protocols.

**Comment by lukeeey** [comment]
@v0idst4r Each minecraft version has different protocols. What's what ViaVersion does, it implements those protocols.

This could be done, but we don't *want* to.

**Comment by ghost** [comment]
Java edition uses TCP and Bedrock edition uses UDP. If all the plugin does is start up DragonProxy then sure, but you won't be making Bukkit understand RakNet.

**Comment by lukeeey** [comment]
Yes you can. You just start a RakNet server from the plugin. 

Have you never heard of ProtocolSupport? https://github.com/ProtocolSupport/ProtocolSupport/tree/mcpenew

**Comment by ghost** [comment]
Did you not read the "If all the plugin does is start up DragonProxy then sure, but you won't be making Bukkit understand RakNet" bit? The point is viaversion doesn't start a separate server, but if we wanted to support PE on Bukkit you would have to.

**Comment by lukeeey** [comment]
Yes it is possible as i said

**Comment by ghost** [comment]
But there's no point in it being a plugin then.
