### ISSUE TITLE
Cant see Chat or Players

### ISSUE THREAD

**Issue by TheMasterBlaster** [DragonetMC/DragonProxy#145]
When using the 0.3.0 version of DragonProxy on a 1.12.2 server the Bedrock player is not getting Chat or Player movement updates. But Java players can. 

[Edit] Java server was "mc.gingycraft.net", and also uses Bungeecord.

**Comment by HoverEpic** [comment]
Can you post a proxy log?

**Comment by TheMasterBlaster** [comment]
So.. Now everytime a Bedrock client joins and logs in the Client crashes.

Console screenshot: https://gyazo.com/5f803628bf3b3fc669b16a0b6913f8d2
[Edit] Im not getting Log files from DragonProxy

**Comment by HoverEpic** [comment]
Ok, what version of Java are you using?

**Comment by TheMasterBlaster** [comment]
"Java Version 9.0.1 (build 9.0.1+11) amd 64"

**Comment by DefinitlyEvil** [comment]
Java 9 is NOT supported, please switch to Java 8. ;)

**Comment by HoverEpic** [comment]
We need to write it in the readme

**Comment by TheMasterBlaster** [comment]
Changing to Java 8 has fixed the login issues, but Bedrock Client still is unable to see server chat or players.
https://gyazo.com/67c88b94f1a8cbf0545283bb18b4fd2b

[Edit]
I did a recompile and now Bedrock Client see this
https://gyazo.com/bdb86156baeea9867e9915f6b4489e73
But still dont see chat or Java player movement

**Comment by HoverEpic** [comment]
Is it a 1.8 like server? With a protocole conversion 1.8 to 1.12.2? It can be the problem.

**Comment by TheMasterBlaster** [comment]
Its 1.12.2 server, it has all the blocks and items.

**Comment by HoverEpic** [comment]
Ok, i don't know where does it come from. We have to investigate.

**Comment by TheMasterBlaster** [comment]
Ill ask if I can get the BungeeCord version as well as the Spigot server version the server is using if that will help any.

**Comment by HoverEpic** [comment]
Ok, thanks.

**Comment by TheMasterBlaster** [comment]
So I did a test with a random server and Chat and players do work to some extent. 
https://gyazo.com/2c69018e8410c210294955ddd764ca2a

[Edit]
Got this after a Java player was TPed away. https://pastebin.com/PN1AkFNG

**Comment by DefinitlyEvil** [comment]
@TheMasterBlaster pls try to use the latest dev one, i fixed a critical bug of chunk translation which crashes the clients.

**Comment by TheMasterBlaster** [comment]
Iv not had any issue with Client crashes since I changed the Java Version the other day.

**Comment by DefinitlyEvil** [comment]
@TheMasterBlaster but pls still build using latest `dev` branch.

**Comment by TheMasterBlaster** [comment]
I think that is what Im doing but I am not 100% sure.

**Comment by DefinitlyEvil** [comment]
client will not be updated if you got disconnected from remote server so maybe you were kicked.

**Comment by HoverEpic** [comment]
Have you tried with the latest release?

**Comment by DefinitlyEvil** [comment]
sometimes it just like being disconnected, no updates, no shit. maybe I suppressed some Exceptions by catching them??

**Comment by HoverEpic** [comment]
Ok, so we have to handle server disconnect properly, im also having an issue with that on localhost, if you shutdown the minecraft server, the proxy don't handle the disconnection.

**Comment by DefinitlyEvil** [comment]
yeah xD
