### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by hafarooki** [DragonetMC/DragonProxy#146]
When I try to connect to my dragonet server, everything works up until I submit my password, then it kicks me and it says it failed to log in.

**Comment by DefinitlyEvil** [comment]
Do not spam login too many times, Mojang will ban your IP for several minutes.

**Comment by hafarooki** [comment]
Thanks for the tip lol, but I knew that - I only tried it a few times.

**Comment by hafarooki** [comment]
http://prntscr.com/hq0vkb

**Comment by lukeeey** [comment]
What does the console say?

**Comment by hafarooki** [comment]
http://prntscr.com/hq0ygo Nothing interesting

**Comment by hafarooki** [comment]
Could it be having an error when it tries sending the web request or something?

**Comment by hafarooki** [comment]
I'm pretty sure it's something like that since I got it to work on my local computer but not the remote computer....

**Comment by DefinitlyEvil** [comment]
I am closing this for now, pls re-open if u find a problem of DragonProxy caused this
