### ISSUE TITLE
Block data values don't send correctly

### ISSUE THREAD

**Issue by hafarooki** [DragonetMC/DragonProxy#147]
MCPE version: 
![image](https://user-images.githubusercontent.com/6323125/34216708-1ea3596c-e577-11e7-8bbd-32ba1bb51936.png)
Actual thing:
![image](https://user-images.githubusercontent.com/6323125/34216733-2f0dbb94-e577-11e7-9cda-3c37449b2ed4.png)
I think the block data values for PE are different from the ones in JE.

**Comment by ApocalypsjeNL** [comment]
I think that has to do something with the point that the JE edition used NBT data for block values, and that they aren't (correctly) translated to the PE edition

**Comment by hafarooki** [comment]
Nope, it's 1.12.2, not 1.13, and they're not making it use NBT data, they're making each variant have its own block ID

**Comment by ApocalypsjeNL** [comment]
Oh I'm mixing things up. This issue looks like an translation error with block id's

**Comment by hafarooki** [comment]
Yep, I think there may need to be some sort of offset applied, and if it's not that simple, then some sort of map for block data.

**Comment by ApocalypsjeNL** [comment]
Is this happening to other blocks as well? Or only these blocks

**Comment by hafarooki** [comment]
If you look closely, you can see that it affects stained glass too.

**Comment by hafarooki** [comment]
Oh, and buttons!

**Comment by ApocalypsjeNL** [comment]
I think buttons has to do with what I said earlier, that block data isn't sent (or incomplete) https://minecraft.gamepedia.com/Button#Block_state

**Comment by hafarooki** [comment]
At least in 1.12.2, button direction depends on block data, not NBT.

**Comment by hafarooki** [comment]
(Otherwise my starships plugin would have infinite borking)

**Comment by hafarooki** [comment]
I took a closer look and that wiki thing is referring to resourcepacks, this does not apply here.

**Comment by ApocalypsjeNL** [comment]
Yeah my fault, forgot that JE uses block data rather then NTB

**Comment by HoverEpic** [comment]
the block translator don't handle complex data values (facing, colors...), we have to work on that too.

**Comment by HoverEpic** [comment]
I'm thinking about making a work on this, with custom BlockEntry.
@ApocalypsjeNL have you already some work on this that can be commited?

**Comment by ApocalypsjeNL** [comment]
I'm gonna commit my changes soon yes, don't have that much time now because of Christmas

**Comment by HoverEpic** [comment]
I think it's good.
