### ISSUE TITLE
Bukkit Player IP is Proxy's IP

### ISSUE THREAD

**Issue by KangYui** [DragonetMC/DragonProxy#15]
no ip forwarding...

**Comment by DefinitlyEvil** [comment]
Yes, unfortunately, I think thee is no way to fix this. :(

**Comment by KangYui** [comment]
No, You can fix it via send BungeeCord's IP Forwarding packet.

**Comment by DefinitlyEvil** [comment]
Okay, will try.

**Comment by DefinitlyEvil** [comment]
Faild. xD Let's close this.

**Comment by KangYui** [comment]
If i success this, i can pull request for this?
2015. 12. 22. 오전 2:03에 "The Evil Man" <notifications@github.com>님이 작성:

**Comment by DefinitlyEvil** [comment]
@KangYui Sure, I will be very appreciated. :P
