### ISSUE TITLE
How does Authentication work?

### ISSUE THREAD

**Issue by xXAndrew28Xx** [DragonetMC/DragonProxy#150]
Could MCPE players impersonate PC names (such as Notch)?

**Comment by Pet0203** [comment]
If Dragonproxy is set no offline mode, yes. But if you have it set to cls or online mode, players have to sign in through their Mojang account and have a valid Minecraft account on it. Authentication via cls is through Dragonet's homepage. If you have set auth to online, then the player will have to enter Mojang e-mail and password in the chat before the proxy sends the player to the server.

**Comment by xXAndrew28Xx** [comment]
Oh, no idea it had a forums. Thank you

**Comment by Pet0203** [comment]
No problems at all ;)
