### ISSUE TITLE
MCPE 0.15.0 Support

### ISSUE THREAD

**Issue by File14** [DragonetMC/DragonProxy#151]
Please update so it supports MCPE 0.15.0. Many thanks!

**Comment by TheDiamondYT1** [comment]
We are working on this

**Comment by File14** [comment]
Thanks a lot! :+1:

**Comment by TheDiamondYT1** [comment]
https://github.com/DragonetMC/DragonProxy/commit/0a24b1e9adc6f1979d6ccecfa31373e1d794c59e - I have made a commit to change the protocol number so you wont get the 'Outdated server message', but it wont join untill we update some more things.

**Comment by File14** [comment]
How long will it take until it is finished? I'm waiting for it.

**Comment by Pet0203** [comment]
It will take some time, they have changed pretty much. I'm trying to get it working (I don't have good skills) but failing all the time. I guess when the team has time to sit down and start developing. Be patient.

**Comment by File14** [comment]
Okay thanks.

**Comment by TheDiamondYT1** [comment]
0.15 progress will now be tracked in #153.
