### ISSUE TITLE
HELP WANTED

### ISSUE THREAD

**Issue by 2449673842** [DragonetMC/DragonProxy#154]
i dao't know how to use this ,i am using pocketmine please help me,thanks so much

**Comment by TheDiamondYT1** [comment]
It currently doesnt work.

**Comment by TheDiamondYT1** [comment]
We need to update to 0.15 for it to work

**Comment by TheDiamondYT1** [comment]
*cough* @DefinitlyEvil

**Comment by 2449673842** [comment]
OK i will wait for it please remind me on time

**Comment by 2449673842** [comment]
and it's php5?

**Comment by TheDiamondYT1** [comment]
its java 8

**Comment by TekkitCommando** [comment]
How does one mix up PHP and Java lol

**Comment by DefinitlyEvil** [comment]
Wtf that's insane, u can combine PHP w/ C++ or Python with C++ or even C# with C++ (Using CLR), but PHP+Java would be come a disaster! xD

**Comment by TekkitCommando** [comment]
@DefinitlyEvil I have worked on Java applications that talk to PHP softwares on the web before :P

**Comment by robske110** [comment]
Of course java+php is no disaster.
PHP = WEB
Java = LOCAL
many companies have java backend servers that talk with the php frontend web-server

**Comment by DefinitlyEvil** [comment]
@robske110 You need either to code a PHP extension or to use sockets.
