### ISSUE TITLE
how

### ISSUE THREAD

**Issue by majovec** [DragonetMC/DragonProxy#16]
Hallo how to instal on debian pls tutorial

**Comment by ethsmith** [comment]
What do you mean? It's a proxy server written in Java. It isn't OS specific installations.

**Comment by majovec** [comment]
i have VPS debian 7  3 GB ram

**Comment by majovec** [comment]
how first install bukkit ?

**Comment by ethsmith** [comment]
https://www.spigotmc.org/wiki/spigot-installation/#linux This is how you run a spigot server that will run the bukkit plugins.

**Comment by majovec** [comment]
and how install dragonet proxy on spigot

**Comment by ethsmith** [comment]
You run it as a separate server.

**Comment by majovec** [comment]
So first I install spigot server. then?  I still don't get it

**Comment by ethsmith** [comment]
Install the spigot server, then run it. Then install the DragonProxy server and run that, fill in the DragonProxy config and then connect with PE. I believe @DefinitlyEvil can give you better instructions.

**Comment by majovec** [comment]
ok thanks and pls install comand on dragon

**Comment by DefinitlyEvil** [comment]
@majovec I suggest you to use Screen (Install with `sudo apt-get install screen`), and plz Google for usage.
