### ISSUE TITLE
MCPE stuck at 'Locating server'

### ISSUE THREAD

**Issue by ExtaSpace** [DragonetMC/DragonProxy#16]
MCPE all the time is stuck at locating server. Am I doing anything wrong? Problem is on both pre-releases. Also tried different remote IP's - no luck. If I click disconnect, console shows '[INFO] Client null[/192.168.1.101:19132] disconnected! Reason: Client disconnect'.

**Comment by DefinitlyEvil** [comment]
What version of MCPE ur using?

**Comment by DefinitlyEvil** [comment]
Seems fixed.
