### ISSUE TITLE
Sending AddEntityPacket with player entity seems to make the game to crash.

### ISSUE THREAD

**Issue by francois76** [DragonetMC/DragonProxy#160]
The client crash when a AddEntityPacket related to a player is sent by the server. Testing if the entity is a player in PCEntityMetadataPacketTranslator class avoid the crash.

Here is the data of the entity that make the game to crash:
CachedEntity [eid=16812, proxyEid=1, pcType=-1, peType=PLAYER, objType=null, player=true, playerUniqueId=null, x=-183.09290923914443, y=45.0, z=1383.0902228284856, motionX=0.0, motionY=0.0, motionZ=0.0, yaw=91.23328, headYaw=0.0, pitch=18.631866, shouldMove=true, spawnPosition=org.dragonet.proxy.utilities.BlockPosition@367f5f52, helmet=null, chestplate=null, leggings=null, boots=null, riding=0, passengers=[], pcMeta=[EntityMetadata(id=0, type=BYTE, value=0)], spawned=true, effects=[], attributes={}]
The crash happened on login on epicube.

**Comment by HoverEpic** [comment]
Uuid null is probably the problem.

**Comment by francois76** [comment]
I found a fix for this issue: sending a addPlayerPacket instead of a addEntityPacket. I'm about to send a pull request with that fix.

**Comment by HoverEpic** [comment]
I wonder in what case we send an player entity as a normal entity, I think I have missed a point somewhere.

**Comment by DefinitlyEvil** [comment]
you always use AddPlayerPacket to add players instead of AddEntityPacket

**Comment by francois76** [comment]
in PCEntityMetadataPacketTranslator, AddEntityPacket is used to update cached entities that haven't been spawned yet, so if a server wants to update a player before spawning him, that packet is used instead of AddPlayerPacket (see also https://github.com/DragonetMC/DragonProxy/pull/161/files for a fix to that).

**Comment by HoverEpic** [comment]
But the player is spawned on received, and the spawned field is always on true
