### ISSUE TITLE
No logs in Bungeecord, connection problems

### ISSUE THREAD

**Issue by HoverEpic** [DragonetMC/DragonProxy#166]
Some people reported a weird bug :
When hosted on the same machine, the proxy cannot reach the Bungeecord, no errors on proxy and no logs on Bungeecord.
Here is a list of bungeecord plugins for a case : 
![plugins](https://user-images.githubusercontent.com/3588249/34363431-5763e046-ea7c-11e7-89d8-984ed19ab301.PNG)

**Comment by tr7zw** [comment]
Plugins that look like they might cause something like that: ABPS, AntiBotDeluxeEX, FastLogin, ViaVersion on bungee. They could do stuff to the connection breaking something.

**Comment by DefinitlyEvil** [comment]
DragonProxy relies on a ServerPlayerPositionRotationPacket to know the player is spawned, so if the server doesn't send that, it will not work.

**Comment by HoverEpic** [comment]
The problem is the server doesn't send anything, downstream bridge is never connected.

**Comment by DefinitlyEvil** [comment]
Huh, that's shit. xD @HoverEpic how could it be? 😅

**Comment by HoverEpic** [comment]
Probably as @tr7zw said, a plugin that block 127.0.0.1 incoming connection in Bungeecord.
If we want Minecraft networks use our proxy, we need to make a list of non compatible plugins, thats why i let open this issue to gather informations about bugs like this.

**Comment by HoverEpic** [comment]
The issue come from ip restriction on Bungeecord, so it's not our probleme. Owners have to be carefull about this.
