### ISSUE TITLE
Suggestion : config en_us messages

### ISSUE THREAD

**Issue by Waooto** [DragonetMC/DragonProxy#168]
I went inside the root folder of the DragonProxy jar, and i found the en_us.properties file, which contains all of the messages that you can edit.

Maybe make it so if the message is just 'null', then it wouldn't send the message?

Example: 
form_login_desc=**null**

Would mean **form_login_desc**, wouldn't be sent to the Client

**Comment by DefinitlyEvil** [comment]
hmmm, that will be a low priority thing but maybe later. 
thanks for the suggestion tho!
