### ISSUE TITLE
All Stucks

### ISSUE THREAD

**Issue by Erkam246** [DragonetMC/DragonProxy#182]
[![Video Link](https://i.ytimg.com/vi/b8GrUEhrQac/hqdefault.jpg?sqp=-oaymwEXCPYBEIoBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBekfQnue641aLUJBmkzrJdBSHuUw)](https://www.youtube.com/watch?v=b8GrUEhrQac)

**Comment by HoverEpic** [comment]
I'm on it.

**Comment by Erkam246** [comment]
ok nice :)

**Comment by francois76** [comment]
do you know if dragonproxy is allowed on hypixel, and if it can result in a ban in case of wrong packet sent to the server?

**Comment by HoverEpic** [comment]
Fixed on [0.3.4.1](https://github.com/DragonetMC/DragonProxy/releases/tag/0.3.4.1).

**Comment by Erkam246** [comment]
Is not fixed!

**Comment by Erkam246** [comment]
It works only sometimes

**Comment by HoverEpic** [comment]
Can you reproduce the bug? I I think i need more datas.

**Comment by Erkam246** [comment]
I created a new issue

**Comment by Erkam246** [comment]
Can i write to you over twitter?

**Comment by HoverEpic** [comment]
Nope, but you can join our discord.

**Comment by ApocalypsjeNL** [comment]
If you need an invite link, here it is: https://discord.gg/grFtgfZ

**Comment by HoverEpic** [comment]
@francois76, i got banned from Epicube, so i think this will be the same on Hypixel ^^
You can also join our discord, it's good see more Frenchies on the project =)

**Comment by HoverEpic** [comment]
and should be fixed
