### ISSUE TITLE
World changing Hangs

### ISSUE THREAD

**Issue by Erkam246** [DragonetMC/DragonProxy#188]
Change world and you will get no packets anymore

**Comment by DefinitlyEvil** [comment]
yeah that's a problem... :/

**Comment by HoverEpic** [comment]
Should be fix, see https://github.com/DragonetMC/DragonProxy/releases/tag/0.3.4.2

**Comment by DefinitlyEvil** [comment]
not rly fixed... sometimes it still hangs

**Comment by Erkam246** [comment]
yes

**Comment by DefinitlyEvil** [comment]
but we can say it was improved tho :D

**Comment by Erkam246** [comment]
If i will teleported to another server by bungee it hangs

**Comment by HoverEpic** [comment]
On world change it's ok, so bungee change server is probably a different process.

**Comment by Erkam246** [comment]
and world changing is too a problem

**Comment by TheMasterBlaster** [comment]
Iv not noticed many issues on server changed when using Bungeecord. Yes sometimes it glitches but i can change servers on Bungee 75% of the time with no issues

**Comment by DefinitlyEvil** [comment]
@TheMasterBlaster  true

**Comment by HoverEpic** [comment]
Same problem than #220
