### ISSUE TITLE
Why certain blocks do not render properly

### ISSUE THREAD

**Issue by HoverEpic** [DragonetMC/DragonProxy#190]
Find why blocks entities render badly on world join but not on item place.
(Works in PCBlockChangePacketTranslator but not in PCChunkDataPacketTranslator)
  - [x] Signs post and standing
  - [ ] Shulker (missing direction)
  - [ ] Double Chests
  - [x] Beds
  - [x] Ender chest
  - [x] Trapped chest
  - [ ] Piston arm
  - [x] Skull

**Comment by DefinitlyEvil** [comment]
they are tile entities and requires NBT ^^

**Comment by HoverEpic** [comment]
there is !

**Comment by DefinitlyEvil** [comment]
ahhh then it's weird lel

**Comment by HoverEpic** [comment]
Seems NBT not working, but the process is ok...

Edit it's not OK !
https://github.com/DragonetMC/DragonProxy/blob/master/src/main/java/org/dragonet/proxy/network/translator/pc/PCChunkDataPacketTranslator.java

**Comment by HoverEpic** [comment]
Just fixed beds, signs and chests display \o/ https://github.com/DragonetMC/DragonProxy/commit/d76e2ebe2bc60501058cbf24377c88accc75a978

**Comment by DefinitlyEvil** [comment]
nice!

**Comment by Erkam246** [comment]
Fix this pls

**Comment by HoverEpic** [comment]
I'm missing data for shulker and piston arms (block flags).
For double chests, we have to find a way to see on DP if a chest is linked to another from java server.
