### ISSUE TITLE
color on UNIX hosts

### ISSUE THREAD

**Issue by Erkam246** [DragonetMC/DragonProxy#192]
```
[14:54:25] [INFO] §a----[ All commands for DragonProxy ]----
[14:54:25] [INFO] §2help: §fDisplays commands for DragonProxy
[14:54:25] [INFO] §2kill: §fForcefully kill the proxy
[14:54:25] [INFO] §2stop: §fStop the proxy
[14:54:25] [INFO] §2test: §f
```

**Comment by x9nico** [comment]
It is do the same on Windows

**Comment by ApocalypsjeNL** [comment]
It's not a bug, as shown in this code the colors are actually implemented https://github.com/DragonetMC/DragonProxy/blob/master/src/main/java/org/dragonet/proxy/utilities/Logger.java#L57-L64

**Comment by lukeeey** [comment]
@HoverEpic We need to have a method to remove the colour codes if the colorful variable is not true in MCColor

**Comment by ApocalypsjeNL** [comment]
Should be an easy fix, and maybe als add an option to the config? Because the Boolean is defined at the top of the file and never updated anywhere

**Comment by lukeeey** [comment]
I put the boolean there because i forgot to add an option to disable ansi

**Comment by lukeeey** [comment]
I could add a startup option to disable ansi

**Comment by HoverEpic** [comment]
Or we need to implements ansii colors codes.

**Comment by ApocalypsjeNL** [comment]
They are, as mentioned above https://github.com/DragonetMC/DragonProxy/blob/master/src/main/java/org/dragonet/proxy/utilities/Logger.java#L57-L64

**Comment by lukeeey** [comment]
Look at MCColor.java @HoverEpic

**Comment by DefinitlyEvil** [comment]
I think it uses ANSI color codes.

**Comment by ApocalypsjeNL** [comment]
It does indeed @DefinitlyEvil, only problem is that colorful (https://github.com/DragonetMC/DragonProxy/blob/master/src/main/java/org/dragonet/proxy/utilities/Logger.java#L22) always false is because it's never updated somewhere, and so is the ansi color function never been called

**Comment by DefinitlyEvil** [comment]
@ApocalypsjeNL ahh I see

**Comment by HoverEpic** [comment]
No it does not implements ansii colors, it's minecraft colors, two different things (we need this https://github.com/fusesource/jansi)

**Comment by HoverEpic** [comment]
I just woke up I missread >< (didtn't see the toANSI()....) let' fix this =)

**Comment by HoverEpic** [comment]
It's fixed in the next release (https://github.com/DragonetMC/DragonProxy/commit/e4a1806e38befc3a6e61e26a0935841e6f91ec3c)
