### ISSUE TITLE
Items custom name

### ISSUE THREAD

**Issue by Erkam246** [DragonetMC/DragonProxy#193]
Name of item is on mc pc "Teleporter" but with DragonProxy "Compass"

Custom names will not be shown

**Comment by HoverEpic** [comment]
I've started something in https://github.com/DragonetMC/DragonProxy/blob/master/src/main/java/org/dragonet/proxy/network/translator/ItemBlockTranslator.java#L344

**Comment by DefinitlyEvil** [comment]
yep, NBT stuff. 
but I think in 1.13 since they remove all IDs we should probably switch all IDs to strings.

**Comment by HoverEpic** [comment]
Fixed in https://github.com/DragonetMC/DragonProxy/commit/c3ef3d040cadb9adc4f2758e5c137bcec576a9c5
