### ISSUE TITLE
ChatComponents on Signs Bug

### ISSUE THREAD

**Issue by HoverEpic** [DragonetMC/DragonProxy#195]
Signs do not render correctly, exemple on simple text on sign:
![image](https://user-images.githubusercontent.com/3588249/34622869-32209ab0-f24f-11e7-84a7-7a60868e79f8.png)
![image](https://user-images.githubusercontent.com/3588249/34622986-ae3ec18a-f24f-11e7-94be-9444929f0458.png)

And with chat components signs, it doesn't work :
![image](https://user-images.githubusercontent.com/3588249/34623106-1e0ce91a-f250-11e7-97fe-5a1a8e16e370.png)

Already tried to work around this : https://github.com/DragonetMC/DragonProxy/blob/master/src/main/java/org/dragonet/proxy/network/translator/ItemBlockTranslator.java#L245

**Comment by DefinitlyEvil** [comment]
why black turned into white :O

**Comment by tr7zw** [comment]
http://tr7zw.de/u/1519612121.png Signs without text is still a thing
