### ISSUE TITLE
Only connects to 1.8.x servers

### ISSUE THREAD

**Issue by iDerp** [DragonetMC/DragonProxy#20]

**Comment by iDerp** [comment]
I meant to give a desc before posting but I can only connect to servers if it's running 1.8. I cant connect to my 1.10.2 server but can't see anything. It has protocolsupport installed but no matter what I can see or move on my server. Also I can't believe it even works on 1.8 and when I try to interact with anything it says I can't build here

**Comment by Pet0203** [comment]
Duplicate issue with #1 . Please read all the other issues before posting a new one. We are working on 1.10.x but the development has stopped for some reason now, I believe it is because of maven.

**Comment by TheDiamondYT1** [comment]
Yeah, i broke it :(

**Comment by iDerp** [comment]
Is there a way to fix it or maybe revert from maven?

**Comment by TheDiamondYT1** [comment]
Well the problem was maven modules. Im trying to get @mastercs to come amd fix it.

**Comment by iDerp** [comment]
Did the problem start when it was originally switched to maven? and Ok

**Comment by TheDiamondYT1** [comment]
Its always been maven i said maven modules

**Comment by iDerp** [comment]
Oh. Didn't read the correctly.

**Comment by TheDiamondYT1** [comment]
Also i meant @mastercoms

**Comment by iDerp** [comment]
Ok, because when I looked at @mastercs profile it seemed inactive
