### ISSUE TITLE
Cannot move from spawn (anti-cheat?)

### ISSUE THREAD

**Issue by Creeperface01** [DragonetMC/DragonProxy#200]
I tried to connect to play.gameteam.cz but I cannot move from spawn anticheat still teleports me back

**Comment by Erkam246** [comment]
I have the same problem on an another server

**Comment by TheMasterBlaster** [comment]
Im not having this issue and the server im using has NoCheatPlus installed.

**Comment by ghost** [comment]
i am ,and it happens 99% of time time i join

**Comment by ghost** [comment]
or when i get teleported

**Comment by Creeperface01** [comment]
its maybe anticheat, but maybe vanilla anticheat, because I spawn something around 0.1 Y less so im in the block and it always teleports me back to this block again, so something is wrong with coordinates rounding from double to float probably

**Comment by HoverEpic** [comment]
hum, i'll take a look.

**Comment by tr7zw** [comment]
Yea I also noticed that on logging in the client tends to get stuck in the floor. Ncp doesn't seem to have a direct problem with DragonProxy, except with stuff like snow layer, slabs and stairs. But I've seen that there are anticheats flagging basic walking/jumping.

**Comment by HoverEpic** [comment]
Take a look at the pe player move translator and try to remove the ceil half thing, probably that.

**Comment by HoverEpic** [comment]
Any news in that? Can someone test with fresh build on multiple servers?

**Comment by Creeperface01** [comment]
Tested with latest build and exactly the same issue but what was not there before is that now I get kicked from server after a few seconds:

[INFO] Client CreeeperFace[/192.168.1.99:55320] disconnected! Reason: Client disconnect
DisconnectingEvent Disconnect
DisconnectedEvent Disconnect

**Comment by Creeperface01** [comment]
jumping and hand animation probably have something to do with adventure settings or attributes

**Comment by HoverEpic** [comment]
Server side log? Spawn position y?

**Comment by Creeperface01** [comment]
I don't know that :/

**Comment by Creeperface01** [comment]
Sorry my fault, I forgot to register, but another bug, messages sent in early joining don't show. However jumping and hand animation still don't work

**Comment by HoverEpic** [comment]
The spawn position is displayed in DragonProxy log at spawning, I have not tested spawn on half block yet, it will propably cause some errors.

**Comment by HoverEpic** [comment]
I have added a packet queue for packet received before spawn, messages issue still appear? and spawn issue?

**Comment by k-jiang** [comment]
jump:
`[NCP]: The player xxxx caused the check SurvivalFly to go up very high to 26004. Please investigate this issue.`

move:
```
[22:11:38 WARN]: xxxx moved wrongly!
[22:11:52 WARN]: xxxx moved too quickly! 2158.302490234375,-3.5,4597.791259765625
```

This player is standing on a `wooden_slab`.
Test with [build 146](https://ci.codemc.org/job/DragonetMC/job/DragonProxy/146/). For some reason any normal movements become exaggerated (a jump with height of 26004?!). Seems that there are something wrong with DP, not anticheat.
