### ISSUE TITLE
Login Idea/Question

### ISSUE THREAD

**Issue by TheMasterBlaster** [DragonetMC/DragonProxy#202]
Is it possible to set up DragonProxy to remember the last PC/Mac account you logged in as and just re-log you back in as that PC/Mac account? figured since DragonProxy can verify your XBox Live account maybe it could be a temporary thing that resets after the Proxy restarts? Just an idea to make it a little easier for players with complicated passwords like mine.

**Comment by DefinitlyEvil** [comment]
YES, there will be a CLSv2 which you can bind MCJE accounts to your xbox account and choose via a custom GUI!
