### ISSUE TITLE
Timings

### ISSUE THREAD

**Issue by HoverEpic** [DragonetMC/DragonProxy#204]
Hi everybody ! Have someone ever works with [Aikar Timings](https://timings.aikar.co/)?
I've created a [branch](https://github.com/DragonetMC/DragonProxy/tree/timings) on this project to be able to post DragonProxy Timings to web view [here](https://github.com/DragonetMC/DragonProxy/tree/timings/src/main/java/co/aikar/timings).
I've customized a bit [timers](https://github.com/DragonetMC/DragonProxy/blob/timings/src/main/java/co/aikar/timings/Timings.java), but when posting timings, it only display the server tick, not the network handlers.

If you have some ideas, please take a look, with this, we can probably fix some lag issues !

**Comment by whirvis** [comment]
Links are broken
