### ISSUE TITLE
please join Chinese language!

### ISSUE THREAD

**Issue by shaokeyibb** [DragonetMC/DragonProxy#205]
**I have a translaten file,you can just take it to your project!**
https://www.dropbox.com/s/bscqniq531chdd9/zh_CN.properties?dl=0

**Comment by HoverEpic** [comment]
https://github.com/DragonetMC/DragonProxy-Translations

**Comment by DefinitlyEvil** [comment]
@shaokeyibb hello, please send a PR to us! 
@HoverEpic that translation was outdated

**Comment by HoverEpic** [comment]
ok, then thanks @shaokeyibb 
(i don't know if it's outdated, i just send the right repo to publish. That was a too short response)

**Comment by shaokeyibb** [comment]
OK，and I just can't understand what PR is?

**Comment by HoverEpic** [comment]
It's  a request with your modifications, if you want your name appear as contributor.

**Comment by ApocalypsjeNL** [comment]
PR = pull request. If you don't know how to create one then people here can do it also for you

**Comment by shaokeyibb** [comment]
Ok,I have finish create PR and maybe something I’m wrong
