### ISSUE TITLE
Bring back maven modules !!!!!!

### ISSUE THREAD

**Issue by HoverEpic** [DragonetMC/DragonProxy#206]
In few days, i'll start another operation on project structure, come back to maven modules to maintaint easily everything.
The main POM will have ~~3~~ 5 modules : 
 - commons (every common libs, tools)
 - abstract API #207
 - protocol (socket + packets)
 - proxy (translators)
 - plugin (bukkit / bungee side plugin)

Each module will create a jar, and should be usefull to setup our maven repository.

~~I wonder if we should create another module for the PE protocol, could be usefull if someone want to create PE minecraft client bots or light server (i think a it personally).~~

I will edit this issue to update the process if needed.

Edit : added api & protocol modules

**Comment by DefinitlyEvil** [comment]
totally agreed!

**Comment by ApocalypsjeNL** [comment]
Yep, would be very nice

**Comment by lukeeey** [comment]
An api module to allow addons to do tasks such as logging chat, moving the player and more

**Comment by HoverEpic** [comment]
Of course, the api will be a separate module =)
https://github.com/DragonetMC/DragonProxy/issues/207

**Comment by HoverEpic** [comment]
Updated

**Comment by lukeeey** [comment]
We can setup a maven repository in a git repo (see https://github.com/TheDiamondYT1/repo.thediamondyt.tk)

**Comment by HoverEpic** [comment]
Thanks, i'll take a look.
Found https://stackoverflow.com/a/14013645 to automate this.

**Comment by HoverEpic** [comment]
I think I will use gh-pages to host maven repository. Uploading artifact will be done via Travis.

**Comment by HoverEpic** [comment]
Already started, look at https://github.com/DragonetMC/DragonProxy/tree/maven-modules

**Comment by HoverEpic** [comment]
Done
