### ISSUE TITLE
Plugin loader

### ISSUE THREAD

**Issue by HoverEpic** [DragonetMC/DragonProxy#207]
After a talk with other developpers of the team, we are thinking about making a plugin loader with a small api.

Here are the features : 
 - onLoad / enable / disable
 - adding commands
 - adding loginhandler
 - packet listening
 - simple events like handshake/playerjoin/playerquit

What do you think about this? What can be missing or useless?

**Comment by DefinitlyEvil** [comment]
this should be useful!

**Comment by HoverEpic** [comment]
@tr7zw ask for this, so it's probably a not idiot thing =P

**Comment by ApocalypsjeNL** [comment]
It could be nice, but don't make it like bungeecord. Keep it simple and build the api on top of dragonproxy and not in dragonproxy

**Comment by yannicklamprecht** [comment]
https://github.com/PluginSystems
https://github.com/PluginSystems/Java-Plugin-System
I think you don't need this.  :)
  
https://github.com/Craftstuebchen/Quantum-Connectors
https://github.com/Craftstuebchen/QuantumDefaultExtension

**Comment by HoverEpic** [comment]
Thanks @ysl3000, seems to be a good one, will take inspiration.

**Comment by lukeeey** [comment]
This was originally my idea 😂

**Comment by ApocalypsjeNL** [comment]
@lukeeey why didn't you create an issue then 😂

**Comment by lukeeey** [comment]
Implement it like in https://github.com/voxelwind/voxelwind without on enable methods but well idk look at https://github.com/TheDiamondYT1/VoxelTest for an example of how the api looked like

**Comment by HoverEpic** [comment]
Thanks @lukeeey (the mother of the project). I will also take a look a this.

**Comment by lukeeey** [comment]
@ApocalypsjeNL Because this was my idea back in 2016

**Comment by HoverEpic** [comment]
https://github.com/DragonetMC/DragonProxy/pull/270
