### ISSUE TITLE
Entities not despawn on world change

### ISSUE THREAD

**Issue by HoverEpic** [DragonetMC/DragonProxy#208]
all is in the title (send entity remove packets for all spawned entities)

**Comment by DefinitlyEvil** [comment]
and clear the entity cache ;)

**Comment by HoverEpic** [comment]
Already done https://github.com/DragonetMC/DragonProxy/blob/master/src/main/java/org/dragonet/proxy/network/translator/pc/PCRespawnPacketTranslator.java#L35

**Comment by DefinitlyEvil** [comment]
noice!

**Comment by HoverEpic** [comment]
the send packet is not done, but the clear cache is ok.

**Comment by HoverEpic** [comment]
Done
