### ISSUE TITLE
Add a mcstats or similar

### ISSUE THREAD

**Issue by HoverEpic** [DragonetMC/DragonProxy#209]
Could be a good idea to add a use statistics in DragonProxy.

**Comment by ApocalypsjeNL** [comment]
Maybe we can setup our own metrics site, and create an api for it so people can use it in their plugins for dp

**Comment by DefinitlyEvil** [comment]
yeah... but we need a webhost, ShockByte will give us shortly

**Comment by lukeeey** [comment]
I can do this :)

**Comment by lukeeey** [comment]
Well mostly anyway i cant do graphs

**Comment by lukeeey** [comment]
Well mostly anyway i cant do graphs

**Comment by ApocalypsjeNL** [comment]
Graphs aren't that hard, just use a JavaScript library :)

**Comment by HoverEpic** [comment]
Why building our own metric site? Mcstats is not good enough?

**Comment by lukeeey** [comment]
Nope its not reliable and is down half the time and the repo isnt updated anymore.

**Comment by DefinitlyEvil** [comment]
lol

**Comment by sgdc3** [comment]
Check out https://bstats.org, it is the most stable and complete metrics system atm. @BToBastian could you register them as server implementation?

Plugins/Server implementations already using bstats: https://bstats.org/plugin-list
Global statistics (just to show that it is currently handling an huge amount of requests without issues): https://bstats.org/global/bukkit

**Comment by HoverEpic** [comment]
Added https://bstats.org/plugin/server-implementation/DragonProxy/
Thanks for the tip !

**Comment by sgdc3** [comment]
Epic! xD
