### ISSUE TITLE
Bug - Trapdoors dont update correctly

### ISSUE THREAD

**Issue by TheMasterBlaster** [DragonetMC/DragonProxy#211]
I am unsure if its something on DragonProxy or just something with MCPE but When updating trapdoors either yourself or by others there are times the trapdoor looks closed but its really open, pic: https://gyazo.com/a649985c248ec74496ef38e4d59376c4

**Comment by HoverEpic** [comment]
Trapdoor were not easy to implements at all, thanks for reporting, I'll take a look.
