### ISSUE TITLE
installation and usage instructions out-of-date/incomplete

### ISSUE THREAD

**Issue by jhwblender** [DragonetMC/DragonProxy#212]
tried to implement with server, but video link is broken and all instructions found do not help or are missing information to get working.

**Comment by TheMasterBlaster** [comment]
Hello jhwblender, If your using shared hosting site like Shockbyte or MCProHosting there is a pretty good chance that their MultiCraft does not support DragonProxy, But if your Home Hosting or using it on a VPN/Dedicated Machine it should work fine. DragonProxy can be started by using the same type of ".bat" file as Spigot/Bukkit/Bungeecord, once booted you can stop the Proxy and open the config and fine this area on the config shown [(HERE)](https://gyazo.com/688178caa20cf00b8a656ac618015ba2) , Find "remote_addr: 'your.java.server.com'" and set it to your MC PC server ip (ex: "12.345.67.890"), Once your config is setup you can start your server back up. I hope this helps you, have a great day!

**Comment by HoverEpic** [comment]
If you want only yourself use the proxy at your home, you can start it on your computer and then connect to it locally to play on your server. 
Some Minecraft hosters do not support DragonProxy now, probably because they secured everything and there firewall block udp.

**Comment by jhwblender** [comment]
This is a personal java edition server. I've been successfully able to start Dragon Proxy and I've changed the remote address in config.yml to reflect the address of my server. I have tried both leaving the binding ip at 0.0.0.0 as well as 127.0.0.1. I've verified all ports are correct and with my firewall both on and off. When I try to connect with the bedrock edition all I get every time is "unable to connect to server".

**Comment by HoverEpic** [comment]
see https://github.com/DragonetMC/DragonProxy/issues/213#issuecomment-356929314

**Comment by TheMasterBlaster** [comment]
What's the bind port you set? And what's the Minecraft server port set to?

**Comment by jhwblender** [comment]
I got it to connect to the Dragon Proxy! The only problem I have now is sometimes it doesn't load past the bedrock temporary screen, sometimes it loads all the way but chests/pressure plates don't work, sometimes it will load the sky and a chunk maybe 2, but then it stops there.

**Comment by HoverEpic** [comment]
The connect issue is closed, other things have to be send in another issue.
