### ISSUE TITLE
Some problems report

### ISSUE THREAD

**Issue by kit8379** [DragonetMC/DragonProxy#215]
When using minecraft pe connect to pc server:
1. GUI can't show  (e.g. server selector)
2. Some problems with jump,walk up stair,sprint. I guess it is related to nocheatplus. Hope you guys can provide some way of how to edit the config and allow minecraft pe run smoothly.
3. Sometimes the chunk can't load, but i think this is not a serious problem.

**Comment by HoverEpic** [comment]
Guis are not working for now.
We can't handle anticheats, it's working on vanilla server, so it's ok for now.
Chunk fail to load sometimes, we are searching why.

**Comment by HoverEpic** [comment]
#220 dupplicated, closing this one.
