### ISSUE TITLE
Problem with carpets

### ISSUE THREAD

**Issue by HoverEpic** [DragonetMC/DragonProxy#217]
When walking from a block to a carpet, you can't go on the carpet, you must jump.

**Comment by Creeperface01** [comment]
its the same problem as slabs/stairs and happens always you step up a block. MCPE simply cuts the edges of block. but quite much so slab BB height is around 0.1 at the end.

**Comment by Creeperface01** [comment]
I think there's not any good solution.

**Comment by HoverEpic** [comment]
I will apply same solution we have done for slabs and stairs.

**Comment by Creeperface01** [comment]
what have you done to fix it? maybe it'll require some universal solution because its still one and same problem.

**Comment by HoverEpic** [comment]
apply code phisics from nukkit only on some blocks =P
@dernise made this, seems to work, but not on all cases.

**Comment by maxencehenneron** [comment]
I can easily add the carpet to the physic engine. At the moment only stairs are fully supported

**Comment by DefinitlyEvil** [comment]
@dernise ftw!!

**Comment by HoverEpic** [comment]
I have added carpets and lily pads.

**Comment by ghost** [comment]
This problem occurs because AABBs on Bedrock Edition behave very differently to Java.

Say you're climbing stairs. On Bedrock, the stairs' bounding box is something like:

```
   /|
 /  |
-----
```

However, Java edition treats it as:

```
  __
_|  |
|___|
```

This becomes problematic because Java edition thinks you're clipping through the stairs, and so will attempt to correct your position. One possible solution is to disable AABB correction through manipulating the Java server (Spigot or otherwise).

**Comment by maxencehenneron** [comment]
Yes, that's what we did and it's actually working. Any packet colliding the java box is simply ignored.

**Comment by maxencehenneron** [comment]
We added the positions of each problematic boxes in a cache and check each movement packets before sending them.

**Comment by DefinitlyEvil** [comment]
but you also killed jumping, jumping with NCP/AC plugins installed will be denied.

**Comment by ApocalypsjeNL** [comment]
Can't we detect if the player is on a stair? And if so manipulate the packet so the correct movement is sent?

**Comment by DefinitlyEvil** [comment]
@ApocalypsjeNL like adding an extra packet to correct the speed vector

**Comment by ApocalypsjeNL** [comment]
Yeah, but maybe also a teleport thing for bedrock -> JE, so it doesn't glitch back

**Comment by ghost** [comment]
Something like that would definitely be a better option if you would rather not make people have to run patched versions of Vanilla/Spigot. It'd be cool to see that, but might be quite a lot of work. 
The odds are you might need to store a cache of all local blocks for the player (5x5 radius maybe), and check the player's position in that set. If they're climbing a stair, you could manipulate the Y vector based on the velocity of a Bedrock client and the required Java AABB.

**Comment by TJPlaysNow** [comment]
Does someone know where I could get the patched version of spigot to fix this while it still occurs?

**Comment by maxencehenneron** [comment]
What’s wrong with jumping?

**Comment by Creeperface01** [comment]
I cannot jump at least on some servers

**Comment by tr7zw** [comment]
Yea I noticed that the onGround/y-position is not that correct, triggering some ac's.

**Comment by HoverEpic** [comment]
This issue is very interesting, but dupplicated with #164 , so i closed this one.
