### ISSUE TITLE
cannot jump

### ISSUE THREAD

**Issue by Creeperface01** [DragonetMC/DragonProxy#218]
After connect I simply cannot jump. And hand hit animation is slowed down (idk if this is known issue or not)

**Comment by DefinitlyEvil** [comment]
need to be confirmed, probably caused by the physics simulation?

**Comment by Creeperface01** [comment]
at least on play.gameteam.cz I cannot jump. simply nothing happens when I touch jump button but it seems like MCPE sends jump action

**Comment by HoverEpic** [comment]
I have no problem on localhost, i'll try on this server.

**Comment by HoverEpic** [comment]
#200 duplicated
