### ISSUE TITLE
Fail when compiling.

### ISSUE THREAD

**Issue by qwertyazerty** [DragonetMC/DragonProxy#22]
I tried to compile by following your tutoriel. This is not the first time I do that.
I did it on Ubuntu and Windows and get the same issue.
The logs ( Windows, same on Linux ).
[logs.txt](https://github.com/DragonetMC/DragonProxy/files/452838/logs.txt)

**Comment by iDerp** [comment]
The latest build, and quite a few before were failing. https://drone.io/github.com/DragonetMC/DragonProxy/latest

**Comment by TheDiamondYT1** [comment]
Yeah blame me i need someone to fix the maven build, or revert to before maven modules

@DefinitlyEvil @mastercoms @TekkitCommando @MrPowerGamerBR @MrGenga @TheMCPEGamer

**Comment by DaMatrix** [comment]
The problem is that protocol depends on proxy, and proxy depends on protocol.  Neither of them can be built.  Would it be a problem if I merged the two in a PR?

**Comment by TheDiamondYT1** [comment]
Okay
