### ISSUE TITLE
Issues with path and file finding...

### ISSUE THREAD

**Issue by TJPlaysNow** [DragonetMC/DragonProxy#227]
Soo, I remember it worked at one point in time, but something changed, I think it's that I moved the dp file.

When I change the original config and reload dragon proxy it doesn't create a new one, shown here:
![image](https://user-images.githubusercontent.com/17147463/35330409-0313a7b6-00c9-11e8-93ba-d532fcd4ee2a.png)

Then a dude gave me a newer build and I tested it with some errors, and nothing changed..
![image](https://user-images.githubusercontent.com/17147463/35330418-0a2cf93a-00c9-11e8-8703-f315e088cb58.png)

Now, the only real info I could give is the path it's under, I've tested it out under both:
"C:\Users\TJPlaysNow\Desktop\Central\Server\Dragon Proxy"
"C:\Users\TJPlaysNow\Desktop\Central\Server\DragonProxy"

Neither of those paths change anything, and the proxy just doesn't work without the config, so help would be great...

**Comment by DefinitlyEvil** [comment]
try not to put on the desktop and put in like `D:\DragonProxy` and without any spaces.

**Comment by HoverEpic** [comment]
Spaces in path is not supported.
