### ISSUE TITLE
Please add Offline Mode Support

### ISSUE THREAD

**Issue by bubundas17** [DragonetMC/DragonProxy#229]
Please Add Offline mode support for lan connections

**Comment by DefinitlyEvil** [comment]
This should be called, fix offline mode support.

**Comment by HoverEpic** [comment]
Is it like #231 ?

**Comment by HoverEpic** [comment]
It's an old issue, but i need more information about this, what's not working properly and how to test?

**Comment by HoverEpic** [comment]
Closing this for cleaning issues.
