### ISSUE TITLE
Create one website for chinese

### ISSUE THREAD

**Issue by hiouttime** [DragonetMC/DragonProxy#232]
I want to make a Chinese official website for chinese,and provide CDN services.Also provide a forum for communication in Chinese environment.Thanks!

**Comment by lukeeey** [comment]
Chinese is dumb.

**Comment by DefinitlyEvil** [comment]
@outtimes you can donate to us! :D but we don't plan to make an alternate website for now.

**Comment by lukeeey** [comment]
CDN services is possible though. What would we host anyway? Just the DragonProxy JARs?

**Comment by HoverEpic** [comment]
We already have a maven repo for that, so I think it's OK.
