### ISSUE TITLE
[Suggestion] [Good Idea] [Possible?] Inventory Server Selector!

### ISSUE THREAD

**Issue by Adrihun** [DragonetMC/DragonProxy#235]
Hi, thanks for clicking on my post.
I have checked out the 3 Main bedrock servers (Lifeboat, Mineplex, InPVP) All of them have special items which you can right click, and it will open an inventory for you that contain all of the **Minigames** they have.

And i was wondering if this could be made inside DragonProxy, maybe you could guys make a special config file that can have items added to it.

For **example:**
```

redstone item:
    inventory size: 5
    opened with: rightclick, leftclick
    items: button1

    button1:  
         Name: "SkyWars"
         Action: SEND Player "Bungee->SkyWars1"
    img1:
        src: imgur.com/example
```
I know this would be very difficult to do, but its still a good idea and I would like to hear your thoughts! :)

**Comment by lukeeey** [comment]
It's not that difficult

**Comment by lukeeey** [comment]
Anyway, i believe this can be done via the api when we actually get round to implementing it.

**Comment by DefinitlyEvil** [comment]
those are modal forms.
