### ISSUE TITLE
Please update to 1.2.10

### ISSUE THREAD

**Issue by PonyPC** [DragonetMC/DragonProxy#237]
Please update to 1.2.10

**Comment by thelex337** [comment]
I agree

**Comment by HoverEpic** [comment]
Im on it

**Comment by HoverEpic** [comment]
I have tried some hours to update and connect a client on DragonProxy unsuccessfully @DefinitlyEvil , can you take a look at this?

**Comment by HoverEpic** [comment]
Updated : https://github.com/DragonetMC/DragonProxy/releases/tag/0.3.4.3
