### ISSUE TITLE
Some red stone items can't work.

### ISSUE THREAD

**Issue by GarryLai** [DragonetMC/DragonProxy#239]
Some red stone items can't work.
For example: button, switch.

**Comment by HoverEpic** [comment]
What do you mean? you can't click or something? What version of DragonProxy?

**Comment by GarryLai** [comment]
0.3.4.2,Redstone item can't work when I clicked it.

**Comment by HoverEpic** [comment]
On my test server, redstone don't have the activate visual, but it's working.
Clicking on buttons, levers works. Can you describe more what is not working?

**Comment by Reflyansyah** [comment]
LoL redstone is't work !
