### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by RandomAltThingy** [DragonetMC/DragonProxy#24]
Holy crap this is epic! Can I get repo access?

**Comment by DefinitlyEvil** [comment]
Sure.

**Comment by RandomAltThingy** [comment]
Also, I get stuck at location server for the Dragonet Hypixel thing.

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy Use 0.13.1.

**Comment by RandomAltThingy** [comment]
I use 0.13.1....

**Comment by RandomAltThingy** [comment]
Nvm I'm in

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy Let me restart it really quick.

**Comment by RandomAltThingy** [comment]
I logged in it says connecting to Hypixel and I'm just floating there glitching...

**Comment by KangYui** [comment]
This software is not completed. Let's contrubing to improve this!

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy You have to wait until you get to the real spawn point of Hypixel, when logging in you are at (0,72,0).

**Comment by Creeperface01** [comment]
Awesome!

**Comment by RandomAltThingy** [comment]
Been waiting 5 mins in the glitching world

**Comment by RandomAltThingy** [comment]
@DefinitlyEvil Where is the code for the join msg

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy PCSpawnPositionPacketTranslator. I used MovePlayerPacket since JoinGamePacket is already sent when connecting and login.
