### ISSUE TITLE
[Request] UPnP Support + Server jar version

### ISSUE THREAD

**Issue by Roadhog360** [DragonetMC/DragonProxy#240]
My router doesn't correctly allow me to port forward, I rely on UPnP to get port forwarding. Please support this, so people like me are able to use this.

Another request could be a version that replaces a Spigot jar, so the server itself supports Bedrock.

**Comment by Adrihun** [comment]
Home servers are not secure & good. Why not just buy a dedi server for 20-40 USD a month, and you could host your server there

**Comment by ghost** [comment]
@Adrihun well some poeple dont have the money am home hosting and its secure

**Comment by sgdc3** [comment]
UPnP makes sense for common use applications, open your ports manually instead

**Comment by Roadhog360** [comment]
@Adrihun Would you like to pay for it, then?
@sgdc3 I can't. Read my post again.

**Comment by sgdc3** [comment]
> My router doesn't correctly allow me to port forward

Model?

**Comment by Roadhog360** [comment]
Dunno. It's just an AT&T router.

**Comment by HoverEpic** [comment]
We are not gonna implements UPnP, unless it's a worldwide requested feature.
And if you want ti replace Spigot by a full Bedrock server, take a look at Nukkit or PocketMine-MP.

**Comment by Roadhog360** [comment]
PocketMine or Nukkit is Bedrock software. This is not what I want. I want a Java server with Bedrock support built in.

**Comment by ghost** [comment]
@Roadhog360  you may look at protocolsupportpe

**Comment by ghost** [comment]
It works like a plugin

**Comment by HoverEpic** [comment]
Is ProtocolSupportPe working?

**Comment by ghost** [comment]
@HoverEpic yes its working
