### ISSUE TITLE
Fix CircleCI build

### ISSUE THREAD

**Issue by HoverEpic** [DragonetMC/DragonProxy#243]
Some errors appear on CircleCI, need to be fix.
https://circleci.com/gh/DragonetMC/DragonProxy

**Comment by lukeeey** [comment]
This error started happening after your project structure cleanup commit.

```
[ERROR] Failed to execute goal on project dragonproxy-protocol: Could not resolve dependencies for project org.dragonet.proxy:dragonproxy-protocol:jar:0.3.4.3-SNAPSHOT: Could not find artifact org.dragonet.proxy:dragonproxy-commons:jar:0.3.4.3-SNAPSHOT in maven-repo (https://raw.githubusercontent.com/JRakNet/MavenRepository/master) -> [Help 1]
```

https://circleci.com/gh/DragonetMC/DragonProxy/162

(Works on previous master build [159](https://circleci.com/gh/DragonetMC/DragonProxy/159))

**Comment by HoverEpic** [comment]
I know, I just created the issue to remember to fix that ^^

**Comment by HoverEpic** [comment]
I removed CircleCI, it tryes to build rtifacts offline mode, that's trhe problem.
Now we use https://ci.codemc.org/
