### ISSUE TITLE
Skin of other player is completely black

### ISSUE THREAD

**Issue by HoverEpic** [DragonetMC/DragonProxy#244]
![image](https://user-images.githubusercontent.com/3588249/36400286-4f3c109e-15d0-11e8-9708-29d6a22cd1c3.png)

**Comment by patricknasci** [comment]
Thank you, there is little left to fix the players in version 1.2.10

**Comment by patricknasci** [comment]
![screenshot_20180220-114833](https://user-images.githubusercontent.com/11508790/36430538-2242d816-1634-11e8-94ee-87afb49ebedb.png)

**Comment by HoverEpic** [comment]
Fixed in latest snapshot
