### ISSUE TITLE
Practically, it is working without errors

### ISSUE THREAD

**Issue by patricknasci** [DragonetMC/DragonProxy#246]
![captura de tela_2018-02-20_14-26-33](https://user-images.githubusercontent.com/11508790/36439018-5ecd157e-164a-11e8-8efd-3fcfc9117492.png)

- Using Snapshot[ #23](https://ci.codemc.org/view/DragonetMC/job/DragonProxy/23/)

- Bungeecord

- Spigot 1.8.8

-  Viaversion in Spigot

-  plugin dragonproxy-plugin-bungee-0.3.4.3-SNAPSHOT.jar in Bungeecord (optional)

- plugin dragonproxy-plugin-spigot-0.3.4.3-SNAPSHOT.jar in Servers Spigots (optional)

![screenshot_20180220-143827](https://user-images.githubusercontent.com/11508790/36439513-ecc1324c-164b-11e8-8de7-9cd260e90444.png)

## Bugs:
- When enter the pc version after the pocket minecraft is in the game
is giving skin black error #244 

![screenshot_20180220-145129](https://user-images.githubusercontent.com/11508790/36440077-926e0494-164d-11e8-92c9-9b5bdc6307e2.png)

- Teleport in long distance
**Not RENDER WORLD AND SHAKES PLAYER**

![screenshot_20180220-162955](https://user-images.githubusercontent.com/11508790/36448367-2b798a2e-1666-11e8-8c79-727b1ff2fc0e.png)

**Comment by HoverEpic** [comment]
Sound good, world load is the biggest problem now, I'll focus on that. Thanks for testing.

**Comment by HoverEpic** [comment]
Fixed in 62da0da7e5d19a0f50f33f871bc4d2507706c530 and 69e8859ac9c67e9bd30f79de28bb41e5c71f80f1
