### ISSUE TITLE
Invisible chests + Drops not disappearing

### ISSUE THREAD

**Issue by Wiiucoop** [DragonetMC/DragonProxy#247]
If you join a server, the chests will be invisible

<img width="960" alt="prototype - copy" src="https://user-images.githubusercontent.com/23005416/36462295-86a2fa1e-1690-11e8-8c08-a2fb11347ca4.png">

And drops aren't removed from the ground when picked up

<img width="960" alt="dropper" src="https://user-images.githubusercontent.com/23005416/36462318-b2293a22-1690-11e8-901a-11f50b67359f.png">

Tested on a 1.8.8 server with ViaVersion and using Snapshot #23

Plugins: 
<img width="573" alt="pls" src="https://user-images.githubusercontent.com/23005416/36462509-e148e31a-1691-11e8-82a8-e7d54d8b6f46.PNG">

**Comment by HoverEpic** [comment]
Chests display is working on a 1.12.2 server, i will not fix that =)
For drops, it's an entity management problem, i'm on it.

**Comment by HoverEpic** [comment]
Can you test with the latest snapshot?

**Comment by HoverEpic** [comment]
Fixed.
