### ISSUE TITLE
PE player can't see the others in Spigot Server

### ISSUE THREAD

**Issue by KatyushaScarlet** [DragonetMC/DragonProxy#249]
I fonud that PE player can't see the others in Spigot Server, but the java player can see the PE player.
Spigot Version: 1.12.2
PE Version: 1.2.10
DragonProxy Version: 0.3.4.3
Here are the screenshots:
![wu jy 2j7 pb136n d0b](https://user-images.githubusercontent.com/24467495/36538005-e0025cc6-180c-11e8-8c3f-cdbc3d000600.png)
![z ne1jeny uup e kof 5](https://user-images.githubusercontent.com/24467495/36538016-e756f5cc-180c-11e8-9aa6-c09b972ac5a6.png)
![c3xu322 qhaoy irk uyfn](https://user-images.githubusercontent.com/24467495/36538025-f0bdb7fe-180c-11e8-9b61-3ce46921dc5f.png)

**Comment by HoverEpic** [comment]
I'm on the problem.

**Comment by HoverEpic** [comment]
Fixed in latest snapshot
