### ISSUE TITLE
Server teleporting

### ISSUE THREAD

**Issue by adelando** [DragonetMC/DragonProxy#250]
Hello, 

I’ve tested the latest build for PE 1.2.10 and sipgot 1.12

I noticed tho that going through portals in a hub is very touchy, sometimes it works sometimes it doesn’t. Other times it will teleport to the server but not update on the screen/pe device.

**Comment by patricknasci** [comment]
A similar error when rendering the map #246

**Comment by HoverEpic** [comment]
I'ts a known problem, i'm currently rewriting the chunk engine.

**Comment by HoverEpic** [comment]
Should be fixed in 62da0da7e5d19a0f50f33f871bc4d2507706c530
