### ISSUE TITLE
Name with spaces

### ISSUE THREAD

**Issue by Wiiucoop** [DragonetMC/DragonProxy#255]
PE Players that have spaces in their names shoudn't be allowed to join

Even tho some of my plugins seem to support these names, some skript and essentials commands doesn't work for them.

NOTE: if you use an Auth plugin like LoginSecurity, these players will be autokicked upon joining the server which solves the issue

**Comment by lukeeey** [comment]
We can replace spaces with underscores

**Comment by DefinitlyEvil** [comment]
@lukeeey then for example, `A Username` and `A_Username`, will collide with each other.

**Comment by lukeeey** [comment]
Well it can be optional and with a notice in the config.
