### ISSUE TITLE
List of problems i've found

### ISSUE THREAD

**Issue by Wiiucoop** [DragonetMC/DragonProxy#258]
Inventories aren't really working, none of the modifications that the pe player makes to their inventory is saved server side.

Chests doesn't seem to work properly, probably due to the issue above.

Villager doesn't work

Holograms doesn't work

No crafting or Creative blocks

Enderdragon has bugged animation

PE Player struggles to move if there is a block on top of his head and he jumps, they also have problems going upstairs

Horses are shown in an incorrect y- coordinate, seems like they're flying,

Sponges dont work if placed on water by the pc player, causing fake water for the pe player, a side effect to this is that it has a very strange behaviour if the pe player tries to place any block in that fake water that shoudn't exist (demo video: https://youtu.be/XwhVTXEKZUg) Also, breaking activator and detector rails while holding a block sometimes cause the same behaviour.

Sometimes the pe player has a strange speed effect on joining due to loginsecurity (it may also be a skript "problem")  i never saw it happen without these plugins, but it also never happened to java players  with the plugins enabled.

Chunk loading still glithy but became way better with #36 snapshot.

Even tho at PE's screen they cannot ride minecarts when clicked on, on server-side they actually are riding the cart (demo video: https://youtu.be/E9_N_uIBqT0) same goes for boats.

Spawn eggs displays the default (white) texture for all mob spawn eggs, but they still function as intended

TNT Explosion doesn't correctly show destroyed blocks

Minecart variants (like tnt minecart) convert into default minecart texture for the PE player

Some blocks doesnt show instantly when placed to the PE player.

Fallingsand is invisible on MCPE, making plugins like Hide and Seek to not work properly
======================
extra notes

1. I didnt mention minor bugs like skin is always Steve

2. Elytras and Wither Boss seem to work as intended.

**Comment by lukeeey** [comment]
Thanks for this list

**Comment by HoverEpic** [comment]
thank you.
