### ISSUE TITLE
Config based online mode (interim step to gui based)

### ISSUE THREAD

**Issue by fredkilbourn** [DragonetMC/DragonProxy#259]
Would be nice if i could add static username -> username+password mappings in the config file to allow the specified users in my server to automatically authenticate against java server based on config file entries.  I imagine this might be easier and quicker to implement than a full gui implementation?

I know you must have a lot to work on now so I'm fine if this just gets tagged RFC and sits forever too.

**Comment by HoverEpic** [comment]
It's planed, wait for the CLS service. It's a remote system to link Xbox Live and Mojang accounts. It's coded, but I need to secure it a bit more before launching.

**Comment by HoverEpic** [comment]
Done in 47c59761bc890050dd4314c538927f8af6b93f50
