### ISSUE TITLE
Packets bug

### ISSUE THREAD

**Issue by Creeperface01** [DragonetMC/DragonProxy#26]
sometimes client doesn't recieve a packet (when i break a block in protected area, it doesn't appear sometimes)

**Comment by DefinitlyEvil** [comment]
It receives, just graphically block isn't updated. But we will figure this out. ;) Thanks or using. I am closing this issue.

**Comment by Creeperface01** [comment]
No i was breaking block in residence and after few attemps it didnt appear but anticheat kicked me out when i jump there

**Comment by RandomAltThingy** [comment]
Dude @DefinitlyEvil add a new server on port 19133 pointing to pvp.thearchon.net

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy Later. xD

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy Done!

**Comment by RandomAltThingy** [comment]
@DefinitlyEvil It works! Extremely slow and chunk loading gets stuck and I can't chat or run commands but it works!

**Comment by RandomAltThingy** [comment]
I showed FuzionDroid some pics of me on TheArchon using this software he seems amazed.

**Comment by RandomAltThingy** [comment]
We only receive chat when first joining the server but we don't receive any other chat and can't send it

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy Try the latest build.

**Comment by RandomAltThingy** [comment]
@DefinitlyEvil Update the test servers xD or give me credentials

**Comment by RandomAltThingy** [comment]
And the last build is by me

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy That's using RSA keys instead of passwords. 
And do not chat here, we have a forum.

**Comment by RandomAltThingy** [comment]
Lol kk

**Comment by RandomAltThingy** [comment]
@DefinitlyEvil Gitter.im/dragonetmc/dragonet
