### ISSUE TITLE
Redstone wiring & note blocks

### ISSUE THREAD

**Issue by emerysteele** [DragonetMC/DragonProxy#262]
I have some note blocks connected to a pressure plate & when activating the pressure plate, it doesn't play the note blocks & crashes dragon proxy.

**Comment by emerysteele** [comment]
Sorry, wasn't on latest snapshot. Note blocks do not play the right notes though.

**Comment by HoverEpic** [comment]
We never work on sounds, (or just a bit and never tested), so it's not implemented.
