### ISSUE TITLE
Half slab glitch

### ISSUE THREAD

**Issue by emerysteele** [DragonetMC/DragonProxy#263]
Walking up half slabs glitches the character position back & forth a few times before continuing normally.

**Comment by Jocke155** [comment]
This is the case for me too, and it does say something about it in the proxy console:
`[36;1m[02:21:51] [37;1m[INFO] Player position : -94.74130249023438, 67.5, 585.8519287109375 collide with BlockStairs on -95/69/585[37;1m[0m`

**Comment by lukeeey** [comment]
@DefinitelyEvil Disable colour in config 😂

**Comment by HoverEpic** [comment]
It's a work in progress, @ApocalypsjeNL will work on that soon.

**Comment by DefinitlyEvil** [comment]
@lukeeey wrong tag xD

**Comment by HoverEpic** [comment]
dupplicated #164 , closing
