### ISSUE TITLE
Error when executing "stop" command

### ISSUE THREAD

**Issue by BrainStone** [DragonetMC/DragonProxy#267]
When I use the `stop` command most of the time I get this exception:

```
[11:33:55] [INFO] Shutting down DragonProxy...
net.marfgamer.jraknet.RakNetException: sleep interrupted
at net.marfgamer.jraknet.server.RakNetServer.start(RakNetServer.java:823)
at net.marfgamer.jraknet.server.RakNetServer$1.run(RakNetServer.java:841)
net.marfgamer.jraknet.RakNetException: sleep interrupted
at net.marfgamer.jraknet.server.RakNetServer.start(RakNetServer.java:823)
at net.marfgamer.jraknet.server.RakNetServer$1.run(RakNetServer.java:841) 
```

(Using build 38)

**Comment by lukeeey** [comment]
@MarfGamer ?

**Comment by lukeeey** [comment]
Oh he changed his name. @Whirvis

**Comment by HoverEpic** [comment]
It's a known issue, and i think i will not fix that =)

**Comment by sgdc3** [comment]
@HoverEpic Maybe add it to the docs, just to help contributors

**Comment by whirvis** [comment]
I know this issue has been closed, but while I was looking at the stack trace I noticed the package is "net.marfgamer" rather than "com.whirvis", meaning you are on an outdated version. Please update to 2.9.1 to make sure you are using the latest version. On top of this, whenever you receive an error and think it might be related to JRakNet feel free to check the current version on the repo and/or make an issue if you are unsure of anything :)

**EDIT**: The issue seems to be coming from an uncaught sleep interrupted exception. If this persists on version 2.9.1, please let me know and I will release another version (2.9.2) to make it so the server ignores it when it's sleeps are uninterrupted as it is most likely coming from the ```Thread.sleep(0, 1);```. This line of code simply prevents the server loop from running so fast it eats up the CPU and has nothing related to timing that would keep the server from running correctly if one of it's sleeps got interrupted.

**Comment by DefinitlyEvil** [comment]
@HoverEpic ^

**Comment by lukeeey** [comment]
@Whirvis Sorry when i mentioned you i didnt realise

1) you changed your name
2) jraknet had been updated

Im very observent, arent i 😂

**Comment by HoverEpic** [comment]
i have updated Jraknet yesterday on a local branch, let me push this =)
(i was trying to remove the server max players, but seems the client not display the max players when the players count is > 1000)

**Comment by whirvis** [comment]
@HoverEpic If you want an ulimited amount of players, you can set the maximum connection count to -1 when creating the server :)

**Comment by HoverEpic** [comment]
i'll test thank you

**Comment by HoverEpic** [comment]
Should be ok, I haven't this error since update.

**Comment by whirvis** [comment]
Great to hear!

**Comment by HoverEpic** [comment]
Still happen ><
`stop
[13:05:58][INFOS] [Console] Executing command: stop 
[13:05:58][INFOS] Shutting down DragonProxy... 
com.whirvis.jraknet.RakNetException: sleep interrupted
	at com.whirvis.jraknet.server.RakNetServer.start(RakNetServer.java:824)
	at com.whirvis.jraknet.server.RakNetServer$1.run(RakNetServer.java:842)
com.whirvis.jraknet.RakNetException: sleep interrupted
	at com.whirvis.jraknet.server.RakNetServer.start(RakNetServer.java:824)
	at com.whirvis.jraknet.server.RakNetServer$1.run(RakNetServer.java:842)
[13:06:00][INFOS] Goodbye! `

The shutdown code is called : 
https://github.com/DragonetMC/DragonProxy/blob/master/proxy/src/main/java/org/dragonet/proxy/DragonProxy.java#L305
https://github.com/DragonetMC/DragonProxy/blob/master/proxy/src/main/java/org/dragonet/proxy/network/RaknetInterface.java#L158

I'm wondering if the `System.exit(0);` can be the problem.

**Comment by whirvis** [comment]
I think I might have finally fixed it, I will release version 2.9.2 as soon as possible which should fix the problem.

**Comment by whirvis** [comment]
Alright, I will release version 2.9.2 then. I have already committed and pushed the code to GitHub, however I am unable to build and release it at the moment. I will release version 2.9.2 as soon as I am able to.

**Comment by HoverEpic** [comment]
Much thanks, you are sure that the problem not came from our implementation?

**Comment by whirvis** [comment]
I have just released version 2.9.2! Now all there should be in the console is a warning saying that a sleep was interrupted rather than an exception that stops the entire process. Once again, if any more issues pop up let me know. I'm sorry bugs like this keep occurring :/

**Comment by lukeeey** [comment]
@Whirvis Can we hide the warning too? Or can JRakNet handle the System.exit()?

**Comment by whirvis** [comment]
The warning can't be hidden, however it shouldn't be of a nuisance (as it should only print it out once if the server or client is shutdown incorrectly). However, if it does get annoying I can remove it all together if you'd like. Just let me know if you would like it removed :)
