### ISSUE TITLE
Make drone.io actually give artifacts

### ISSUE THREAD

**Issue by DaMatrix** [DragonetMC/DragonProxy#27]
I think that drone isn't using the right commands.  According to [this](https://drone.io/github.com/DragonetMC/DragonProxy/83), it's running the command `mvn package -q -DskipTests=true` when it sould be using `mvn clean install`.  Running `mvn package -q -DskipTests=true` on a fresh clone produces no output whatsoever, as in here: [http://imgur.com/a/ScVCL](http://imgur.com/a/ScVCL). It just froze for a second and then stopped.  Can that be changed?

**Comment by DaMatrix** [comment]
Oh nvm, it just doesn't produce any output. `mvn package -q -DskipTests=true` DOES compile correctly.  The jars are put in `{clone_dir}/proxy/target` and are called `dragonproxy-0.0.6-preR1` (with budled deps) and `original-dragonproxy-0.0.6-preR1.jar` (without bundled deps).

**Comment by TheDiamondYT1** [comment]
We know
