### ISSUE TITLE
Still doesn't work when connecting to test server with Samsung Galaxy S4

### ISSUE THREAD

**Issue by RandomAltThingy** [DragonetMC/DragonProxy#27]
Title says it all. I login, then I just glitch there and nothing happens. It does say logging in.

**Comment by DefinitlyEvil** [comment]
hmmm let's test it out.

**Comment by ExtaSpace** [comment]
What MCPE version are you using? Do you use any custom launcher?

**Comment by TheMasterBlaster** [comment]
If it does not say anything on the server the Proxy is forwarding to its possible something is incorrectly configured, or the server the Proxy is forwarding to is not a 1.8 server. Hopefully this helps your issue @RandomAltThingy :)

**Comment by RandomAltThingy** [comment]
@DefinitlyEvil Check the configuration xD

**Comment by RandomAltThingy** [comment]
Locking

**Comment by RandomAltThingy** [comment]
I use BlockLauncher due to being able to join servers on 4g
