### ISSUE TITLE
Can't join server

### ISSUE THREAD

**Issue by SgtJalau** [DragonetMC/DragonProxy#275]
So basicly auth menu works but after typing everything it it just kicks me and says: " Failed to login. Please rejoin.". The log looks like this:
```
[16:55:11] [INFO] Saving console output disabled
[16:55:11] [WARNING] This is a development build. It may contain bugs. Do not use on production.
[16:55:11] [INFO] Starting up DragonProxy, version: 0.3.4.3-SNAPSHOT (d0cf942-dirty) ...
[16:55:11] [INFO] Supported version of Minecraft PC/Mac: 1.12.2
[16:55:11] [INFO] Supported version of Minecraft: Pocket/Windows 10 Edition: v1.2.10
[16:55:11] [INFO] Creating thread pool(Size:8)...
[16:55:11] [INFO] Binding on 0.0.0.0:19132 ...
[16:55:11] [INFO] The proxy has started!
Mär 02, 2018 4:55:23 PM com.fasterxml.jackson.databind.ext.Java7Support <clinit>
WARNUNG: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
Mär 02, 2018 4:55:23 PM org.dragonet.common.utilities.LoginChainDecoder decode
INFORMATION: The LoginPacket has been successfully verified for integrity
[16:55:11] [INFO] Player Jalau[/192.168.2.101:40194] connected!
[16:55:11] [INFO] Client Jalau[/192.168.2.101:40194] disconnected! Reason: Client disconnect
```

Server log shows nothing.

Using the latest original app version from the google play store. Trying to connect to my online mode bungee cord on play.mysticrunes.net (server is using 1.12.2 however protocol support is running (shouldn't change anything in this case though)).

Interesting thing is the java 7 thing. Do I really need to install a deprecated java version to get this working?

Could it be my gamer tag being the same as my pc version mc name?

**Comment by HoverEpic** [comment]
In online mode, gamer tag is replaced by mojang name. The jdk7 message is just a warning and not cause any problem.
You should use the latest snapshot, 0.3.4.4 !

**Comment by SgtJalau** [comment]
@HoverEpic Strange. The file name says 0.3.4.4 but when started it says 0.3.4.3? Found it here: https://github.com/DragonetMC/DragonProxy/releases/tag/0.3.4.4

**Comment by HoverEpic** [comment]
Snapshot repository
https://ci.codemc.org/view/DragonetMC/job/DragonProxy/

**Comment by SgtJalau** [comment]
Do I need a bungee plugin? Or is it only for API purposes?

**Comment by HoverEpic** [comment]
Bungee plugin is not working now

**Comment by SgtJalau** [comment]
@HoverEpic Got it working however there is nothing that I can really do. I am just floating in the void and the whole world is like "vibrating". No matter what server I join. On hypixel I can see a lot of players standing inside me though.

**Comment by HoverEpic** [comment]
Weird, works at my home ><

**Comment by SgtJalau** [comment]
@HoverEpic So it's probably something different. I will test around a bit. Both hypixel and mysticrunes or just hypixel?

**Comment by HoverEpic** [comment]
Tested with 4 / 5 servers, including hypixel.

**Comment by SgtJalau** [comment]
@HoverEpic Works for me now too. Strange. But only after teleport somewhere. Otherwise the world is not loading correctly. but I know this is a development build. Thanks for the great work and keep it up 👍

**Comment by HoverEpic** [comment]
Ok, yes the world loading is still under heavy development.
