### ISSUE TITLE
Bug Requests

### ISSUE THREAD

**Issue by Ghost-chu** [DragonetMC/DragonProxy#276]
1.Close door will let's door another to be stone_slab
2.When I disconnect,My character not disconnect on server.(Timed out
3.Can't walk on Stairs

**Comment by HoverEpic** [comment]
Doors are probably badly translated and need a special translator, i'll do that after chunk loading isser is resolved.
Can you give more informations about the timeout? Where is it apear (proxy/minecraft/client)? Can you give me a console log?
For stairs, it's wip, see #164

**Comment by Ghost-chu** [comment]
When Player disconnected,Player in server not disconnect in shortly time.
If you reconnect,Will kicked by Authme and say "Another same name player already in game."
This player must wait 15-30 secs to waiting old connectiom timed out,Then can reconnect to server.

**Comment by Ghost-chu** [comment]
When Player disconnected,Player in server not disconnect in shortly time.
If you reconnect,Will kicked by Authme and say "Another same name player already in game."
If want reconnect,This player must wait 15-30 secs to waiting old connectiom timed out.

**Comment by HoverEpic** [comment]
Weird, never had this issue on my testing spigot. I'll test this on my side.
