### ISSUE TITLE
dragonproxy-0.0.6-preR1 not starting

### ISSUE THREAD

**Issue by iDerp** [DragonetMC/DragonProxy#28]
After a successful build, the proxy doesn't want to start.
![img_3179](https://cloud.githubusercontent.com/assets/15174488/18296678/51e06038-7479-11e6-835b-f26e7cb601f0.PNG)

**Comment by marxst** [comment]
Exactly the same I have here. Build on Linux is successful, but running fails in the same place as in the screenshot above.
