### ISSUE TITLE
Barrier hitbox in survival

### ISSUE THREAD

**Issue by Wiiucoop** [DragonetMC/DragonProxy#280]
Barrier blocks has no hitbox in survival, which allows the player to break the block through it

**Comment by HoverEpic** [comment]
There is no barrier block in Bedrock edition, i can make a raytracing system to make sure player can't hit thought invisible block, but it will consume more resource. I'll try something when the chunk engine will be ok.

**Comment by Xayanix** [comment]
I think better solution is making barrier blocks seen as glass (as ProtocolSupport does).

**Comment by HoverEpic** [comment]
I'll do that, better idea.

**Comment by lukeeey** [comment]
Barrier blocks have been implemented in Bedrock 1.6.
