### ISSUE TITLE
Version shows as null in the log

### ISSUE THREAD

**Issue by BrainStone** [DragonetMC/DragonProxy#281]
The version when the proxy starts, shows as null:

```[09:00:16] [INFO] Starting up DragonProxy, version: null ... ```

**Comment by HoverEpic** [comment]
Yes, it's because the Jenkins snapshot build server execute the mvn package goal badly, and not fetch build data from github. I have to take a look at it.

**Comment by sgdc3** [comment]
@HoverEpic What's the correct task?

**Comment by HoverEpic** [comment]
I just do mvn package to fetch git data, on ci, it does this task with params, its probably does not trigger the pom plugin.

**Comment by HoverEpic** [comment]
Fixed with 2c4d065c59373c3fa24a68d6b5d032290dabd4d5
