### ISSUE TITLE
Potential IPv6 issue

### ISSUE THREAD

**Issue by fredkilbourn** [DragonetMC/DragonProxy#282]
My Minecraft server is on a DNS name that resolves to both IPv4 and IPv6.  When I use this hostname for DragonProxy, connections that happen to come through on IPv4 will connect properly to the server, connections that come through on IPv6 fail.  Both appear to be communicating just fine on port 19132 (similar packet counts and sized for both IPv4 and IPv6) so i don't know exactly how / where / why it is failing to connect in the end.

If you think this could be an issue with my environment or it isn't clear what this could be from the existing source, I'd be happy to provide tcpdumps of both IPv4 and IPv6 connections for review if that would help.

**Comment by HoverEpic** [comment]
I don't know if jraknet supports ipv6, I'll test on local development environment. I have no experience on ipv6 networking.
