### ISSUE TITLE
chest problem

### ISSUE THREAD

**Issue by chenxuuu** [DragonetMC/DragonProxy#286]
big chest (made up with tow chests) , can't open
it will be opened , but suddenly disappeared

**Comment by HoverEpic** [comment]
Can you test with latest snapshot?
https://ci.codemc.org/job/DragonetMC/job/DragonProxy/lastSuccessfulBuild/artifact/proxy/target/dragonproxy-0.3.4.5-SNAPSHOT.jar

**Comment by chenxuuu** [comment]
I tried but I can't connect to server , my client is 1.2.11
![qq 20180316225228](https://user-images.githubusercontent.com/10357394/37527329-c49fff58-296c-11e8-9416-d419aa3b64ec.png)

**Comment by HoverEpic** [comment]
We do not support edu édition, sorry.

**Comment by chenxuuu** [comment]
nonono, I'm using normal version,not edu
![qq 20180318113039](https://user-images.githubusercontent.com/10357394/37562297-d190c740-2a9f-11e8-9668-4e87433087e9.png)

**Comment by lukeeey** [comment]
@chenxuuu Why does it mention a school then? If you dont know why, i suggest you report it on http://bugs.mojang.com in the MCPE section if it hasnt been reported already
