### ISSUE TITLE
SOMETHING WRONG ?

### ISSUE THREAD

**Issue by Reflyansyah** [DragonetMC/DragonProxy#289]
I Say There's a Bug on the Effect Command!
That command does not work And there is something wrong with the command I mean I ask for the night vision effect given to {A} What is given instead The effect is not visible

Command BUG = {/ effect @a night_vision 255}

**Comment by refly2119** [comment]
I Say There's a Bug on the Effect Command!
That command does not work And there is something wrong with the command I mean I ask for the night vision effect given to {A} What is given instead The effect is not visible

Command BUG = {/ effect @a night_vision 255}

**Comment by HoverEpic** [comment]
Effects are totaly not working.
