### ISSUE TITLE
Player gets stuck in the ceiling

### ISSUE THREAD

**Issue by Hagb** [DragonetMC/DragonProxy#295]
I used the latest snapshot DragonProxy ( fb37021 ) and Minecraft Win10 1.2.11.
If I jump and touch the ceiling , I will "fly" at the sky near the ceiling and be hard to move ( just like being fixed) . 
I can't describe it better (I have tried my best). Sorry for my bad English.

**Comment by HoverEpic** [comment]
I'm aware of this and I haven't way to fix now. Thanks for reporting.
