### ISSUE TITLE
Port plugin for Sponge too

### ISSUE THREAD

**Issue by BrainStone** [DragonetMC/DragonProxy#298]
A plugin version for Sponge would be very handy!

**Comment by lukeeey** [comment]
Yes! I will try and move the plugins into their open repo first

**Comment by Aang23** [comment]
It's fairly easy to make that a plugin.

**Comment by sgdc3** [comment]
@lukeeey why? that doesn't have any advantage.

**Comment by lukeeey** [comment]
Build time and the plugin is seperate and not using the DragonProxy code base so why should it be here
