### ISSUE TITLE
Bugs in game ( dragonproxy-0.0.5.jar ) 

### ISSUE THREAD

**Issue by iMelsom** [DragonetMC/DragonProxy#3]
- [x] 1. At spawn I spawned under ground every time I logged in
- [ ] 2. There is a delay at player disconnect. This delay hinders a player loging back in until player disconnect is transmitted to recieving server
- [x] 3. I am unable to place or break any blocks
- [ ] 4. No animals/mobs where shown.

**Comment by TheDiamondYT1** [comment]
Can you make this a checklist?

**Comment by ethsmith** [comment]
^

**Comment by iMelsom** [comment]
Like that?

**Comment by ethsmith** [comment]
Yep

**Comment by MrPowerGamerBR** [comment]
Fixed 1 and 3 with 7cdd334eb7bd4ddd8402fdea3ea87d25cac98149
