### ISSUE TITLE
RIP DragonProxy

### ISSUE THREAD

**Issue by DaMatrix** [DragonetMC/DragonProxy#30]
...yeah.

**Comment by TheDiamondYT1** [comment]
:+1:

**Comment by DaMatrix** [comment]
lol

**Comment by Sceat** [comment]
lmao

**Comment by TheDiamondYT1** [comment]
It may be revived in the future

**Comment by Pet0203** [comment]
Wouldn't it be fixed by just undoing the maven modules? Also, this is open source so I suppose there is no problem with me using this code for my own server?

**Comment by ethsmith** [comment]
@Pet0203 yeah you can use it as long as there is credit to Dragonet team and any copyright headers aren't deleted.

**Comment by TheDiamondYT1** [comment]
Im probably going to restart it one day, properly.

**Comment by TheDiamondYT1** [comment]
And completely rewrite it

**Comment by Pet0203** [comment]
Or I'll make one from scratch for myself, more learning along the way and easier to understand.
