### ISSUE TITLE
Cannot join sub-servers.

### ISSUE THREAD

**Issue by ExtaSpace** [DragonetMC/DragonProxy#30]
When I join server, I'm at servers lobby. There are two ways of joining sub-servers - Opening the book, that server gives you, or just use /server [sub-server] . I can't open the book, but when I type for example /server skyblock, MCPE does nothing. I can move around lobby as I could before, but I'm disconnected. Console only shows, that I disconnected from the server. Any way of joining a sub-server?

**Comment by DefinitlyEvil** [comment]
Any error tracebacks?

**Comment by ExtaSpace** [comment]
Tracebacks...? I don't know, what does it mean, but I don't get any errors in console.

**Comment by ExtaSpace** [comment]
I can run DragonProxy, join the server again, and attach log file in here, but I don't think it will help, because there are no errors.

**Comment by ExtaSpace** [comment]
Also, it happens even on newest build.

**Comment by Creeperface01** [comment]
Or backtrace it is list of methods called before error

**Comment by RandomAltThingy** [comment]
Commands do not work.

**Comment by ExtaSpace** [comment]
Then why it disconnects me from server?

**Comment by RandomAltThingy** [comment]
Most likely anti cheat kicking you.

**Comment by jython234** [comment]
What works?

**Comment by RandomAltThingy** [comment]
@jython234 Hey dude :)

We could maybe use a bit of help.

**Comment by RandomAltThingy** [comment]
There is an issue here somewhere with a LONG list of bugs

**Comment by jython234** [comment]
You guys need a gitter chat. Any networking issues?

**Comment by RandomAltThingy** [comment]
@jython234 Gitter.im/DragonetMC/dragonet

**Comment by DefinitlyEvil** [comment]
@jython234 A lot of issues. xD

**Comment by RandomAltThingy** [comment]
@jython234 #17

**Comment by Creeperface01** [comment]
i have similar issue i stack in air when server send me to another server

**Comment by DefinitlyEvil** [comment]
This feature is not damn implemented lol, check out the code, there are loads of `//TODO`s. 
Dupl with #98
