### ISSUE TITLE
installing

### ISSUE THREAD

**Issue by XoticRealmsOwnerandDev** [DragonetMC/DragonProxy#301]
can someone explain in detail how to install this on windows 10 pc

**Comment by lukeeey** [comment]
Do you have Java installed?

**Comment by XoticRealmsOwnerandDev** [comment]
yes i do

**Comment by lukeeey** [comment]
You will need to run a Spigot server as well. There's plenty of tutorial online for that.

Download the latest build of DragonProxy from [here](https://ci.codemc.org/job/DragonetMC/job/DragonProxy/lastSuccessfulBuild/artifact/proxy/target/dragonproxy-0.3.4.5-SNAPSHOT.jar) (direct download)

Then copy it to an empty directory and in then hold SHIFT and right click on the file explorer background. Click "Open command window here".

Next, type `java -jar dragonproxy-0.3.4.5-SNAPSHOT.jar`

**Comment by XoticRealmsOwnerandDev** [comment]
@lukeeey would it matter if i buy a server from a host or would i have to do it on my pc

**Comment by lukeeey** [comment]
You can do it from either. DragonProxy is not ready for production but it works well enough for messing around.

**Join the test server:** &nbsp;&nbsp;   demo.dragonet.org

You can join from either PE 1.2.10 or PC 1.12.2 :)

**Comment by XoticRealmsOwnerandDev** [comment]
ok thanks
