### ISSUE TITLE
World error after teleport

### ISSUE THREAD

**Issue by Misat11** [DragonetMC/DragonProxy#304]
After teleport from spawn (or any position) I can't see world and I can't move.

On Spawn:
![onspawn](https://user-images.githubusercontent.com/20199703/37840794-505085c6-2ebe-11e8-9be0-2c96a962b94e.png)

After teleport:
![afterteleport](https://user-images.githubusercontent.com/20199703/37840807-5adbae58-2ebe-11e8-8d36-4dff86b284e2.png)

**Comment by lukeeey** [comment]
Known bug

**Comment by Misat11** [comment]
BE has 2 packets for it MoveEntity and MovePlayer, but PC send EntityTeleport (I didn't find any else packet). Dragon translator use MoveEntity for both Entity and Player (https://github.com/DragonetMC/DragonProxy/blob/master/proxy/src/main/java/org/dragonet/proxy/network/translator/pc/PCEntityTeleportPacketTranslator.java). Maybe this is a problem. So I suggest to send MovePlayer packet, maybe with mode RESET or TELEPORT.

**Comment by Misat11** [comment]
or in MoveEntity set boolean TELEPORTED to true, in all translators is not set

**Comment by DefinitlyEvil** [comment]
no @Misat11 , DragonProxy caches entities so it knows whether the target is a player entity or not.

**Comment by Misat11** [comment]
I SOLVE IT: Every you need is: send empty chunk (I add it to my pull request), but new problem is broken blocks (sometimes chunks) after teleports (if you in debug mode, these blocks are logged into console, this is in my pull request)

**Comment by Misat11** [comment]
ok, after maybe 15 teleports is broken, long distances are problems and teleport to blocks too

**Comment by Misat11** [comment]
After teleport:
![image](https://user-images.githubusercontent.com/20199703/38254830-8166556a-375a-11e8-8801-f37d38e12e20.png)
You can see chunk, that isn't here 😄
