### ISSUE TITLE
Jump unsynced with the remote server

### ISSUE THREAD

**Issue by TheGameratorT** [DragonetMC/DragonProxy#306]
If you jump on cubecraft you get teleported back.

**Comment by lukeeey** [comment]
I'm guessing that's their anticheat lol. Can you share a video?

**Comment by TheGameratorT** [comment]
Sorry, but I can only use the computer again tomorrow, sorry.

**Comment by CtrlAltCuteness** [comment]
If the anti-cheat does not get a packet about the player jumping, it will do that.
