### ISSUE TITLE
Client crashed after joining Hypixel (Help needed)

### ISSUE THREAD

**Issue by DefinitlyEvil** [DragonetMC/DragonProxy#31]
Client crashed after joining Hypixel. 
Help needed! :(

**Comment by RandomAltThingy** [comment]
Change the test server to pvp.thearchon.net please

**Comment by RandomAltThingy** [comment]
@DefinitlyEvil

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy Why?

**Comment by RandomAltThingy** [comment]
So we can see if that works and I like that server

**Comment by DefinitlyEvil** [comment]
Hmm, I am gonna make a separate one on another port.

**Comment by RandomAltThingy** [comment]
What port?

**Comment by Castar** [comment]
I has a same problem on lpopvm.cloudapp.net.

2015-12-29 20:50 GMT+09:00 Luke <notifications@github.com>:

**Comment by DefinitlyEvil** [comment]
@Castar I need to know what exactly caused this so I can try to fix it.

**Comment by TheMasterBlaster** [comment]
I tried on my Phone (Samsung Galaxy S4) as well as on BlueStacks and Windows 10 Edition and I could not get any of them to crash.

**Comment by DefinitlyEvil** [comment]
@TheMasterBlaster Weird. xD Have u tried Hypixel?

**Comment by TheMasterBlaster** [comment]
That is what I did my tests on yes.

**Comment by DefinitlyEvil** [comment]
@TheMasterBlaster That's weird, why did mine crashed and so did @Castar 's? xD

**Comment by TheMasterBlaster** [comment]
@DefinitlyEvil I honestly don't know, I could get each client to correctly join with little to no issue (besides the delay on loading chunks).

**Comment by DefinitlyEvil** [comment]
@TheMasterBlaster Okay.

**Comment by RandomAltThingy** [comment]
I can now join Hypixel. However I could before. It joins and loads the closest entity to you and the chunks have forever to load. I can't receive or send chat either.

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy You couldn't or you could?

**Comment by RandomAltThingy** [comment]
Couldnt

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy Lol you scared me, I thought my new commits broke the program.

**Comment by TheDiamondYT1** [comment]
Fixed awhile ago. Closed.
