### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by redmusic27** [DragonetMC/DragonProxy#311]
Hello sir, I'm a graphic designer and I would love to contribute to your project with a logo. This is completely free, take it as a contribution. In case you agree I would be presenting sketches and you will be choosing/modifying the aspects you like more so we could work on the perfect logo for your project together.

Let me know what do you think? best regards :)

**Comment by lukeeey** [comment]
Sure :)

**Comment by redmusic27** [comment]
Okay sir. I will start to make a logo for you. if it is ready I will be back.

**Comment by redmusic27** [comment]
Hello sir, I have created a concept logo for you. If you like it, I'll send you files and pr.
is there anything you want ?

Horizontal
![dragon-proxy- horizontal](https://user-images.githubusercontent.com/37577374/38551798-546aa20c-3ce4-11e8-9b63-95796b28823e.jpg)
Vertical
![dragon-proxy- vertical](https://user-images.githubusercontent.com/37577374/38551800-54a3df0e-3ce4-11e8-8bb4-c894a05eb994.jpg)

**Comment by sgdc3** [comment]
Very nice, i like it :+1:

**Comment by ethsmith** [comment]
I like Horizontal. Looks nice

**Comment by HoverEpic** [comment]
OMG, it's amasing, and perfect, thank you !!!
Is it possible to have a simple D, icon like for social networks?

**Comment by redmusic27** [comment]
I will add all the data. including icons and other necessary things if this logo is okay and will be used sir @HoverEpic

**Comment by whirvis** [comment]
These logos look very nice, would love to approve them but I do not have permission to do so. You have my vote though 👍
