### ISSUE TITLE
can you create an example server?

### ISSUE THREAD

**Issue by LewBr** [DragonetMC/DragonProxy#312]
Hello, can you do that?

**Comment by LewBr** [comment]
for every player test that

**Comment by lukeeey** [comment]
ptero.dragonet.org 
port 19132 (if on bedrock)
or port 25565 (if on java)

**Comment by LewBr** [comment]
nice, but have called "big" server running that proxy? if so, write this on README all servers running DragonProxy, included yours of test and can you update that server to 1.2.13?
