### ISSUE TITLE
Can't login to online server. 0.3.4.5-snapshot

### ISSUE THREAD

**Issue by codergreen** [DragonetMC/DragonProxy#316]
Steps I take:
Run dragonproxy
Change config to point to the server I want to go to.
Restart dragonproxy
Start Minecraft PE 1.2.10
Login to Xbox live
Connect to the ip of my dragonproxy server
Login menu pops up
Type in my Minecraft java edition email and password
Login fails and tells me to rejoin.

The server log says my Xbox live account logged in successfully but no mention of my java edition name. Any advice on how to fix this?

**Comment by codergreen** [comment]
Decided to turn on debug log, so I could see if anything is there. Is something wrong happening here?


26.04 21:28:45 [Server] INFO [21:28:45][INFO ] Client VacantRaptor100[/107.242.116.66:58345] disconnected! Reason: Client disconnect 
26.04 21:28:45 [Server] INFO [21:28:45][INFO ] CLIENT DISCONNECT 
26.04 21:28:45 [Server] INFO at java.lang.Thread.run(Thread.java:748)
26.04 21:28:45 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
26.04 21:28:45 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
26.04 21:28:45 [Server] INFO at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
26.04 21:28:45 [Server] INFO at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
26.04 21:28:45 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266)
26.04 21:28:45 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
26.04 21:28:45 [Server] INFO at org.dragonet.proxy.network.UpstreamSession.lambda$authenticate$0(UpstreamSession.java:285)
26.04 21:28:45 [Server] INFO at com.github.steveice10.mc.protocol.MinecraftProtocol.<init>(MinecraftProtocol.java:192)
26.04 21:28:45 [Server] INFO at com.github.steveice10.mc.auth.service.AuthenticationService.login(AuthenticationService.java:218)
26.04 21:28:45 [Server] INFO at com.github.steveice10.mc.auth.service.AuthenticationService.loginWithPassword(AuthenticationService.java:302)
26.04 21:28:45 [Server] INFO at com.github.steveice10.mc.auth.util.HTTP.makeRequest(HTTP.java:79)
26.04 21:28:45 [Server] INFO com.github.steveice10.mc.auth.exception.request.InvalidCredentialsException: Invalid credentials. Invalid username or password.

**Comment by ApocalypsjeNL** [comment]
You are trying to login with an invalid combination of username and/or password of your Minecraft java edition account

**Comment by codergreen** [comment]
I'll double check by logging into my pc account, but I used the exact same email and password. I doubt I would have punched it all in wrong 10+ times. I'll tell you how it goes when I try on my pc

**Comment by codergreen** [comment]
Just logged in on pc and mojang.com and they both worked. I'm still  getting invalid credentials exception every time I try to sign in using dragonproxy. It also doesn't matter what server, they all seem to fail with this error.

In case these details matter, I'm using Minecraft host called Aquatic for hosting. My phone is an s5, and I paid for mcpe but had to download an apk in order to get the right version (1.2.10)

**Comment by codergreen** [comment]
Is it OK if I share my server name to help debug? I kinda want to nail down if it's my phone, the apk, or the server. I figure if it fails for you, it's the server. If it works, then it's my phone or apk. Or you could share an apk that you know works. Hopefully something to figure this out.

**Comment by brandonholland** [comment]
If I host my own java dedicated server do my kids have to have a java account as well to use the proxy?  I've already paid for their bedrock accounts and my own bedrock/java account.

**Comment by ApocalypsjeNL** [comment]
Could be that your host is "blacklisted" by mojang, or something else is also making login requests to their servers

**Comment by codergreen** [comment]
I don't think the server is blacklisted by Mojang, otherwise I couldn't run a proper online spigot server that works, right? Unless you are saying I can receive creditial, but not log in.

What's the second part? If something else is doing login requests, wouldn't it still work? I've run two java edition minecraft clients from the same pc before in onine mode. I don't think this would be different.

I tried connecting to ptero.dragonet.org , your server, the banner comes up but when I start connecting it gets stuck at locating server. I don't even get a chance to enter my java info.

Sorry for all the trouble, I'm just wondering what the problem could be.

**Comment by ApocalypsjeNL** [comment]
I read something today, are you running dragonproxy on a OVH server?

**Comment by codergreen** [comment]
I'm using https://aquatis.host/ I don't think it's an OVH reseller, as it charges less than OVH. I'll look into that a bit more to double check.

**Comment by ApocalypsjeNL** [comment]
I'm asking that because I came across this yesterday, maybe that's the case for youhttps://www.reddit.com/r/Minecraft/comments/7ngdpi/psa_mojang_is_blanket_banning_ovh_ips_to_login_to/

**Comment by codergreen** [comment]
Looks like they did it to digitalocean too. I'm guessing they might do it to all vps and vpn? I'll look into it more. If my plan doesn't work, you can close this. But give me time to try one last trick.

**Comment by codergreen** [comment]
Tried a few proxy servers, managed to get a new error with one of them. Something about not being able to authenticate with mojang's server. I dont know if that's one step forward or back. If it's a step forward, then it's safe to say mine craft is blocking my vps, thinking I'm using it as a vpn.

I guess if I keep looking deeper, I may find a sock proxy that works. If there are no objections, I think we can close this issue.

**Comment by ghost** [comment]
I have same problem too.

Bungeecord's online mode is Enable

local Dragonproxy → remote Bungeecord (SUCCESSED)  (using/without VPN)
local Dragonproxy → local server (SUCCESSED)

(Dragonproxy & bungeecord in the same host)
remote dragonproxy → remote bungeecord (FAILED) (using/without VPN)

I success log in my Minecraft account in remote server (without VPN), but Dragonproxy still login fails and tells me to rejoin.

update:
when I join remote server and disconnect, the local Dragonproxy  could not be log in success.

**Comment by HoverEpic** [comment]
@FlanNep is your DragonProxy server hosted in a data center? If true, online mode will not work, Mojang has blacklisted these IPs, the Mojang login API refuse the connection.

You should use the Bungeecord auth bridge (can be found in [plugin/bungee](https://github.com/DragonetMC/DragonProxy/tree/master/plugin/bungee)) witch allow joining both Mojang online mode and XboxLive accounts on bungeecord with no UUID collision.

If you have issues setup this, please join our Discord to ask some help.

**Comment by timriker** [comment]
I'm using "online" from Azure and it appears to be working.

**Comment by HoverEpic** [comment]
Thanks for the tip, but i guess it will be blocked soon, Mojang do not allow servers to login on their APIs, only personal computers (unless they allow it from Microsoft servers).

**Comment by ghost** [comment]
@HoverEpic No, neither DragonProxy nor Bungeecord/Spigot  is in data center

update:
18.06.12 I change the PROXY_TYPES to SOCKS and restart , it says login success, but throws some ERROR messages , Bungeecode doesn't have any message , I'm very sure Bungeecord is running and port is correct.

[12:18:01][信息   ] Player ****[/***.***.***.***:52257] logged in via Min
ecraft account.
[12:18:02][信息   ] DisconnectedEvent io.netty.channel.AbstractChannel$Annotated
ConnectException: Connection refused: no further information: /127.0.0.1:25565 i
o.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: n
o further information: /127.0.0.1:25565
[12:21:03][信息   ] Session exception: Session timeout
com.whirvis.jraknet.session.TimeoutException: Session timeout
        at com.whirvis.jraknet.session.RakNetSession.update(RakNetSession.java:8
69)
        at com.whirvis.jraknet.server.RakNetServer.start(RakNetServer.java:822)
        at com.whirvis.jraknet.server.RakNetServer$1.run(RakNetServer.java:856)

**Comment by HoverEpic** [comment]
I don't understand, you are using proxy option in the config file? (Authentication proxy details, for expert user) Warning : it's not a VPN, it's a proxy.
This option is for http proxying the auth/connect request, if you don't know how to setup this, you should let it to default !

The only things you have to configure are remote_server_addr and port.

**Comment by ghost** [comment]
@HoverEpic  Yes, I'm using Shadowsocks (a socks5 proxy) and I set DragonProxy config to the socks5 proxy. 
but a few minute ago I set proxy_type to NONE , it login success . Perhaps just my network unstable.
The remote_server_addr is 127.0.0.1 (bungeecord is in the same host) , when I  change it to external IP , the problem solved. 
In my local PC , the 127.0.0.1 is available . but in the remote server , 127.0.0.1 will throw no further information exception  . My PC is Windows 10, the remote server is Windows server 2012 (in VM).

**Comment by HoverEpic** [comment]
I just have few questions, same vm or different VMs ? (but i guess you know how to use VM networks)
Have you unlocked the 127.0.0.1 minecraft firewall rule (idk if set on your system) ?
It's probably a network problem (config or unstability).
