### ISSUE TITLE
NewToDragonetProxy first impressions this is broken

### ISSUE THREAD

**Issue by brandonholland** [DragonetMC/DragonProxy#317]
My 6 year old will not play this until MOST IMPORTANTLY:
1: Auto jump is NOT working
I confirmed it's not working in my windows 10 app or her phone after setting it to enabled.

Secondly and truly more importantly i thought it said creative inventory isn't supported but:
2: I can't craft THE VERY FIRST ITEM I would need to begin crafting in a survival world: a crafting table(?)  Is it just me?  Is there something I've done wrong?  Crafting support is a requirement before leaving ALPHA in my opinion?!?!?

3: When I attempted to transfer my inventory I had collected but couldn't use to my java counterpart, my items DISAPPEARED!

4: No animations (I know this is already stated elsewhere) - breaking a block, hitting a monster is pretty confusing for my child as well and getting stuck in a tree multiple times.  These are first impressions after just 5 minutes of time in there.

**Comment by gatewaytofredom** [comment]
Please open up a separate ticket for each individual issue. It makes handling issues easier.

**Comment by Aang23** [comment]
This project is a very complex one, they already spent a lot of time on it, and even stop working on it during some months ! 
This is something very hard to do, so, yes, survival is currently broken, but the simple fact that you can see a Java Edition Map on a bedrock client is already something very impressing...
And note that the latest build is not stable, it is clearly said "Do not use on production", "Alpha release".
So, if you really want a more stable version, build it from the source code, or simply wait for those known issues to be fixed.

**Comment by brandonholland** [comment]
Fungie2134 I did but my build appeared to be the same as the latest snapshot.  I would be interested in delving in to the weeds on this I wonder if I could contribute.  Bedrock needs a dedicated server.  When it's just me and my kids I'd like to be able to keep most stuff private.  One thing I didn't like was having to spend way too much time getting them set up in xbox live for a private server.

**Comment by HoverEpic** [comment]
Hi @brandonholland, thank you for testing DragonProxy.
I know there are a lot of non working things, specially crafting, it can't be done until inventories transactions are not fully working, and it's two different systems on two different engines. It will probably takes months to implements it.
If you have some server setup skills, i recommend you to setup an open source bedrock server like PocketMine, Nukkit or Minet (idk there devel states).
You can also rent a Realm, but it costs a bit.
If you want to support us, you can follow the development and speak with the team on our Discord server.
And thank you @gatewaytofredom @Fungie2134 for your responses, i'm happy to have a such community \o/ !
