### ISSUE TITLE
If/when you continue this project, focus on the PE bit

### ISSUE THREAD

**Issue by yangm97** [DragonetMC/DragonProxy#32]
Considering you can choose the client version on the java easily and iOS/Win10 versions won't let you downgrade the client, I think it's more important to make the PE side updated with the latest version.

**Comment by DefinitlyEvil** [comment]
yes and I think you're right.

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil HES ALIVE!! *dab*

**Comment by TheDiamondYT1** [comment]
If its continues make a new repo with new code

**Comment by ethsmith** [comment]
There's been 2 or 3 new repos.

**Comment by MrPowerGamerBR** [comment]
@TheDiamondYT1 you already created a new DragonProxy repo before... and you deleted it.

Welp, without @DefinitlyEvil DragonProxy simply won't move forward in development.

**Comment by DefinitlyEvil** [comment]
@MrPowerGamerBR true :(

**Comment by TheDiamondYT1** [comment]
True

**Comment by TheDiamondYT1** [comment]
Apparently we have permission to use networking code from https://github.com/voxelwind/voxelwind which is updated for 0.16 already

**Comment by TheDiamondYT1** [comment]
Its none of that nukkit bs

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil Are you free to work on it now

**Comment by DefinitlyEvil** [comment]
@TheDiamondYT1 Yes I got some time now it's 0.16 already wtf!!??

**Comment by DefinitlyEvil** [comment]
@TheDiamondYT1 Yes I got some time now and it's 0.16 already wtf!!??

**Comment by MrPowerGamerBR** [comment]
@DefinitlyEvil and soon it will be 1.0 ;)

**Comment by DefinitlyEvil** [comment]
@MrPowerGamerBR Hopefully there's won't be 0.17 lol! xD And this project will BECOME ALIVE again!!

**Comment by inxomnyaa** [comment]
0.17 beta is already out. http://pocketbeta.minecraft.net/2016/11/10-beta-changelog-build-1-aka-01701.html

**Comment by DefinitlyEvil** [comment]
@thebigsmileXD Wow it shocked me when I saw so many ppl still concentrating on this almost-dead project. :octocat:

**Comment by inxomnyaa** [comment]
Well, it is/was the only great working proxy "plugin"

**Comment by DefinitlyEvil** [comment]
@thebigsmileXD hopefully ;P

**Comment by Lord-Felidae** [comment]
I believe this project can LIVE!!! I really love combining two versions together, and I want to do it more. Why did you shut this down in the first place?

**Comment by Lord-Felidae** [comment]
In fact, ima search the code for bugs now XD

**Comment by DefinitlyEvil** [comment]
@CubeFromSpace Nah, the whole s**t is broken now, I haven't updated packet structures yet.

**Comment by Lord-Felidae** [comment]
Ok... :(... ... ... ...

**Comment by Creeperface01** [comment]
Yes this project is awesome!

**Comment by TheDiamondYT1** [comment]
Comment `+1` if you want this project to be COMPLETELY recoded and in another repo (No more repo changes after that). We wont be using the bad Nukkit raklib btw.

**Comment by MrPowerGamerBR** [comment]
I'm the only one that is interested in the PE -> PC proxy instead of the PE -> PE proxy? Yes? Okay then...

**Comment by Pet0203** [comment]
Nah, I want PE -> PC too

**Comment by DefinitlyEvil** [comment]
@Pet0203 Did u mean PE -> PE? Currently there is no BungeeCord-like thing for PE. xD

**Comment by Pet0203** [comment]
@DefinitlyEvil No, I did mean PE-> PC, tho making a new repo is just a waste of time, for now.

**Comment by inxomnyaa** [comment]
I am one of the PE<->PE guys. My voice counts for 5 persons okay? xD *talks for 55 people*

**Comment by MrPowerGamerBR** [comment]
@DefinitlyEvil of course it does exist, Nemisys is a PE server proxy.

**Comment by inxomnyaa** [comment]
@MrPowerGamerBR actually Nemisys is a complete core, isn't it? You couldn't run, for example, PMMP connected via Nemisys, or do you
Correct me if i am wrong, thx :)

**Comment by DefinitlyEvil** [comment]
@thebigsmileXD Oops maybe I am just an outdated guy in the area of MCPE. xD

**Comment by MrPowerGamerBR** [comment]
@thebigsmileXD I think you can connect Nemisys to a PM-MP server as long the PM-MP server uses Synapse, however I'm not sure because I never done that before.

(I thought you would know that because you are one of the developers of ClearSky... I know that because <sup>you banned</sup> <sup><sup>me from the</sup></sup> <sup><sup><sup>ClearSky repo</sup></sup></sup>)

**Comment by Lord-Felidae** [comment]
Maybe you could just make the necessary edits and add the new software to update it to PE 16.0 -> PC 10.2
