### ISSUE TITLE
Question about Plugin API

### ISSUE THREAD

**Issue by Weffle** [DragonetMC/DragonProxy#321]
What plugins can I use?

Bungee or Spigot plugins?

If neither, can you guys make it so the proxy uses spigot plugins?

Thank you for reading! :)

**Comment by lukeeey** [comment]
Running spigot plugins would defeat the entire point of the proxy

**Comment by ethsmith** [comment]
What he is saying is, you install spigot plugins on your server and the proxy is only for connections to the server.
