### ISSUE TITLE
Animals in the air

### ISSUE THREAD

**Issue by tendwong** [DragonetMC/DragonProxy#325]
My horses are all 1 block above ground. If the horse climbs over a step, he hovers 1 block above the step as well.

Bedrock version: 1.4
Minecraft Server : Spygot 1.12.2

**Comment by HoverEpic** [comment]
I think the problem is rounding numbers : in PC and PE some positions are stored differently in packets (Double vs Float), i was aware of this.

**Comment by tendwong** [comment]
Can this be solved? Seems like an obvious bug to me.
