### ISSUE TITLE
Support for mixed-mode authentication

### ISSUE THREAD

**Issue by k-jiang** [DragonetMC/DragonProxy#326]
Some BungeeCord/Bukkit plugins like [FastLogin](https://www.spigotmc.org/resources/fastlogin.14153/)([GitHub repo](https://github.com/games647/FastLogin)) allow both Premium and Offline players join the server. They ensure premium players can join a server with mojang UUID and skip third-party login like AuthMe while Offline players are forced to use their [AuthMe](https://www.spigotmc.org/resources/authmereloaded.6269/) password to authenticate.

We have FastLogin install across Bungeecords and would like to allow Offline players joining our server as well as Premium players. Could this feature be possibly done with DragonProxy?

Please consider the feature. You have done great jobs on the project. Thank you all for the effort!

**Comment by HoverEpic** [comment]
I think this can be done with DragonProxy core plugins (it have a non documented plugin API).

We natively provide strict auth modes (online, offline and hybrid), and we'll not add other auth mode.

If i understand well, you want to allow logged in and not Xbox players, non logged in will be asked password likes java players?

**Comment by lukeeey** [comment]
I dont actually like the idea of the plugin api anymore lol. Its whats stopped me contributing anything

**Comment by k-jiang** [comment]
> If i understand well, you want to allow logged in and not Xbox players, non logged in will be asked password likes java players?

Yes. Basically I would like to have `online` and `offline` modes enabled at the same time. And premium (logged in) player could join in the server with premium uuid.
