### ISSUE TITLE
Missing metrics opt-out option

### ISSUE THREAD

**Issue by k-jiang** [DragonetMC/DragonProxy#337]
"metrics" is forced enabled every time I restart DragonProxy. The "enable=false" option is useless.

Ppl choose to turn this off for a good security reason. If it is not changed back or explained, we will consider to switch to some other solutions for the security.

**Comment by lukeeey** [comment]
Don't threaten us. This software is still in development and parts of it are being rewritten to be more stable. We have full rights to force metrics on in this development process, and when we make a *proper* release then we will allow it to be toggled.

It's possible it could've been a code error and someone forgot to check if its disabled in the config.

**Comment by k-jiang** [comment]
Then you have to properly inform people about the situation, explaining why you have to force enable metrics at this moment and what information you collect so you can better improve the project. Doing sneaky business could only harm your reputation.

Furthermore, we, as server operators, have to put security to our top priority. If anything could potentially be harmful to our service or infrastructures, we have to do everything we could to prevent it, which includes cooperating with partners (like you), or in the worst case, switch. So may you please understand that it is not a "threat" or leverage, we are being responsible to our players and equipments.

**Comment by lukeeey** [comment]
Metrics source: https://github.com/DragonetMC/DragonProxy/blob/master/proxy/src/main/java/org/bstats/Metrics.java

bStats page: https://bstats.org/plugin/server-implementation/dragonproxy

**Comment by sgdc3** [comment]
Calm down, we simply forgot to add such option.

**Comment by HoverEpic** [comment]
It's probably an error, i wasn't aware of this, thanks for reporting.
