### ISSUE TITLE
Add skins?

### ISSUE THREAD

**Issue by Pomdre** [DragonetMC/DragonProxy#344]
add skins to players?

**Comment by HoverEpic** [comment]
Skin are wip.
Java -> Pocket should be easily coded
Pocket -> Java is not possible (but ok with a modded java client)

**Comment by Lord-Felidae** [comment]
What does this mean?

Which side doesn’t display skins?

**Comment by x9nico** [comment]
@Shiny-andKittens on Bedrock Edition, it is not showing the skins of Players whose playing on Java Edition. It sets them as Steve.

**Comment by akxks** [comment]
DragonProxy is currently being remade, and probably in the future versions, this issue will be fixed. If you want, you can work on it yourself by making a fork and compiling with Maven.
