### ISSUE TITLE
Player's move speed is weird

### ISSUE THREAD

**Issue by StarWishsama** [DragonetMC/DragonProxy#351]
Issue: When player joined the server, Player's speed looks weird so player will be kicked 100%.
Java Edition: 1.12.2
DragonProxy Edition:  0.3.4.5-SNAPSHOT (98f4578)
Bedrock Edition: 1.2.10
Some logs:
[2018-07-19 12:32:09][INFO ] Spawning StarWish_Sama in world 0 at -2.2540200780233013/121.72000000625849/100.47699416439843 
[2018-07-19 12:32:09][INFO ] Unknown effect ID: 15

**Comment by lukeeey** [comment]
DP supports 1.4.0

**Comment by x9nico** [comment]
Download the latest version => https://ci.codemc.org/job/DragonetMC/job/DragonProxy/lastSuccessfulBuild/artifact/proxy/target/dragonproxy-0.3.4.6-SNAPSHOT.jar
