### ISSUE TITLE
crafting, enderchests and beds dont work, stairs have odd behavour

### ISSUE THREAD

**Issue by EzioisAwesome56** [DragonetMC/DragonProxy#354]
so im using the lasted snapshot build for my test server, and i cant craft things, cant open ender chests, and beds dont appear to let you sleep

stairs also act weird, if i try to climb them i get pushed off and if i jump onto them i start floating above them

**Comment by HoverEpic** [comment]
Thanks for the report. We are aware of these non implemented features.
