### ISSUE TITLE
Can't place any blocks

### ISSUE THREAD

**Issue by Zxilly** [DragonetMC/DragonProxy#355]
i'm using Spigot 1.12.2 and it works,but ic can't place any blocks no matter what mode i switch to.
#348

**Comment by Theyka** [comment]
Place blocks like in java edition and do not do it quickly

**Comment by Mio-sha512** [comment]
i cant place any blocks on any server at all

**Comment by Zxilly** [comment]
i try to change some code and now i can place the blocks properly,however,when i try to expand the blocks of the same type,only the first block of this type will be shown.
I read the guide,it said this is a known bug, i will try to solve it by myself lol
