### ISSUE TITLE
Java process multiplies over and over

### ISSUE THREAD

**Issue by TheMasterBlaster** [DragonetMC/DragonProxy#356]
I'm unsure what or why its happening but as of the updates on Aug 3, 2018, Iv found after starting DragonProxy my CPU is maxed out from 10 to 15 Java processes that either cannot be ended by Task Manager or just starts again after being ended. Closing DragonProxy does not fix this issue. The only way i can find to correct this is to do a restart of my PC. The Proxy does start but it does overload my PC, I never had issues with this before today.

[Update]
When starting DragonProxy "JavaSE Runtime Enviroment 8 Update 181" prompts for access to make changes to the device, allowing this causes the Java process issue but denying it stops this.

**Comment by SupremeMortal** [comment]
Are you using the latest build by any chance? This may be to do with the powershell elevation to fix local loopback by @Whirvis.

**Comment by TheMasterBlaster** [comment]
I am, as i said above "as of the updates on Aug 3, 2018" but it could cause issues for people that dont catch the issue in time or that have a low end PC.

**Comment by whirvis** [comment]
I'll look into this, they may very well be a JRakNet glitch.

**Comment by whirvis** [comment]
@TheMasterBlaster I just made an update where the broken code is no longer executed, I suggest you update to this one for now and when I can get this feature fully working on DragonNet I will let you know and add it back :)

Keep in mind if you need the loopback exemption you will have to do it manually like normal. Sorry about this :/

**Comment by whirvis** [comment]
Just saw this issue that has been fixed but was still marked open so I closed it :)
