### ISSUE TITLE
Anti cheat kicks you so you can't chat or receive chat or interact with the server.

### ISSUE THREAD

**Issue by RandomAltThingy** [DragonetMC/DragonProxy#36]
Join the test server (Its TheArchon PC server)

**IP:** hypixel.dragonet.org
**PORT:** 19133

Login with your email and pass then it will show The Archon join message and you will not receive any chat (Except some occasions when 1 message will show every few minutes).

**Comment by TheMasterBlaster** [comment]
I have only had this issue from time to time when using this server. My own tests do not have this issue, it's possible those servers have a formal of anti cheat plug in and is kicking you which could be the cause of not being able to send or receive chat

**Comment by RandomAltThingy** [comment]
Do we have a fix?

**Comment by RandomAltThingy** [comment]
This would be critical then if we are getting kicked when joining..

**Comment by RandomAltThingy** [comment]
TheMasterBlaster can you port forward yours or use hamachi or something so I can join?

**Comment by TheMasterBlaster** [comment]
If an anti cheat plugin is the cause the only way to fix it would be to correct the packet sending, Most likely any good anti cheat plugin would think the proxy is trying to use some type of packet glitch of some sort and thus kicks you and since Dragon proxy is not the best and sending the disconnect packet you would never know you got kicked and would still remain on the proxy but not said server.

**Comment by TheMasterBlaster** [comment]
I have a full test server not home hosted. Once I get home I could get you the Ip

**Comment by RandomAltThingy** [comment]
Kk

**Comment by RandomAltThingy** [comment]
@DefinitlyEvil Does the test servers update automatically with successful builds?

**Comment by RandomAltThingy** [comment]
Also, we need to covert PC colour codes (§ and &) to PE so we can show colour in chat

**Comment by RandomAltThingy** [comment]
@TheMasterBlaster Got the IP yet?

**Comment by TheMasterBlaster** [comment]
Still at work

**Comment by RandomAltThingy** [comment]
:/

**Comment by RandomAltThingy** [comment]
@DefinitlyEvil How many sub-domains can you have for dragonet.org, and do they cost money?

**Comment by RandomAltThingy** [comment]
@DefiniyEvil Is it possible I could get the details so I can start/stop the server? And update the jar etc

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy Subdomains won't cost me money. ;) 
I will often updates it so don't worry about that.

**Comment by RandomAltThingy** [comment]
Yes but when I'm testing I need to use the test server I fucked up my pc and deleted Windows by accident

**Comment by RandomAltThingy** [comment]
BTW I advertised on spounge and here.  http://www.thearchon.net/hub/threads/new-software-join-pc-servers-on-mcpe.64749/

**Comment by DefinitlyEvil** [comment]
Thx.

**Comment by RandomAltThingy** [comment]
@TheMasterBlaster IP?

**Comment by TheMasterBlaster** [comment]
@RandomAltThingy IP:76.72.160.22 Port:25864

**Comment by RandomAltThingy** [comment]
@TheMasterBlaster offline

**Comment by RandomAltThingy** [comment]
Nvm

**Comment by RandomAltThingy** [comment]
@TheMasterBlaster I KEEP CRASHING!

**Comment by TheMasterBlaster** [comment]
@RandomAltThingy It started doing this after I updated DragonProxy. The one I just had worked fine.

**Comment by RandomAltThingy** [comment]
@TheMasterBlaster Please revert ASAP. It looks cool and I wish I could join.

**Comment by TheMasterBlaster** [comment]
@RandomAltThingy I dont know what is going on... It legit was just working o-o

**Comment by TheMasterBlaster** [comment]
@RandomAltThingy  Join Its working

**Comment by TheMasterBlaster** [comment]
Anyone? o.o

**Comment by TheMasterBlaster** [comment]
@RandomAltThingy  @DefinitlyEvil The Issue seems to be caused when a server uses a custom name for their map besides the default generated name. A simple map rename fixed my issue allowing players to correctly join and play.

**Comment by RandomAltThingy** [comment]
Check Skype @TheMasterBlaster

**Comment by RandomAltThingy** [comment]
@Jython234 Can you tweet

#DragonProxy is legit, it needs PC account to login to the server"

Or something like that. I'm nearly at fucking breaking point with people like TruDan tweeting its fake I mean wtf you've seen the code you know this aint fake.

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy That's a kind of advertising, ignore them. And everyone has haters.

**Comment by TheMasterBlaster** [comment]
Anything that asks for your MC Info gets attacked for trying to steal your info xD

**Comment by DefinitlyEvil** [comment]
@TheMasterBlaster What do you mean?

**Comment by TheMasterBlaster** [comment]
@DefinitlyEvil When people see a Program or Mod or anything asking you to type in login info they automatically think it's trying to steal your login credentials when something like Dragon proxy doesn't do that.

**Comment by DefinitlyEvil** [comment]
@TheMasterBlaster Hmmm, that's normal thought. We should show them the code. lol

**Comment by TheMasterBlaster** [comment]
@DefinitlyEvil Not going to lie... I used a dummy account when I first tried DragonProxy xD

**Comment by DefinitlyEvil** [comment]
@TheMasterBlaster Hmm, and?

**Comment by TheMasterBlaster** [comment]
@DefinitlyEvil Just goes to show you people are extremely skeptical xD

**Comment by DefinitlyEvil** [comment]
@TheMasterBlaster We have to prove that we are legit somehow. ;P

**Comment by TheMasterBlaster** [comment]
@DefinitlyEvil Just keep your work for good and not evil and people will slowly figure it out :3

**Comment by DefinitlyEvil** [comment]
@TheMasterBlaster Lol, true.

**Comment by TheMasterBlaster** [comment]
@DefinitlyEvil any idea when creative users will build a break blocks? Or when we can attack people and mobs at all?

**Comment by TheMasterBlaster** [comment]
@DefinitlyEvil also I found out why people having issues joining random servers. Or I think so at least. As a server is running a custom named map besides the default one. It will cause the client to crash on logging in

**Comment by DefinitlyEvil** [comment]
@TheMasterBlaster That will take time, lett's do that later.

**Comment by DefinitlyEvil** [comment]
@TheMasterBlaster Why crash?

**Comment by TheMasterBlaster** [comment]
@DefinitlyEvil I am unsure why. If I knew Java I would try to figure it out. Best and I suggest for now is to put somewhere on the readme file to keep the world name the default one until we have the time to get to fix it.

**Comment by RandomAltThingy** [comment]
@DefinitlyEvil @TheMasterBlaster Join IRC channel #Dragonet on irc.freenode.net

**Comment by RandomAltThingy** [comment]
Cmon guys get on the IRC its easier to chat

**Comment by TheMasterBlaster** [comment]
Site loaded nothing but white

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy @TheMasterBlaster I prefer Gitter.

**Comment by RandomAltThingy** [comment]
@TheMasterBlaster Lol you know what IRC is? You can use web one or an IRC client like hex chat. I recommend you get it. For now, I will give you the website link.

**Comment by RandomAltThingy** [comment]
https://webchat.freenode.net

**Comment by RandomAltThingy** [comment]
@DefinitlyEvil Gitter is harder to use on mobile and IRC is just better and faster xD

**Comment by RandomAltThingy** [comment]
Well I creates the channel #dragonet so lets use jt

**Comment by RandomAltThingy** [comment]
@DefinitlyEvil We're on IRC waiting for you

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy Can't load the page.

**Comment by RandomAltThingy** [comment]
You guys need to learn what and IRC client is. Anyway, here is web chat.

webchat.freenode.net

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy I knew what is it and plz not chat here on issues.

**Comment by RandomAltThingy** [comment]
Well download an IRC client master blaster can connect fine.

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy Later. xD

**Comment by RandomAltThingy** [comment]
@DefiniflyEvil Dude new IRC.   http://webchat.esper.net/?nick=&channels=dragonet

**Comment by RandomAltThingy** [comment]
@DefinitlyEvil Any chance of getting owner? Also we have a sponge community.leader interested in our project, on our IRC. I would like to invite them.

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy Okay, that's cool. Joining...

**Comment by RandomAltThingy** [comment]
@DefinitlyEvil Replace the 19133 port with mineplex instead of TheArchon.

**Comment by jython234** [comment]
It seems you guys have lots of debugging to do. It would be easier if we
had a standard IRC or gitter chat that stays open.

**Comment by RandomAltThingy** [comment]
@jython234 #Dragonet on esper its 24/7

**Comment by jython234** [comment]
Why not freenode?

**Comment by RandomAltThingy** [comment]
@jython234 It was but some people didn't like it they said esper it for more Minecraft stuff just join esper

**Comment by RandomAltThingy** [comment]
We could ask the MineChat developer to help us
