### ISSUE TITLE
Remove modules from DragonProxy

### ISSUE THREAD

**Issue by DaMatrix** [DragonetMC/DragonProxy#36]
I haven't been able to build DragonProxy since the modules update, and it only seems to make the whole thing more complicated for potential new developers. Is there a reason that it's needed and if not, could it be reverted?

**Comment by MrPowerGamerBR** [comment]
I can compile DragonProxy without any issues, but I also think that adding a module system was unnecessary.

**Comment by DaMatrix** [comment]
[Here's](https://hastebin.com/sogibihete.scala) the output of `mvn package` in a fresh clone of the refactor branch.

**Comment by TheDiamondYT1** [comment]
Im sure the modules were reverted.

**Comment by DaMatrix** [comment]
https://github.com/DragonetMC/DragonProxy/blob/refactor/pom.xml#L24

**Comment by TheDiamondYT1** [comment]
Well change it then, i cant rn.

**Comment by DaMatrix** [comment]
I've tried, I still get flooded with errors. Nukkit needs to be in the build path for it to compile, lombok refuses to work correctly... :/

**Comment by robotman3000** [comment]
Actually, in my fork I am using maven modules. Any git repository that is a maven project can be cloned as a git submodule and used as a maven module. This is how I am getting JRakNet to be used as a dependency

**Comment by robotman3000** [comment]
Except possibly for lombok (I haven't tested this) I am able to build the project just fine, again this is currently in my fork. I plan to submit a pull request to merge my fork with the refactor branch soon. After that I will most likely begin pushing directly to the refactor branch instead of my fork

**Comment by DaMatrix** [comment]
Huh, I'm able to build your fork fine as soon as I move the translators out. Very confused now :/

**Comment by robotman3000** [comment]
Oh, yes. It builds just fine once you remove the translators. Currently they are completely broken

**Comment by robotman3000** [comment]
@TheDiamondYT1 Considering that in my fork I am using maven modules, should this issue be closed or should I change something?

**Comment by DefinitlyEvil** [comment]
@robotman3000 I guess this issue can be closed since your fork structure is just fine(tho I dun like Git submodules but they are better than split maven modules) . xD

**Comment by robotman3000** [comment]
Ok then, I shall close the issue.
