### ISSUE TITLE
Can't Connect to Server at All

### ISSUE THREAD

**Issue by Etrainquandt17** [DragonetMC/DragonProxy#364]
Shockbyte server hosting has everything set up correctly so everything has to be installed correctly. I tried messing with all of the settings. I had no luck. On the server list (both java and bedrock) the sever looks like it's just taking a while to ping but after all the waiting it just says cannot connect to server. I am confused to what I am doing wrong. I looked at all the issues and no one else seems to be having my problem. Any help would be appreciated.

**Comment by DefinitlyEvil** [comment]
Please try to contact them to get help, we are unable to help you from here.

**Comment by TheMasterBlaster** [comment]
I tried doing the same thing with that host, they never was able to get my DragonProxy server working.

**Comment by Etrainquandt17** [comment]
I got connecting to the server both through bedrock and java working but when I login to my java account and press the submit button it kicks me and tells me to log in again. I tried the same exact email and password when logging into my java account through the website and I successfully logged in.

**Comment by Etrainquandt17** [comment]
Changing both servers to offline mode makes me able to connect to the server but it's pointless because when I login to bedrock while my java one is one it says I logged on from another location. That doesn't make sense because 1. it's an offline server. 2. Any username can be used on an offline server.

Edit: I'm an idiot I was logging in with my alt account with the same username as my xbox account.

**Comment by HoverEpic** [comment]
Mojang blocked authentication from famous data centers, and Shockbyte seems blocked.
Hosting a classic Minecraft server works well, but DragonProxy doesn't works.
