### ISSUE TITLE
Update for 1.6.0 :)

### ISSUE THREAD

**Issue by Erkam246** [DragonetMC/DragonProxy#366]

**Comment by MisterSheeple** [comment]
When is this coming?

**Comment by blubbll** [comment]
> When is this coming?

when it's ready :)

**Comment by Endode** [comment]
When will it be ready?

**Comment by blubbll** [comment]
It'll be ready when it's ready. I'm not sure if we can help the authors, but patience is a start. It'll eventually come when it's done.
The past versions have all been implented after some time, this might be too.
I guess that is all information that's available as of now.

**Comment by MisterSheeple** [comment]
Ok it's been a while... any updates on how progress is going, @SupremeMortal?

**Comment by ru-ni** [comment]
blink once for soon, blink twice for soon:tm:

**Comment by MisterSheeple** [comment]
Ok it's been a month. What's going on?

**Comment by MisterSheeple** [comment]
Also, is the 1.6 branch stable yet? I need to use it

**Comment by MisterSheeple** [comment]
Wait never mind. Just saw @SupremeMortal's PR for it that was made yesterday.

**Comment by sgdc3** [comment]
@HoverEpic could you take a quick look at this? :)

**Comment by ApocalypsjeNL** [comment]
845686a74ff2eedcebced162393e5fc3abd069c3
