### ISSUE TITLE
[Reminder] Forums Anti Spam

### ISSUE THREAD

**Issue by TekkitCommando** [DragonetMC/DragonProxy#37]
I should remind you that I setup the forums but it has no anti spam/anti bot capabilities and so if there are any spam bots you must ban then via the members page of the forums then go to http://esotalk.org/forum/conversations/+plugins+skins+languages and find an anti bot Addon :)

**Comment by TekkitCommando** [comment]
There is a successor to the forum software we use but it is not ready yet. I will change the forums when the successor is ready.

**Comment by RandomAltThingy** [comment]
What is it

**Comment by RandomAltThingy** [comment]
Can I get access?

**Comment by TekkitCommando** [comment]
DefinitlyEvil can give you access if he wants, all he's got to do is login with the main account and add you guys as administrators.

**Comment by TekkitCommando** [comment]
Actually DefinitlyEvil is switching forum softwares, so it will be a little more secure.

**Comment by mastercoms** [comment]
http://flarum.org/ is the successor, btw.

**Comment by RandomAltThingy** [comment]
That softwares epic I was gonna use it once.

BTW @mastercoms join #Dragonet on irc.freenode.net

**Comment by TekkitCommando** [comment]
Correct

**Comment by mastercoms** [comment]
Well I can't, I'm too busy trying to help with the Valve ARG.

**Comment by RandomAltThingy** [comment]
What if I could get us non cracked XenForo? :)

I just remembered I have a connection I can get it from.

**Comment by TekkitCommando** [comment]
Then be my guest xD
