### ISSUE TITLE
1.13.1 and latest Bedrock support?

### ISSUE THREAD

**Issue by k9lego** [DragonetMC/DragonProxy#372]
Any word on the latest updates? Do you have any tentative timeline for updating for Spigot?

**Comment by JDJGInc** [comment]
I am going to say just use a snapshot of the software:

https://ci.codemc.org/job/DragonetMC/job/DragonProxy/lastSuccessfulBuild/artifact/proxy/target/


There use that for now, until the official one comes out.

**Comment by Xayanix** [comment]
It's not working too. Connecting takes ages and nothing happens.

**Comment by whirvis** [comment]
Please refer to issue #374
