### ISSUE TITLE
Developer TODO List

### ISSUE THREAD

**Issue by RandomAltThingy** [DragonetMC/DragonProxy#38]
- [x] Chat colours
- [ ] Fix the problem where we are supposedly getting kicked by Spigot
- [ ] Fix Respawn packet so we can hit the Respawn button (Urgent)

Please add more if you find things we need to do

**Comment by TheMasterBlaster** [comment]
@RandomAltThingy The Respawn button does work unless your client just thinks its been killed (which honestly happens alot) if the server says you died you can click the respawn button.

**Comment by RandomAltThingy** [comment]
@DefinitlyEvil When connecting with online mode disabled (No auth) it works great but with online mode enabled (With auth) we start to have connection problems and crashes and bugs.

**Comment by RandomAltThingy** [comment]
How would you find out if a player was put into spectator? Since it doesn't exist in mcpe, we would need to create our own spectator mode (siiimple)

**Comment by jython234** [comment]
You guys need to figure out if you are actually getting kicked. Print out to the console when connection is closed and also print out network traffic.

**Comment by MrPowerGamerBR** [comment]
Chat colors is added in this Pull Request: #55
