### ISSUE TITLE
Minecraft crashes when joining dragonproxy server.

### ISSUE THREAD

**Issue by EOT3000** [DragonetMC/DragonProxy#385]
I tried joining with 1.6 because the server said that mcpe 1.6 is supported. Then the game crashed. When I tried joining with 1.8, it said cannot join world. In the console: 
[15:10:34][INFO ] Client null[/192.168.1.47:42930] disconnected! Reason: Client disconnect[0m
[15:13:27][INFO ] Client null[/192.168.1.47:42930] disconnected! Reason: Client disconnect[0m
[15:23:25][INFO ] Client null[/192.168.1.47:42930] disconnected! Reason: Client disconnect[0m
[15:24:58][INFO ] Client null[/192.168.1.47:42930] disconnected! Reason: Client disconnect[0m

**Comment by MisterSheeple** [comment]
DragonProxy in its current state does not work at all. The devs have abandoned the project and development is unlikely to continue, so unfortunately, this is the end for now.

**Comment by raku-cat** [comment]
Last commit 6 days ago = abandoned? Lol

**Comment by akxks** [comment]
DragonProxy is currently being remade. Do not worry, although, this might take some time. If you look at my profile, you can see I'm trying to make the latest DragonProxy work with latest bedrock edition by changing the protocol number. Although, I have not made it work yet. There are some issues. Just be patient :)

**Comment by Beaness** [comment]
> DragonProxy is currently being remade. Do not worry, although, this might take some time. If you look at my profile, you can see I'm trying to make the latest DragonProxy work with latest bedrock edition by changing the protocol number. Although, I have not made it work yet. There are some issues. Just be patient :)

I dont think its that easy by just changing protocol version.

**Comment by akxks** [comment]
I know, but it's a start to getting it updated
