### ISSUE TITLE
The proxies crashed

### ISSUE THREAD

**Issue by kasuganosoras** [DragonetMC/DragonProxy#386]
| Name | Value |
| ------ | ------ |
| Server | CentOS 7.5-1804 x86_64 |
| Java | OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode) |
| DragonProxy | Version 0.3.4.6 |
| Minecraft Server | Akarin-1.12.2 |

I just run the proxy use the command
````
java -Xmx2048M -Xms128M -jar dragonproxy-0.3.4.6-SNAPSHOT.jar
````
Then it use a lot of system resource (CPU, Memory).

![img](https://i.natfrp.org/9d83e7fc62673356328c721a29ac6aa8.png)

And it crashed because `OutOfMemory`

![img](https://i.natfrp.org/a7a4f1fcf4a9bd557a2f8d6aa1bcc8c3.png)

**Comment by MisterSheeple** [comment]
That means that you allocated more RAM than you actually have or the server just ran out of RAM, which it shouldn't for 2 GB, so it's more likely the first one.

**Comment by MisterSheeple** [comment]
Besides, DragonProxy doesn't even work in its current state, and it was undergoing a rewrite, but I guess the developers abandoned it because the only thing updating the rewrite is bots just bumping some dependencies.
