### ISSUE TITLE
UUID Minecraft Windows10/Java

### ISSUE THREAD

**Issue by TheCalypso** [DragonetMC/DragonProxy#390]
Hello,
I ask myself a few questions about your proxy. If I understand correctly the windows10 client connects to the DragonProxy then connects to the BungeeCord. I would like to know if uids are managed by your system? Given that my database and my bans plugins only work with that I would like to know if this is compatible? Can you tell me how this is treated? 
For information, I have a server Minecraft Java Edition and I would like to ensure that the sender can join him. I'm also wondering what to put in the config.yml file at # Server Authentication Modes.

Thank you very much it is in any case a great project !

**Comment by Aang23** [comment]
I think that this is working like cracked version, with a random UUIDs per user. (I think)
For premium accounts the real one will be used. (For sure)

That depends on your server setup.

**Comment by ApocalypsjeNL** [comment]
It's exactly what @Aang23 says. If the proxy is set up as normal mode (premium mc accounts) the real uuid's will be used and the normal authentication flow will be used. When the proxy is in offline mode there will be a random uuid generated (like the cracked mc clients) and the offline authentication flow is used (so the client will not be able to join online-mode servers)

**Comment by SuperMarioSF** [comment]
Sorry for off topic, but my mailbox just blown to sky high when you closed so many issues at once. I am just watching this project for update and didn't expect this happend.

**Comment by lukeeey** [comment]
@SuperMarioSF Sorry but we had to close the issues as we had so many and the project is being rewritten so the issues dont apply

**Comment by SuperMarioSF** [comment]
Well, that is not a big deal for me, but maybe for someone else...

btw, be lucky with this write, you guys did amazing job to connect both versions.
