### ISSUE TITLE
Can you add pc 1.13.2 support?

### ISSUE THREAD

**Issue by rainchi** [DragonetMC/DragonProxy#394]

**Comment by meletisf** [comment]
Have you tried it with PC 1.13.2?

**Comment by MisterSheeple** [comment]
The developers are rewriting it so it will work with 1.13.2. Please be patient.

**Comment by tunip3** [comment]
any update on this?

**Comment by ondrejvajdak** [comment]
@tunip3 
![](https://i.imgur.com/oeXHoV4.png)

**Comment by Creeperface01** [comment]
🤔🤔

**Comment by Drison64** [comment]
@Creeperface01 🙃🙃
