### ISSUE TITLE
AAC goes Crazy When A Player Join in by DProxy

### ISSUE THREAD

**Issue by WeirdCoding123** [DragonetMC/DragonProxy#398]
AAC 3.6.4 PL (Latest)
BungeeCord Server
when a player join in,aac will go crazy. such as stuck the player with a high move detection VL
sometimes AAC occur errors directly :(

**Comment by MisterSheeple** [comment]
Please elaborate what AAC means.

**Comment by Erkam246** [comment]
I think AntiCheat

**Comment by WeirdCoding123** [comment]
AdvancedAntiCheat ：（

**Comment by Bluscream** [comment]
Well, the packets arriving at the MC server should be the same as if it was a PC client but the timing might be different (consider that you have an additional hop [the proxy] + all the processing the proxy does to each command) So if the AntiCheat is highly depending on timings you're most likely f*cked

**Comment by MisterSheeple** [comment]
I don't think this can be fixed because development of DragonProxy has not been continued for a long time, so don't count on a bugfix anytime soon.

**Comment by ApocalypsjeNL** [comment]
It has always been an advise to disable any anti cheat on your server when using DragonProxy, because this is heavily interfering with each other due to the way DragonProxy (and the Bedrock clients) are sending packets to the Java server
