### ISSUE TITLE
Anything going on for 1.9.0? 

### ISSUE THREAD

**Issue by person4268** [DragonetMC/DragonProxy#408]
I just downloaded the latest release and ran it, and when I use it on Bedrock 1.9.0, it hangs on loading resources. Are there any goals to get this working on 1.9.0? This is a really cool project, and would suck if it wasn't maintained anymore. 

Edit: In the meantime, does anyone know about anything that does the same thing as this? I'm hosting a server and want to bridge bedrock and java edition, and can't find anything besides this.

**Comment by DefinitlyEvil** [comment]
it will take years to complete this project, there are alternatives for native servers e.g. ProtocolSupportPE.

**Comment by EOT3000** [comment]
Years? With the protocol libraries we use, it'll be sooner

**Comment by alexchandel** [comment]
Why years?  Can't any of the protocol knowledge from [ProtocolSupport PE](https://github.com/ProtocolSupport/ProtocolSupport/pull/972), [MiNET](https://github.com/NiclasOlofsson/MiNET/wiki), and [PocketMine-MP](https://github.com/pmmp/PocketMine-MP) be applied here?

**Comment by EOT3000** [comment]
no, we use nukkit

**Comment by person4268** [comment]
I would like to have a way to bridge Java and mobile players together, and Nukkit only appears to be a server for mobile players.

**Comment by EOT3000** [comment]
the protocol knowledge is nukkit

**Comment by SupremeMortal** [comment]
@alexchandel I have made a library for Bedrock Edition which means we don't have to spend time implementing the entire protocol into DragonProxy.
https://github.com/NukkitX/Protocol
