### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ghost** [DragonetMC/DragonProxy#41]
No translator found for : org.spacehq.mc.protocol.packet.ingame.server.entity.ServerEntityPositionPacket[37;1m[0m
[36;1m[13:37:03] [33;1m[WARNING] [PC to PE] No translator found for : org.spacehq.mc.protocol.packet.ingame.server.entity.ServerEntityHeadLookPacket[37;1m[0m
[36;1m[13:37:03] [33;1m[WARNING] [PC to PE] No translator found for : org.spacehq.mc.protocol.packet.ingame.server.entity.ServerEntityVelocityPacket[37;1m[0m
[36;1m[13:37:03] [33;1m[WARNING] [PC to PE] No translator found for : org.spacehq.mc.protocol.packet.ingame.server.entity.ServerEntityPositionPacket[37;1m[0m
[36;1m[13:37:03] [33;1m[WARNING] [PC to PE] No translator found for : org.spacehq.mc.protocol.packet.ingame.server.entity.ServerEntityHeadLookPacket[37;1m[0m

**Comment by DefinitlyEvil** [comment]
we(actually they) are updating to the new protocol and lots of stuff won't work yet.
