### ISSUE TITLE
JSON messages needs to be transformed into plain messages.

### ISSUE THREAD

**Issue by MrPowerGamerBR** [DragonetMC/DragonProxy#41]
![screenshot_20160102-172805](https://cloud.githubusercontent.com/assets/9496359/12075867/928bd9a8-b176-11e5-8f4c-6dc5c6834e2a.png)

The server sends a "JSON message" to the Minecraft client, but the MCPE client doesn't "transform" the JSON message to something... "readable", creating that mess in the chat.

One solution is making DragonProxy detect if it is a JSON message, if it is a JSON message, loop all the JSON arrays to get the "text" value (sometimes is not just one JSON message with a text value, so be careful with that), after this, send the "text" value to the client.

**Comment by RandomAltThingy** [comment]
I don't even see colour chat

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy strange, when joining my public server using the DragonProxy, the client display that mess because my chat uses JSON messages so you can hover player names to see something useful, etc.

Also, some colors are correctly displayed in that "mess" (for some reason)

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy If you want to see what happens, set the proxy to connect to "158.69.120.5", port "25565" (It is my public server, I was DragonProxy on it), also, set the online-mode to false on the proxy, it isn't needed.

If you done everything right, you will connect and see... "the mess in the chat" (It only happens when the plugin sends a JSON message, another way to have the same bug (in Vanilla too!) is killing someone with a item with a custom name)

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy also, it seems that the "coloring" in the chat came from a colored item name/lore that I was using to display information on mouse hover.

**Comment by RandomAltThingy** [comment]
@MrPowerGamerBR PC currently broken, can you setup the proxy?

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy I will setup the proxy on the dedicated server, will reply when I done setting it up.

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy 158.69.120.5:19132

Running the latest artifact build, proxy is redirecting to 158.69.120.5:25565.

The chat issue appears as soon as you log in (as long there is people saying things in chat)

(Also, for some reason the MCPE client crashes when I'm in spawn)

**Comment by RandomAltThingy** [comment]
What is the world name?

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy on the server? it is the default Minecraft world name "world".

Also, I'm not running BungeeCord, if this affects anything.

(Also, this may be related because I'm running the Protocol Hack 1.7.10)

**Comment by RandomAltThingy** [comment]
Proxy offline

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy are you sure? It is reachable here.

(The port is the default MCPE port)

![screenshot_20160102-185958](https://cloud.githubusercontent.com/assets/9496359/12076086/23810cd8-b183-11e5-8d51-905de3b5a18e.png)

**Comment by RandomAltThingy** [comment]
Got the exact same thing

**Comment by RandomAltThingy** [comment]
Is it on a remote server?

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy the proxy is running on the same server as my PC server.

DragonProxy config:
´´´
# =================================
#| DragonProxy Configuration File  |
#|    Sponsered by BytePowered     |
# =================================


# Language file
# If you downloaded other language files such 
# as de_DE.lang, place it in the same folder of DragonProxy binary,
# set lang to de_DE.lang (Default: english)
lang=default

# What IP and port to bind on your own computer/server. 
# IP 0.0.0.0 means bind to all IP addresses available on your own computer/server. 
udp_bind_ip=0.0.0.0
udp_bind_port=19132

# The IP and Port of the PC/Mac Server you want to connect to.
remote_ip=127.0.0.1
remote_port=25565

# Server Mode?
# To join premium PC/Mac servers you must set this to true. 
# You will be notified to login to your Minecraft PC/Mac account when you connect. 
online_mode=false

# How many players can join the proxy at once?
max_players=120

# Should we create the console.log file?
log_console=true

# How many threads will process MCPE packets? Only change if you know what you're doing.
# Recommanded at least 8 threads. 
# If you using this software at home, you can set to lower value like 8 or 12. 
# If you using it on a multi-player server, you may want to have 2 threads per 50 players. 
thread_pool_size=32

# ===============================
#|      Recommanded Servers      |
# ===============================
# [None yet]  - Donate to us to get your server advertised here. 
#             - Contact Skype: DefinitlyEvil (Check spelling before you add, it's Definitly but NOT Definetly)
´´´

The Server is reachable for me on my Minecraft PC client and the Proxy is reachable with the MCPE client (I don't know why the player count is -1, but you can connect to it and "play" (and see the server chat).

I don't know why it would be unreachable for you.

**Comment by RandomAltThingy** [comment]
Ummm the remote_ip should be the IP of the PC server.

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy I don't know why it should be... I kept 127.0.0.1 because the Proxy and the Server are in the same machine, whatever, I changed the "remote_ip" to the server IP address and rebooted the proxy.

**Comment by RandomAltThingy** [comment]
[Lol](http://m.imgur.com/InN7MOO)

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy ok, that's weird.

The only thing you can try is see if "(http://mrpowergamerbr.com)[http://mrpowergamerbr.com]" is reachable on your browser, if it reachable, try adding "mrpowergamerbr.com" to the server list. (The server/proxy/my website/the server website are on the same machine)

**Comment by RandomAltThingy** [comment]
Works

**Comment by RandomAltThingy** [comment]
Can you change the proxy remote_ip to

hub.reborncraft.his

For testing purposes.

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy changed and rebooted.

**Comment by RandomAltThingy** [comment]
.biz
Soz

**Comment by RandomAltThingy** [comment]
@MrPowerGamerBR

**Comment by RandomAltThingy** [comment]
Keep it offline mode

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy changed and rebooted.

**Comment by RandomAltThingy** [comment]
@MrPowerGamerBR Can I get access? It would be useful for testing.

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy The problem is that dedicated server is my dedicated server which hosts my server/my website/my blog/my everything.

If you really need a VPS, I can buy a Linux 512MB VPS on US for you.

**Comment by RandomAltThingy** [comment]
@MrPowerGamerBR REALLY? Thanks! When got it DM me on twitter.com/thediamondyt or Skype goldowl_37

**Comment by RandomAltThingy** [comment]
We eventually won't need it if we get more sponsors.

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy add me on Skype (my username is "mrpowergamerbr", I already sent a contact request)

**Comment by RandomAltThingy** [comment]
@MrPowerGamerBR Make your Reddit.com/r/MCPE flare "DragonProxy Community Support" :)

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy sorry for being without reply for so many days.

I'm travelling right now and no, the VPS didn't activate so I done a chargeback to get the money back, I won't be able to buy another VPS until I get back home, sorry. 😑

**Comment by MrPowerGamerBR** [comment]
Another photo of the issue:

![http://i.imgur.com/JRYAs3h.png](http://i.imgur.com/JRYAs3h.png)

Suggested Solution:
Edit the ChatPacket.java, before setting the data to walk the JSON array to get only the text, I will try to fix the issue, but I don't promise anything. :wink:

**Comment by DefinitlyEvil** [comment]
@MrPowerGamerBR I already did JSON translation in translator but idk why this happens.

**Comment by MrPowerGamerBR** [comment]
Already fixing this issue myself, will create a pull request when I'm done.

**Comment by MrPowerGamerBR** [comment]
Pull request fixing this issue: #55

**Comment by MrPowerGamerBR** [comment]
Pull request pulled by @RandomAltThingy , closing the issue
