### ISSUE TITLE
Can you add pc 1.14 support?

### ISSUE THREAD

**Issue by pppwaw** [DragonetMC/DragonProxy#415]

**Comment by Redned235** [comment]
Minecraft 1.14 is not (officially) out yet. The only thing that is currently out are the pre-releases. Plus I don't think there are any servers yet running in 1.14 except for maybe a few vanilla ones.

**Comment by pppwaw** [comment]
Since the  1.14 cannot be supported, when can the bedrock 1.10 be supported?

**Comment by Redned235** [comment]
> Since the 1.14 cannot be supported, when can the bedrock 1.10 be supported?

Fairly sure DragonProxy is undergoing a recode right now. I'm unsure of how long this process will be, but it probably won't be for a couple months at the least.

**Comment by pppwaw** [comment]
OK
