### ISSUE TITLE
No main manifest attribute

### ISSUE THREAD

**Issue by CCF100** [DragonetMC/DragonProxy#417]
When I try to start the proxy, java returns this:
`no main manifest attribute, in dragonproxy-0.0.1-SNAPSHOT.jar`

**Comment by lukeeey** [comment]
Run dragonproxy-bootstrap

**Comment by CCF100** [comment]
![Screenshot_20190508-161601](https://user-images.githubusercontent.com/29297989/57408967-b2d30c00-71ac-11e9-8e4d-f5b8d8979358.png)
Whenever I run the bootstrap, I get this: (this is an ssh session)

**Comment by lukeeey** [comment]
Go to the root of the repository and run `git submodule update --init`

**Comment by lukeeey** [comment]
Then build it again
