### ISSUE TITLE
Can you tell me where you get the mcpe versions from?

### ISSUE THREAD

**Issue by hipvpitsme** [DragonetMC/DragonProxy#418]
I was wondering where you devs got the mcpe versions from. Im assuming nukkit or pmmp, because i wanted to try to code in support for thoes versions. Could you also tell me the file that shows which version is supported?

**Comment by pppwaw** [comment]
now the mcpe version is 1.11,but the dargonetproxy is support 1.5.

**Comment by EOT3000** [comment]
the nukkitx protocol lib.

**Comment by hipvpitsme** [comment]
> the nukkitx protocol lib.

thx for the response man
