### ISSUE TITLE
Support for the upcoming 1.14.3 release.

### ISSUE THREAD

**Issue by benrobson** [DragonetMC/DragonProxy#419]
Hello,
I am looking to add DragonProxy to my Minecraft server when 1.14.3 is released, to allow a maximum amount of users to play on the server.
When will it be viable that DragonProxy will be released for 1.14.3, when it's out of pre-releases of course.

**Comment by Redned235** [comment]
DragonProxy is currently undergoing a rewrite. As of now you can use it to join offline mode servers and chat, but really nothing more than that. There is still a lot work left to be done, and most likely it won't be any time soon.
