### ISSUE TITLE
Can't find plugin

### ISSUE THREAD

**Issue by Nyssa73** [DragonetMC/DragonProxy#421]
I am trying to follow the instructions to install DragonProxy and BungeeCord on my PC so that I can join a Java Minecraft game from my iPad. I think I have installed DragonProxy and BungeeCord correctly, but I cannot find the DragonProxy-BungeeCord plugin. The links I try to follow are all 404:File Not Found. Any help would be appreciated.
Thanks.

**Comment by Sourack** [comment]
Plugin ???

**Comment by Nyssa73** [comment]
I am trying to follow the instructions at
https://github.com/DragonetMC/DragonProxy/wiki/Hybrid-Mode-Setup
because I have a version of Minecraft PE and an XBox account and I would
like to join a Minecraft Java game running on a PC. We are using the same
router. The web page says I need a DragonProxy-BungeeCord plugin.

- Angela

**Comment by lukeeey** [comment]
We don't support the master branch anymore, it is being completely rewritten.

**Comment by Nyssa73** [comment]
So if I want to use your program, what do I need to do?
- Angela

**Comment by lukeeey** [comment]
Download the latest build from here: https://ci.codemc.org/job/DragonetMC/job/DragonProxy/lastSuccessfulBuild/

**Comment by Nyssa73** [comment]
And from there I download the .jar file and run that?
Thanks,
Angela

**Comment by lukeeey** [comment]
![image](https://user-images.githubusercontent.com/32024335/62838720-ecb62180-bc77-11e9-9101-92ac9df02269.png)

[Direct link](https://ci.codemc.org/job/DragonetMC/job/DragonProxy/lastSuccessfulBuild/artifact/bootstrap/target/DragonProxy.jar)

**Comment by Nyssa73** [comment]
Thank you. I’m now trying to determine what all the fields in the
configure.yml file should be. What is the difference between the various
ports and  IP addresses
and how do I find them?

- Angela

**Comment by lukeeey** [comment]
`bind-address` and `bind-port` should probably stay the same. This is the address and port that the proxy will bind to, to allow bedrock connections.

`remote-address` and `remote-port` are the address and port of the java edition server that you want to connect to.
