### ISSUE TITLE
Not technically an issue but i have questions.

### ISSUE THREAD

**Issue by RudRecciah** [DragonetMC/DragonProxy#423]
I have 2 public servers ready to go, all I need is to host them. This allows me to host both of them using 1 server. After looking at this, I have many questions about it. Does this work like a plugin, implementing itself into the server, or is it like its own server? Do I need to have another server computer for this? Do I need to open a port for it? Do I have to use hybrid mode for pocket/windows 10 users to join? Why does this exist; isn't information translated to binary and then translated again in the recipient's language, meaning that it's just a matter of telling the device to translate to C++ instead of Java? Do I need BungeeCord if I don't use hybrid mode? If I need BungeeCord, does it work like a plugin, or does it work like another server? Do Do I understand this correctly:
1. Bedrock player joins DragonetMC
2. DragonetMC forwards the player to the java edition server
3. DragonetMC translates the information coming from the server to C++

Sorry if this is really obvious, I don't understand much more than how to make an extremely simple vb script.
Thanks!

**Comment by lukeeey** [comment]
1) This is standalone software that creates a server to allow the bedrock client to join. It then establishes a connection to a remote java edition server and translates the packets.
2) You dont need another computer
3) Yes, you need to open a udp port
4) The rewrite (which is the only supported version currently) does not have hybrid mode and tbh i have no idea what it does
5) The protocol specification for each version is different. Different platforms have different features, different packets, different fields in packets, different entity ids, different item / block ids etc
6) You dont need bungeecord

Nothing here has anything to do with C++, it (not so) simply translates things from one edition to the equivalent (or somewhat equivalent - we may need to do a bit of work to get the desired outcome) of the other platform
