### ISSUE TITLE
Compilation failure 'cannot find symbol' error

### ISSUE THREAD

**Issue by cr08** [DragonetMC/DragonProxy#426]
Recently came back across this project and would like to keep tabs on it as the rewrite progresses. However trying to compile it I am getting this 'cannot find symbol' error that I can't seem to find a proper resolution to:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project dragonproxy: Compilation failure
> [ERROR] /home/cr08/DragonProxy/proxy/src/main/java/org/dragonet/proxy/network/ProxyServerEventListener.java:[35,16] cannot find symbol
> [ERROR]   symbol:   class MessageUtils
> [ERROR]   location: package sun.misc`

Currently running on a near stock Ubuntu 18.04 install and just installed maven from the default repos. Looks like it grabbed openjdk 11.0.4 during that time.

**Comment by lukeeey** [comment]
Can you give the entire stack trace and the command you are using to build?

**Comment by cr08** [comment]
Sure thing:

[dragonproxy_stacktrace.txt](https://github.com/DragonetMC/DragonProxy/files/3483579/dragonproxy_stacktrace.txt)

And the command is simply `mvn clean install` (or `mvn clean install -e` in this case) from /home/cr08/DragonProxy/ where the repo is cloned out to.

**Comment by SupremeMortal** [comment]
Why are we using a `sun.misc` class which is an internal API?
It's likely the Java version compiled against doesn't have this API exposed anymore.

**Comment by lukeeey** [comment]
I have no idea i dont think ive seen it in the code

**Comment by SupremeMortal** [comment]
https://github.com/DragonetMC/DragonProxy/blob/b359e285048a9d3856089c658912aa9929812a9a/proxy/src/main/java/org/dragonet/proxy/network/ProxyServerEventListener.java#L35
