### ISSUE TITLE
Dye color is incorrect

### ISSUE THREAD

**Issue by lukeeey** [DragonetMC/DragonProxy#427]
For some reason on the `new-item-mappings` branch the dye color is incorrect. If you type `/give player green_dye` it will give pink dye and if you give yourself blue dye it with give you yellow dye.

I have no idea why this is, as the data value is the same as the ones for the same colour of wool or stained glass (and those both work fine).

**Comment by EOT3000** [comment]
it's probably the order

**Comment by EOT3000** [comment]
would be easier if you had your mapper open source, like geyser's

**Comment by lukeeey** [comment]
Its not the order because firstly i checked it and secondly i said it works for wool and stained glass

**Comment by CtrlAltCuteness** [comment]
> Its not the order because firstly i checked it and secondly i said it works for wool and stained glass

Are you or someone else able to provide the item you try to get, the item you see, and also the item the server sees (via. testing what item the player has)?

**Edit:** For all the main 16 dye colors.

**Comment by lukeeey** [comment]
Green -> Magenta
Magenta -> Green
White -> Ink Sac
Ink Sac -> Nothing *(should look into that)*
Blue -> Yellow
Yellow -> Blue (lapis lazuli)
Brown -> Light Blue
Light Blue -> Brown (cocoa beans)
Red -> Orange
Orange -> Red
Black -> White (bone meal)
Pink -> Cyan

You get the idea

**Comment by CtrlAltCuteness** [comment]
@lukeeey Looks like the bits are inverted when being read and / or sent back.

**Edit**: Some dyes exist separate from their old-style item (blue, black and white dyes for example)

**Comment by lukeeey** [comment]
Its only for dyes

**Comment by CtrlAltCuteness** [comment]
@lukeeey Can you DM me on Discord so I can try to join and inspect what my client sees?

**Comment by lukeeey** [comment]
Ah i think ive figured it out

**Comment by EOT3000** [comment]
what is it?

**Comment by lukeeey** [comment]
im not gonna tell you lol

**Comment by Tim203** [comment]
"A team of developers helping Minecraft in every corner we can. "

**Comment by lukeeey** [comment]
But thats not helping Minecraft and also i didnt write that description

**Comment by Tim203** [comment]
It will help, because Geyser does what DragonProxy does, and that is connecting Minecraft's community. So by telling what is wrong / making the mapper open source you'll help the Minecraft community. Also for projects to come from other people.
