### ISSUE TITLE
Actionbar in chat

### ISSUE THREAD

**Issue by Beaness** [DragonetMC/DragonProxy#429]
The actionbar is send in chat and not to the action bar it self.

**Comment by lukeeey** [comment]
Its not

**Comment by Beaness** [comment]
Weird i was on a server and the action bar was spamming every x seconds in chat.

**Comment by lukeeey** [comment]
Can you show me?

**Comment by MVDW-Java** [comment]
I got the same issue + world does not load for me.
Here is a video of this: https://youtu.be/72jsUPjyQjo

if you want I can give you my configuration.

**Comment by lukeeey** [comment]
![image](https://user-images.githubusercontent.com/32024335/62973841-d68e9980-be0e-11e9-968e-17aac4cb76a7.png)

I did join that server and see it in chat though. I have no idea why that is happening.

**Comment by lukeeey** [comment]
Also chunks arent implemented yet so you wont see anything

**Comment by Beaness** [comment]
I get the same look like maxw2000 only on a different server.

**Comment by lukeeey** [comment]
Not seeing the world or action bar in chat?

**Comment by Beaness** [comment]
action bar in chat
