### ISSUE TITLE
Unable to load block

### ISSUE THREAD

**Issue by Khushashi** [DragonetMC/DragonProxy#430]
When you enter the game, you will get stuck in the void.

**Comment by SkRThatOneDude** [comment]
Known issue. Chunk loading is not yet implemented. Please check updates for future progress.

**Comment by Khushashi** [comment]
So can the historical version of 1.5.0-1.12 load the block?

**Comment by SkRThatOneDude** [comment]
The historical version works, but not with newer versions of Java or Bedrock.

There are also bugs in the historical version with certain server plugins that change blocks. For example, McMMO's "tree feller" ability does not show client side when the whole tree breaks, but you can relog and see the tree did indeed break.

**Comment by WesleyVanNeck** [comment]
close this
