### ISSUE TITLE
World not loading

### ISSUE THREAD

**Issue by qwertyuser1234** [DragonetMC/DragonProxy#431]
Not sure if this was resolved but I was able to connect to the server and even use the chat function but the world doesn't load at all. The only thing I can see is the weather.

**Comment by cr08** [comment]
Might want to review the front page/README. On the checklist is 'Chunk loading' which essentially translates to world loading. It is not currently implemented at this time so what you see is expected.

**Comment by qwertyuser1234** [comment]
Whoops sorry for that and thanks for clarifying.
