### ISSUE TITLE
PaletteManager is referencing to nonexistent file.

### ISSUE THREAD

**Issue by nuriofernandez** [DragonetMC/DragonProxy#433]
Why this file doesn't exist? How this works?https://github.com/DragonetMC/DragonProxy/blob/c418da1e60c2c7233e0559029aa56baf77bee178/proxy/src/main/java/org/dragonet/proxy/util/PaletteManager.java#L51

**Comment by lukeeey** [comment]
When cloning the repo add the `--recursive` flag or go to the root of the repo and do `git submodule update --init`

**Comment by SupremeMortal** [comment]
@lukeeey Might want to add that step to the readme and/or make the exception display useful information to fix the problem.

**Comment by lukeeey** [comment]
I technically did add it to the readme. It says clone recursively

**Comment by cr08** [comment]
Ran into this myself. As a somewhat git newb who often just sees a basic `git clone repo` everywhere, maybe being explicit in the README to use this command will be beneficial?

**Comment by nuriofernandez** [comment]
> I technically did add it to the readme. It says clone recursively

Sometimes humans do a _skim-reading_ without reading nothing at all. For this reason, I think that making that **line bold** can be a good idea. **<3**
