### ISSUE TITLE
(Sorry to post in issues) Is this project active?

### ISSUE THREAD

**Issue by TS440S** [DragonetMC/DragonProxy#435]
I see that is says on the description of this project that 1.14.4 is supported, but then I see that in the todo list that stuff like player movement and chunk loading is not done yet. Is this plugin usable in any form currently? Again sorry for posting In issues but I don’t know any other way to comment on this project. Thank you to anyone working on this.

**Comment by ZD-ChaofanJ** [comment]
From what I am aware of, yes. The program is currently going through a rewrite. (Note:  I am not a developer)

**Comment by MVDW-Java** [comment]
Right now there are no stable/full working builds of this software.
These builds are only development builds and it's NOT meant for public use.
And yes, this project is still active.
