### ISSUE TITLE
could not connect to outdated server

### ISSUE THREAD

**Issue by TamasSzerb** [DragonetMC/DragonProxy#436]
with 
java -jar ~toma/local/minecraft/dragonproxy/dragonproxy-0.3.4.6-SNAPSHOT.jar

from 

iphone/ IOS 1.12 minecraft client

with 

minecraft_server.1.14.4.jar

any idea?

even 

log_debug: true

can't see anything in logs, only the ping from the ios bedrock / pe client:

should we fake the version somehow in dragonproxy? ort do I miss something?

Thanks!

**Comment by lukeeey** [comment]
We do not support the old version, please download the new version from [here](https://ci.codemc.org/job/DragonetMC/job/DragonProxy/lastSuccessfulBuild/)

**Comment by TamasSzerb** [comment]
according the https://github.com/DragonetMC/DragonProxy/blob/HEAD/proxy/src/main/resources/config.yml

I rewrote the config, now, I can't even see the motd of the same server in ios client. Any idea?

**Comment by lukeeey** [comment]
Did you download the rewrite from the link i sent?

**Comment by TamasSzerb** [comment]
sure, I downloaded this:

https://ci.codemc.org/job/DragonetMC/job/DragonProxy/lastSuccessfulBuild/artifact/bootstrap/target/DragonProxy.jar

[12:41:12 INFO]: Starting DragonProxy...
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
[12:41:12 INFO]: Welcome to DragonProxy version 0.0.2-SNAPSHOT
[12:41:12 WARN]: This is a development build. It may contain bugs. Do not use in production.
[12:41:12 INFO]: RakNet server started on 127.0.0.1
[12:41:12 INFO]: Done (0.23s)!
