### ISSUE TITLE
Client crashed when join server

### ISSUE THREAD

**Issue by jiongjionger** [DragonetMC/DragonProxy#44]
01:45:08 [信息] Player nerd[/111.175.XXX.XXX:51640] connected! 
01:47:26 [信息] Client nerd[/111.175.XXX.XXX:51640] disconnected! Reason: Client disconnect
01:47:44 [信息] Player nerd[/111.175.XXX.XXX:51640] connected! 
01:47:44 [信息] Bridge established for player nerd[/111.175.XXX.XXX:51640]! 
01:47:55 [信息] Client nerd[/111.175.XXX.XXX:51640] disconnected! Reason: Client disconnect

**Comment by RandomAltThingy** [comment]
What's the remote server (You specified in the config) ip?

**Comment by DefinitlyEvil** [comment]
It said `Bridge established` so it successfully connected to remote server. What version of MCPE u using and what's the version for remote server?

**Comment by jiongjionger** [comment]
I use 0.13.1. Sometimes it works just fine(but just like disconnected), sometimes it will crashed client.
remote ip: 144.0.3.62 (1.8)

**Comment by DefinitlyEvil** [comment]
@jiongjionger Hmmm, idk what causing client crashed for now, we have to do more experiments...

**Comment by DefinitlyEvil** [comment]
Duplicated with #31 , closing.
