### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by WesleyVanNeck** [DragonetMC/DragonProxy#44]
$ mvn package
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for net.marfgamer:jraknet:jar:2.4.8
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ line 62, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ line 76, column 15
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] DragonProxy-parent
[INFO] DragonProxy
[INFO] JRakNet
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building DragonProxy-parent 0.0.7
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ DragonProxy-parent ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building DragonProxy 0.0.7
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for net.marfgamer:jraknet:jar:2.4.6 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] DragonProxy-parent ................................. SUCCESS [  0.542 s]
[INFO] DragonProxy ........................................ FAILURE [  0.283 s]
[INFO] JRakNet ............................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.999 s
[INFO] Finished at: 2017-02-18T15:12:00+01:00
[INFO] Final Memory: 8M/191M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project DragonProxy: Could not resolve dependencies for project org.dragonet.proxy:DragonProxy:jar:0.0.7: Failure to find net.marfgamer:jraknet:jar:2.4.6 in https://oss.sonatype.org/content/repositories/public/ was cached in the local repository, resolution will not be reattempted until the update interval of sonatype has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :DragonProxy

**Comment by DaMatrix** [comment]
you need to initialize submodules before building.

**Comment by WesleyVanNeck** [comment]
@DaMatrix how can i do that

**Comment by robotman3000** [comment]
@caspervanneck123  You can have git auto initialize the submodules if you add the `--recursive` option when you run `git clone`

**Comment by WesleyVanNeck** [comment]
???

**Comment by DaMatrix** [comment]
The other thing you can do is `git submodule init`

**Comment by robotman3000** [comment]
How did you download the source code?

**Comment by WesleyVanNeck** [comment]
no cloned with git gui

**Comment by DaMatrix** [comment]
Use git CLI or GitKraken

**Comment by WesleyVanNeck** [comment]
$ mvn install
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for net.marfgamer:jraknet:jar:2.4.8
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ line 62, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ line 76, column 15
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] DragonProxy-parent
[INFO] DragonProxy
[INFO] JRakNet
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building DragonProxy-parent 0.0.7
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ DragonProxy-parent ---
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ DragonProxy-parent ---
[INFO] Installing C:\Users\Wesle\Downloads\DragonProxy\pom.xml to C:\Users\Wesle\.m2\repository\org\dragonet\proxy\DragonProxy-parent\0.0.7\DragonProxy-parent-0.0.7.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building DragonProxy 0.0.7
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for net.marfgamer:jraknet:jar:2.4.6 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] DragonProxy-parent ................................. SUCCESS [  0.736 s]
[INFO] DragonProxy ........................................ FAILURE [  0.273 s]
[INFO] JRakNet ............................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.158 s
[INFO] Finished at: 2017-02-18T15:41:29+01:00
[INFO] Final Memory: 8M/135M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project DragonProxy: Could not resolve dependencies for project org.dragonet.proxy:DragonProxy:jar:0.0.7: Failure to find net.marfgamer:jraknet:jar:2.4.6 in https://oss.sonatype.org/content/repositories/public/ was cached in the local repository, resolution will not be reattempted until the update interval of sonatype has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build wit

**Comment by WesleyVanNeck** [comment]
@DaMatrix its the same

**Comment by WesleyVanNeck** [comment]
@robotman3000 what must i do mvn install or package

**Comment by DefinitlyEvil** [comment]
@caspervanneck123 try `git submodule update --init --recursive` then build again.

**Comment by DaMatrix** [comment]
show me the output of `ls` and `ls JRakNet`

**Comment by DaMatrix** [comment]
oh nvm, just read @DefinitlyEvil 's comment
do that then `mvn package`

**Comment by WesleyVanNeck** [comment]
@DaMatrix  @robotman3000 @DefinitlyEvil its steal same 



$ mvn package
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for net.marfgamer:jraknet:jar:2.4.8
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ line 62, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ line 76, column 15
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] DragonProxy-parent
[INFO] DragonProxy
[INFO] JRakNet
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building DragonProxy-parent 0.0.7
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ DragonProxy-parent ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building DragonProxy 0.0.7
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for net.marfgamer:jraknet:jar:2.4.6 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] DragonProxy-parent ................................. SUCCESS [  1.686 s]
[INFO] DragonProxy ........................................ FAILURE [  0.946 s]
[INFO] JRakNet ............................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.809 s
[INFO] Finished at: 2017-02-18T17:55:10+01:00
[INFO] Final Memory: 7M/135M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project DragonProxy: Could not resolve dependencies for project org.dragonet.proxy:DragonProxy:jar:0.0.7: Failure to find net.marfgamer:jraknet:jar:2.4.6 in https://oss.sonatype.org/content/repositories/public/ was cached in the local repository, resolution will not be reattempted until the update interval of sonatype has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :DragonProxy

Wesle@DESKTOP-G72R5H7 MINGW64 ~/DragonProxy (refactor)
$

**Comment by DefinitlyEvil** [comment]
weird

**Comment by DefinitlyEvil** [comment]
try not to use MinGW

**Comment by ghost** [comment]
@robotman3000 @DaMatrix  @DefinitlyEvil #45 the fix

can i be invited to help you?

**Comment by TheDiamondYT1** [comment]
@caspervanneck Because there isint a button to [fork it](https://github.com/DragonetMC/DragonProxy/fork).

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil should i invite @caspervanneck?

**Comment by DaMatrix** [comment]
Just make pull requests like the rest of us.  You've only contributed 1 line.

**Comment by TheDiamondYT1** [comment]
@DaMatrix Good point i must be half asleep  in the middle of the day didnt even realise he only contributed 1 line

**Comment by ghost** [comment]
this can be clost its fixt

**Comment by ghost** [comment]
@thebigsmileXD
