### ISSUE TITLE
Can't connect to world, says outdated.

### ISSUE THREAD

**Issue by quikscpreapz** [DragonetMC/DragonProxy#446]
Sorry if I am wasting people's time, I am new to this and don't know if I'm doing something wrong, so please bear with me.
I downloaded the 0.3.4.6 snapshot (titled dragonproxy-0.3.4.6-SNAPSHOT.jar) set everything up, and went into 1.12 windows 10 edition, and when I clicked to join, it told me that the version was outdated. I looked at what was put out when starting the proxy, and noticed that it was still saying "supported PC version 1.12.2, etc" and that is not the version of java I am running. I am currently using 1.14.4 for java edition.

**Comment by 12emin34** [comment]
You are using the old version, download the latest one from Jenkins

**Comment by quikscpreapz** [comment]
Hmm. Sorry, but where do I find Jenkins at? Or do you mean the website? Because I couldn't find it on the website either.

**Comment by blueberrymuffin3** [comment]
https://ci.codemc.io/job/DragonetMC/job/DragonProxy/
