### ISSUE TITLE
Unable to connect to world

### ISSUE THREAD

**Issue by communityfablab** [DragonetMC/DragonProxy#449]
Hi all - thank you so much for making this project and developing this code. We've recently been awarded an NSF grant to help kids learn about exoplanets though Minecraft simulations and our current server, based on Java/Bukkit, will need to be able to host hoards of helpless children with only Minecraft PE. I've been working on setting up dragonproxy today with no luck. Here's what all I've tried:

-Dragon Proxy versions (0.0.2-snapshot and 3.4.6)
-Our regular Bukkit server 1.14.4 and a temporary blank/default Forge server on 1.12.2
-Minecraft PE on Android and iOS 1.12.1
-Only changing this setting -> remote-address: '192.17.189.137' (our address)
-No ports are on anything are nonstandard, no firewalls, regular connections all work fine

Neither Minecraft PE install can see any info about the server and gives the "Unable to connect to world" response when we attempt to force it. They are able to connect to the featured servers. I've attached my config file here, I'm not sure what else to do. Any suggestions? 

I realize you probably get silly newbies like my self asking for help often. If you can help me work through it I'd be happy to help document how to get a cross-over server going so you don't have to field questions from us as often. 

[config.txt](https://github.com/DragonetMC/DragonProxy/files/3747210/config.txt)

**Comment by Heath123** [comment]
DragonProxy is nowhere near ready.  Try this:
https://drive.google.com/file/d/1gS9yvNwkPJG8t-W48Zyx57Sc8gV6fk8Q/view?usp=sharing
It almost works
GitHub page for it:
https://github.com/GeyserMC/Geyser

**Comment by Heath123** [comment]
It's definitely best to use a Bedrock-specific server.

**Comment by Heath123** [comment]
Basic chunks and movement work on this and Geyser, but nothing fancy that you'd need to show simulations.

**Comment by communityfablab** [comment]
Thank you for the incredibly fast response! So it looks like your PE device has to be on the same network as the proxy then? I quickly ran through setup with Geyser and a default MC server and get the same error message. We'd be expecting kids from random homes trying to join with their iPhones and such - many parents/kids don't seem to understand the difference between Java and Bedrock.

We'll almost certainly pay for a professional server that can host as bedrock, just wanted to setup a testbed at our UIUC location so we can safety mess things up before deploying them :)

**Comment by Heath123** [comment]
Did you port forward properly? 

By the way I'm not a dev but I can help you because I know how to use this and how it works

**Comment by Redned235** [comment]
> Thank you for the incredibly fast response! So it looks like your PE device has to be on the same network as the proxy then? I quickly ran through setup with Geyser and a default MC server and get the same error message. We'd be expecting kids from random homes trying to join with their iPhones and such - many parents/kids don't seem to understand the difference between Java and Bedrock.
> 
> We'll almost certainly pay for a professional server that can host as bedrock, just wanted to setup a testbed at our UIUC location so we can safety mess things up before deploying them :)

You can portforward and allow anyone from anywhere to join. 

One server that you can test Geyser on is play.loyaltymc.net (if I knew of a server running DragonProxy I would link it instead). It accepts both bedrock connections (port 19132) and Java connections (port 25565). If you would instead like to use Geyser instead of DragonProxy, let’s move this conversation into the Geyser GitHub or the Geyser Discord server (link is in the README).

**Comment by communityfablab** [comment]
Heath:

I think we're forwarding ports correctly, but I'm not sure. Right now the config file has:

```
# The IP and port the proxy will listen for connections on
# '0.0.0.0' will bind to all IP addresses available on your device
bind-address: '0.0.0.0'
bind-port: 19132

# The MOTD that will be shown on the MCPE server list
motd: 'FAB LAB TEST'

# The maximum amount of players that can join the proxy
max-players: 3

# The IP and port of the remote server to connect to
# TODO: Add support for multiple servers
remote-address: '192.17.189.137'
remote-port: 25565
```

I know the server is operating on that IP and port. 

RednedEpic:

Agreed, I'll shuffle conversation over there. My PE device was able to connect to that server without issue. 

Thank you both for the help!

**Comment by lukeeey** [comment]
May i ask why you are not using a mcpe server software if the kids only have minecraft pe?

**Comment by EOT3000** [comment]
bedrock server software, well, they sort of lack many features, and apis

**Comment by Heath123** [comment]
But this lacks way more

**Comment by Tim203** [comment]
True, but I would also wait for projects like DP to catch up if I was him.
