### ISSUE TITLE
Hypixel doesnt work

### ISSUE THREAD

**Issue by tonibm19** [DragonetMC/DragonProxy#45]
I cant get to see any blocks.
Using mcpe 0.13.1

**Comment by RandomAltThingy** [comment]
It's a bug with NoCheat+ join servers without it

**Comment by tonibm19** [comment]
Any other compatible server IP?

**Comment by DefinitlyEvil** [comment]
It will take years for MCPE teleport from (0,0,0) to the actual spawn point, I'm still trying to figure a new way out. xD

**Comment by DefinitlyEvil** [comment]
Duplicated issue, #37 .
