### ISSUE TITLE
Terrain not loading, then "Timed out "

### ISSUE THREAD

**Issue by MaximPerry** [DragonetMC/DragonProxy#455]
I managed to successfully setup Dragon Proxy for my server, but I'm experiencing this issue. Once I connect to the server, only the sky and my inventory bar loads, I seem not to be able to move, and after a few seconds I get disconnected: "Timed out".

Java server: Bukkit, 1.14.4
Client: Minecraft Bedrock 1.12.1 (Android)
Dragon Proxy : Build #251

**Comment by lukeeey** [comment]
Should be fixed in the latest build
