### ISSUE TITLE
Installation via FTP

### ISSUE THREAD

**Issue by ghost** [DragonetMC/DragonProxy#458]
Hey,
Can you please make a video "how to install DragonProxy via FTP"? I can't use commands via server interface so i have to make a .bat file!

**Comment by ghost** [comment]
Sorry, can you please translate it to German?

Luke <notifications@github.com> schrieb am Do., 2. Apr. 2020, 16:11:

**Comment by lukeeey** [comment]
Well I don’t know german

**Comment by ghost** [comment]
Ok! I paste it into Google Translator

Luke <notifications@github.com> schrieb am Do., 2. Apr. 2020, 18:53:
