### ISSUE TITLE
Is the project still in development or...?

### ISSUE THREAD

**Issue by Esinko** [DragonetMC/DragonProxy#460]
I would be interested in using this proxy, but my server is 1.15.2. Will this proxy get an update to support 1.15.2 ever?

**Comment by lukeeey** [comment]
Yes it’s being worked on behind the scenes

**Comment by Heath123** [comment]
> I would be interested in using this proxy, but my server is 1.15.2. Will this proxy get an update to support 1.15.2 ever?

Probably not, because there’s a new proxy that does everything this did. Look up GeyserMC
