### ISSUE TITLE
Cannot find the plugin.yml

### ISSUE THREAD

**Issue by Zagzo** [DragonetMC/DragonProxy#466]
I'm trying to start up the server buy it doesn't want to work. Wondering if its cause of 
"31.03 17:45:43 [Server] INFO org.pf4j.PluginException: Cannot find the plugin.yml"

**Comment by lukeeey** [comment]
This is not a plugin.

**Comment by Zagzo** [comment]
I know its not a plugin. Can someone explain how to install this and set it up
