### ISSUE TITLE
Can someone explain how to install and set this up

### ISSUE THREAD

**Issue by Zagzo** [DragonetMC/DragonProxy#467]
I know it's not a plugin.
I've been trying to set this up for ages but I cant. I keep having problems and ngl I have no clue what I'm really doing

**Comment by Zagzo** [comment]
I keep running into problems like it will just stop or keep crashing in a loop

**Comment by lukeeey** [comment]
I think you’re using a version from the releases section even though it clearly states to not use them and use the link in the README

**Comment by lukeeey** [comment]
I have made a [wiki page](https://github.com/DragonetMC/DragonProxy/wiki) with setup instructions
