### ISSUE TITLE
Can't connect to the proxy via Java version

### ISSUE THREAD

**Issue by JustLeader** [DragonetMC/DragonProxy#469]
It looks like it has problems with binding the port...
I made sure nothing was running on 25565 but still, didn't work... Help

`Using username "root".
root@*ip*'s password:
Access denied
root@*ip*'s password:
Access denied
root@*ip*'s password:
Welcome to Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-91-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

 * Canonical Livepatch is available for installation.
   - Reduce system reboots and improve kernel security. Activate at:
     https://ubuntu.com/livepatch
Last login: Thu Apr  2 08:41:40 2020 from *ip*
root@ns54611:~# screen -r
There are several suitable screens on:
        11042.arcade    (04/02/2020 08:42:00 AM)        (Detached)
        22090.pts-0.ns54611     (04/01/2020 10:13:52 AM)        (Detached)
Type "screen [-d] -r [pid.]tty.host" to resume one of them.
root@ns54611:~# cd /home/bungee
root@ns54611:/home/bungee# sh start.sh
root@ns54611:/home/bungee# cd /home/DragonProxyTest
root@ns54611:/home/DragonProxyTest# sh start.sh
root@ns54611:/home/DragonProxyTest# screen -r
There are several suitable screens on:
        28736.test      (04/02/2020 09:32:58 AM)        (Detached)
        28684.bungee    (04/02/2020 09:32:47 AM)        (Detached)
        11042.arcade    (04/02/2020 08:42:01 AM)        (Detached)
        22090.pts-0.ns54611     (04/01/2020 10:13:53 AM)        (Detached)
Type "screen [-d] -r [pid.]tty.host" to resume one of them.
root@ns54611:/home/DragonProxyTest# screen -r test
[screen is terminating]
root@ns54611:/home/DragonProxyTest# screen -r
There are several suitable screens on:
        28684.bungee    (04/02/2020 09:32:47 AM)        (Detached)
        11042.arcade    (04/02/2020 08:42:01 AM)        (Detached)
        22090.pts-0.ns54611     (04/01/2020 10:13:53 AM)        (Detached)
Type "screen [-d] -r [pid.]tty.host" to resume one of them.
root@ns54611:/home/DragonProxyTest# sh start.sh
root@ns54611:/home/DragonProxyTest# screen -r
There are several suitable screens on:
        19047.test      (04/02/2020 09:34:58 AM)        (Detached)
        28684.bungee    (04/02/2020 09:32:47 AM)        (Detached)
        11042.arcade    (04/02/2020 08:42:01 AM)        (Detached)
        22090.pts-0.ns54611     (04/01/2020 10:13:53 AM)        (Detached)
Type "screen [-d] -r [pid.]tty.host" to resume one of them.
root@ns54611:/home/DragonProxyTest# screen -r test
[screen is terminating]
root@ns54611:/home/DragonProxyTest# sh start.sh
root@ns54611:/home/DragonProxyTest# screen -r
There are several suitable screens on:
        1503.test       (04/02/2020 09:42:10 AM)        (Detached)
        28684.bungee    (04/02/2020 09:32:47 AM)        (Detached)
        11042.arcade    (04/02/2020 08:42:01 AM)        (Detached)
        22090.pts-0.ns54611     (04/01/2020 10:13:53 AM)        (Detached)
Type "screen [-d] -r [pid.]tty.host" to resume one of them.
root@ns54611:/home/DragonProxyTest# screen -r test
[screen is terminating]
root@ns54611:/home/DragonProxyTest# sh start.sh
root@ns54611:/home/DragonProxyTest# screen -r test

[09:43:43][INFO ] Creating thread pool(Size:12)...
[09:43:44][INFO ] This is a development build. It may contain bugs. Do not use on production.
[09:43:44][INFO ] Starting up DragonProxy, version: 0.3.4.6-SNAPSHOT (276ad68) ...
[09:43:44][INFO ] Supported version of Minecraft PC/Mac: 1.12.2
[09:43:44][INFO ] Supported version of Minecraft: Pocket/Windows 10 Edition: v1.5.0
[09:43:44][INFO ] Java version : 11.0.6
[09:43:44][INFO ] System arch : amd64
[09:43:44][INFO ] System os : Linux 4.15.0-91-generic
[09:43:45][INFO ] 09:43:45 [INFO ] org.pf4j.DefaultPluginStatusProvider -> Enabled plugins: []

[09:43:45][INFO ] 09:43:45 [INFO ] org.pf4j.DefaultPluginStatusProvider -> Disabled plugins: []

[09:43:45][INFO ] 09:43:45 [INFO ] org.pf4j.DefaultPluginManager -> PF4J version 0.0.0 in 'deployment' mode

[09:43:45][INFO ] Loaded sound translates: 499
[09:43:45][INFO ] 09:43:45 [INFO ] org.pf4j.AbstractPluginManager -> No plugins

[09:43:45][INFO ] Binding on 89.203.249.158:25565 ...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/home/DragonProxyTest/server.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[09:43:45][INFO ] The proxy has started!
`

**Comment by lukeeey** [comment]
You’re using a very old version. Use this https://ci.codemc.io/job/DragonetMC/job/DragonProxy/lastSuccessfulBuild/artifact/bootstrap/target/DragonProxy.jar
