### ISSUE TITLE
Extremely high CPU load

### ISSUE THREAD

**Issue by inxomnyaa** [DragonetMC/DragonProxy#47]
My pc without dragonproxy:
![image](https://cloud.githubusercontent.com/assets/8733998/23131468/5744c7d2-f78a-11e6-9117-191c5f386f3c.png)

PC with dragonproxy:
![image](https://cloud.githubusercontent.com/assets/8733998/23131489/72c7270c-f78a-11e6-8bb4-c0f76c320a37.png)

I closed the Java Firewall window. Maybe its a leak if the firewall doesn't accept it?

**Comment by ethsmith** [comment]
DragonProxy has always had a high CPU load, when we had it hosted on an official test sever that had a Xeon E5v3 it still maxed out the CPU.I am not sure why.

**Comment by Aang23** [comment]
This is a problem only on Windows...
I've some idea about this to come from the Windows core ( which is bad in resources management ).

**Comment by ethsmith** [comment]
@Fungie2134 No it is not. sorry but blaming windows doesn't fix this one haha. I have been with Dragonet/DragonProxy from the beginning it has always been like this.

**Comment by inxomnyaa** [comment]
I experience the same issues on linux. (EDIT: and mac)

**Comment by DefinitlyEvil** [comment]
We probably should add some Thread.sleep(); into some loops somewhere somehow.

**Comment by DefinitlyEvil** [comment]
Blame me, my code always get fucked somehow.

**Comment by inxomnyaa** [comment]
sleep would reduce the over all processing performance. The problem is: either infinitely check and calculate, or cache them for.. 5 seconds or 1, and then batch all packets. Buth isnt the best..

**Comment by DefinitlyEvil** [comment]
you can do `sleep(5);` won't take much time

**Comment by DaMatrix** [comment]
...or we could use an event-based system rather than having a loop that's constantly checking things

**Comment by Aang23** [comment]
I think an event based system is the better idea, isn't it ?
And I don't get this problem on Linux, for me only on Windows. I will try on some other computers.

**Comment by ethsmith** [comment]
If it happened on some of the best Xeon processors on a dedicated servers then we can almost guarantee it's a problem everywhere.

**Comment by DefinitlyEvil** [comment]
I used to get my i7-6700k 100% load lol

**Comment by DaMatrix** [comment]
Why does @thebigsmileXD have write access???

**Comment by inxomnyaa** [comment]
Why not???

Maybe because i am one of the less people that know git?

**Comment by DaMatrix** [comment]
I think everybody here knows git, or they wouldn't be using github for coding.

**Comment by inxomnyaa** [comment]
@DaMatrix oh, you wouldnt believe how many people use the desktop or web version of github to change and upload files.

**Comment by DefinitlyEvil** [comment]
c'mon ppl don't fight, peace

**Comment by DaMatrix** [comment]
:peace_symbol:

**Comment by TheDiamondYT1** [comment]
Fight. Fight. Fight.

**Comment by inxomnyaa** [comment]
@TheDiamondYT1 shut up
@DefinitlyEvil we don't. we collect facts
@DaMatrix ☮️
@TheDiamondYT1 stfu

**Comment by DefinitlyEvil** [comment]
@thebigsmileXD Enemy triple kill! 😝😝

**Comment by k-jiang** [comment]
On Linux, DragonProxy 1.2.13 is consuming 100% of a single core cpu power still. An event based system is a great idea. `while(1)` loop hurts performance in general no matter you have `sleep(x)` or not.

**Comment by HoverEpic** [comment]
The issue is known, wait for someone implements better command handler. Thanks for the report. Old but gold, how to notify old devs that we still exist and need there help <3

**Comment by SupremeMortal** [comment]
I'll take a look into this now and see what I can do.

**Comment by HoverEpic** [comment]
Problem seems being here : https://github.com/DragonetMC/DragonProxy/blob/master/proxy/src/main/java/org/dragonet/proxy/commands/ConsoleCommandReader.java

**Comment by SupremeMortal** [comment]
Would have thought Jline was used in this project instead of a basic scanner.

**Comment by whirvis** [comment]
I know JRakNet used to have this problem, it literally would use up to 99.9% of the CPU at all times, now it takes up less than 3% I believe when running a test. Does DragonProxy have any sleeps in its running loops? I haven't looked at the source code at all, but I would assume this is caused by an unending loop without any sleeps like ```Thread.sleep(0, 1);``` to slow it down and save CPU usage.

**Comment by HoverEpic** [comment]
ive fixed the command thread some weeks ago, forget to marks it as fixed (https://github.com/DragonetMC/DragonProxy/commit/2f176c8b9ced5e77c575c497b62b18b8709f17c5).
