### ISSUE TITLE
Server resetting sprinting?

### ISSUE THREAD

**Issue by lukeeey** [DragonetMC/DragonProxy#476]
Recently you are unable to sprint. If i comment out the following line, however, it works fine.
https://github.com/DragonetMC/DragonProxy/blob/5799187453de830e61d398c5d542b0ebeb7c5fbb/proxy/src/main/java/org/dragonet/proxy/network/translator/bedrock/player/PEPlayerActionTranslator.java#L66 

I also checked the sprinting metadata flag and that gets set back to false as soon as i start sprinting, so i tried commenting that out but it still stops me from sprinting unless i comment out the line above.

It's probably a simple issue but nevertheless an annoying one.

**Comment by Chew** [comment]
Is this fixed now?

**Comment by james090500** [comment]
Yes.
