### ISSUE TITLE
Random Speed

### ISSUE THREAD

**Issue by rahulc07** [DragonetMC/DragonProxy#478]
when I join in there is just random speed for about 20 seconds or indefinitely.  Also the server log says that were moving wrongly.  I am using spigot 1.15.2

**Comment by lukeeey** [comment]
Not entirely sure why this happens, but attempting to sprint (although sprinting doesn’t work?) will reset the speed

**Comment by lukeeey** [comment]
I think I have an idea how to fix it, but it’s almost 3 am

**Comment by lukeeey** [comment]
@xXTeraXx Please try the latest jenkins build and see if it is still happening

**Comment by lukeeey** [comment]
Closing due to lack of response, plus it seems to be fixed

**Comment by rahulc07** [comment]
Thanks it worked
