### ISSUE TITLE
how to run the proxy

### ISSUE THREAD

**Issue by eluternauer** [DragonetMC/DragonProxy#479]
i dont understand the config file and how to run the proxy. i cant find the server on my android.
please explain

**Comment by eluternauer** [comment]
![Anmerkung 2020-04-10 155309](https://user-images.githubusercontent.com/63459602/78995801-7a1d7e80-7b43-11ea-9c2c-6b6cd1f9e4f5.png)
thats what comes when i execute the jar command

**Comment by eluternauer** [comment]
what do i have to write then?

**Comment by lukeeey** [comment]
https://github.com/DragonetMC/DragonProxy/wiki/Editing-the-config

**Comment by james090500** [comment]
No response in 13 days. Closing
