### ISSUE TITLE
proxy is already running but unable to connect

### ISSUE THREAD

**Issue by MeowRay** [DragonetMC/DragonProxy#481]
os: centos 8
java: jdk 8 241

![QQ截图20200412225029](https://user-images.githubusercontent.com/29674595/79071812-480d4780-7d10-11ea-92d3-4ddce494d41f.jpg)

**Comment by lukeeey** [comment]
It says port 19132 is closed on the last image...you need to open it for UDP connections (unless you’re connecting from the same machine or local network, but it looks like it’s a VPS)

**Comment by MeowRay** [comment]
> It says port 19132 is closed on the last image...you need to open it for UDP connections (unless you’re connecting from the same machine or local network, but it looks like it’s a VPS)

No, it's just another session window

**Comment by MeowRay** [comment]
> It says port 19132 is closed on the last image...you need to open it for UDP connections (unless you’re connecting from the same machine or local network, but it looks like it’s a VPS)

Okay, bedrock works based on UDP .. I always thought it was TCP

**Comment by lukeeey** [comment]
Are you joining from the same machine or a device on your local network (like your phone)?

**Comment by james090500** [comment]
No response in 10 days. Closing
