### ISSUE TITLE
Unhandled Player Action: START_SWIMMING and STOP_SWIMMING

### ISSUE THREAD

**Issue by shawndewet** [DragonetMC/DragonProxy#482]
Hi guys.
Thanks for this project!  It has finally enabled me to get my kids connected from their devices to the MineOS server I set up at home.

I noticed in the DragonProxy log the following entries:
Unhandled Player Action: START_SWIMMING
Unhandled Player Action: STOP_SWIMMING

I understand this project is still under development and that this action will probably still make it into the nightly builds.  Just thought I'd put it on the radar though.

**Comment by lukeeey** [comment]
This will be fixed in the latest commit (when i push it)
