### ISSUE TITLE
Wall Climbing Bug

### ISSUE THREAD

**Issue by Kolya-Borisov** [DragonetMC/DragonProxy#483]
Just thought I would bring this up: While playing on bedrock, the bedrock players can "climb" vertical blocks similarly to a spider. I don't know what is causing the issue but while testing the server on my xbox and mobile device, the server almost lets them jump on the stacked blocks. I only noticed this with leaf blocks but I did not test other solid blocks.

**Comment by DjArt** [comment]
I have that issue too

**Comment by Chew** [comment]
Yep, I have this problem with stairs. Flying right on up!

**Comment by Kolya-Borisov** [comment]
@Chew I think you are reporting a seperate bug then the one I am describing. It is already on the TODO list for the bugged movement on slabs/stairs/carpets. The bug here is that the bedrock client can sometimes lag climb multiple blocks which should not be possible in Vanilla. Can't really narrow down the issue but it only occurs on a separate world within the server. Maybe my world guard plugin is causing the issue but I really don't know. EDIT: it just occurred within my regular world via jumping on barrier blocks.

**Comment by Chew** [comment]
That's what I'm saying. I have this in one x,z coord 

Stair
Stair
Stair

Not a flight of stairs, just 3 stairs on top of each other. I can climb up them

**Comment by Kolya-Borisov** [comment]
My apologies then, do you have an idea about what is causing the issue? I mean are you using plugins?

**Comment by james090500** [comment]
Stairs/Slabs/Carpet (Half Blocks) is a known issue.

Regarding climbing up trees. I've only had it happen once to me, so it hard to pin down. I'll look into it.

**Comment by Kolya-Borisov** [comment]
@james090500 I believe @Chew was describing the same issue I was having, I noticed this with stone bricks as well. It's hard to identify why it happens but I am able to repeatedly recreate the bug in my world (Here's a Java player looking at a bedrock player during the bug):
![Glitch](https://user-images.githubusercontent.com/62844138/79641366-1c052280-8165-11ea-9a47-c854ca6b023d.gif)
Note: The bedrock player is in survival. The only way I was able to render the player was when I temporarily stopped jumping on the bedrock account. For trees and other blocks, if I jump, I get stuck in the trees.

**Comment by Kolya-Borisov** [comment]
Appears the latest commit fixed this issue. I am no longer seeing this in my server.

**Comment by Kolya-Borisov** [comment]
@lukeeey it appears that I can still go through trees but only via half blocks. Fixing the half block issue will probably remove this bug. Try this set up:
![2020-04-19_10 37 06](https://user-images.githubusercontent.com/62844138/79690700-c3e42400-8229-11ea-9410-e23f4ebae020.png)
![2020-04-19_10 37 14](https://user-images.githubusercontent.com/62844138/79690701-c47cba80-8229-11ea-8ee0-e5a2479f16d2.png)
![2020-04-19_10 37 20](https://user-images.githubusercontent.com/62844138/79690704-c5ade780-8229-11ea-90dd-424e8ec49efe.png)
Sprint straight from the carpet and the bedrock player should be in the leaves

.

**Comment by lukeeey** [comment]
This will be fixed today

**Comment by Kolya-Borisov** [comment]
Great!
