### ISSUE TITLE
no gamemode c fly 

### ISSUE THREAD

**Issue by PixelcrafterEXE** [DragonetMC/DragonProxy#484]
if i download the newest version, i cant fly on the bedrock edition

**Comment by MinikPLayer** [comment]
For me sprinting also doesn't work

**Comment by lukeeey** [comment]
Flying also works fine?

**Comment by james090500** [comment]
Flying only works if you join a world whilst flying. If I switch to /gamemode survival, then back to /gamemode creative I can not fly. Double jumping does nothing.

**Comment by lukeeey** [comment]
What DragonProxy version are you running

**Comment by james090500** [comment]
0.4-SNAPSHOT build 294 I believe...

(Could really do with a /version command 😉 )

**Comment by lukeeey** [comment]
It shows the version when you start it up but ill add support for showing the git commit at some point

**Comment by lukeeey** [comment]
What server software are you using and what version?

**Comment by lukeeey** [comment]
https://streamable.com/yr8qju

**Comment by james090500** [comment]
> What server software are you using and what version?

That's weird then. The setup we have is the dragon proxy infront of a waterfall proxy which connect to 3 sub-server running PaperMC. I have just tested and still not working. Will try grab a video but my internet speed isn't great. I can get you on the server to test if you want to DM me in discord as I dont want to advertise here in an issue comment

james090500#0001

**Comment by james090500** [comment]
It appear flying works for some people but not others. @MinikPLayer @PixelcrafterEXE please let us know your current proxy/server setups? 

As seen here lukeeey can fly but I can't. 

https://streamable.com/z4kcfr

**Comment by MinikPLayer** [comment]
Same version, 0.4 build 294 with PaperMC 1.15.2 version 80. Can't fly and sprint

**Comment by lukeeey** [comment]
Sprinting is known but flying should work

**Comment by thaggren** [comment]
Flying is not working for me either on 0.4-SNAPSHOT :(

**Comment by james090500** [comment]
> Flying is not working for me either on 0.4-SNAPSHOT :(

Please let us know your current setup and steps to replicate the issue.

**Comment by thaggren** [comment]
Server: Windows 10, Java 8.0.2510.8, DragonProxy 0.4-SNAPSHOT, McMyAdmin 2.7.1.4
Client: Windows 10, Bedrock Edition 1.14.20
Create new world, connect and no option to fly. Java Edition users can fly.

**Comment by lukeeey** [comment]
Fixed in the latest build. It worked for me because i was using an outdated MCProtcolLib locally.
