### ISSUE TITLE
Invisable players

### ISSUE THREAD

**Issue by PixelcrafterEXE** [DragonetMC/DragonProxy#485]
the java edition client can see the bedrock editions, but with the bedrock client i can't see any java player

**Comment by NotN33d3d** [comment]
I confirm this Java can see bedrock. Bedrock cannot see java. Bedrock can hit java

**Comment by lukeeey** [comment]
It works fine for me

**Comment by james090500** [comment]
Sometimes Bedrock can see java players, some times not. If I switch servers or TP to people outside of unloaded chunks sometimes players are invisible. Also sometimes bedrock players can not see other bedrock players.

**Comment by lukeeey** [comment]
Now thats a better description. Thank you @james090500

**Comment by Kolya-Borisov** [comment]
I found that if the bedrock client logs out and logs back in, the java player could be seen but only if the java player was around the starting chunk loading that occurs when logging in.
