### ISSUE TITLE
Changing worlds doesn't update weather

### ISSUE THREAD

**Issue by james090500** [DragonetMC/DragonProxy#487]
This also effects different server.

/server1 is raining and /server2 is not raining. If I join /server1 then go back to /server2 it will be raining on server2, until I force update weather with /weather storm then /weather sun. This only affects storm and not sunny weather.

**Comment by Kolya-Borisov** [comment]
For my server at least, the java players will see sunny weather but the bedrock players will sometimes see the server as rainy.
