### ISSUE TITLE
Skin's aren't display correctly

### ISSUE THREAD

**Issue by james090500** [DragonetMC/DragonProxy#488]
Player with Alex skins will have invisible arms. Also Bedrock player skins have all layers (hats, legs etc) disabled so will appear "flat"

What me (Bedrock) see's a Java Alex skin
![image](https://user-images.githubusercontent.com/20372645/79399098-4e9ef780-7f7a-11ea-8e89-e22e955e28e3.png)

Java seeing me (bedrock):

What they see:
https://cdn.discordapp.com/attachments/671032951626268693/700127736718688297/IMG_20200416_003719.jpg

What they should see:
https://namemc.com/profile/james090500.2

**Comment by Kolya-Borisov** [comment]
How were you able to fetch skins? Are you putting your server on online mode?

**Comment by lukeeey** [comment]
That would probably work @Kolya-Borisov , also theres a config setting

**Comment by Kolya-Borisov** [comment]
What is the config setting? I couldn't figure out how to bypass the authentication key for online mode even when I shut it off. The system just prints out that the key cannot be null or empty.

**Comment by lukeeey** [comment]
You can't bypass online mode unless you set the server to offline mode

**Comment by james090500** [comment]
> What is the config setting? I couldn't figure out how to bypass the authentication key for online mode even when I shut it off. The system just prints out that the key cannot be null or empty.

All my servers are in online mode. Hence skins

**Comment by Kolya-Borisov** [comment]
Ok, that answers my question though is it possible to make an authentication key for online mode?

**Comment by james090500** [comment]
DragonProxy and the java server both need to be in online mode. Otherwise you will get the auth error

**Comment by Kolya-Borisov** [comment]
How would you get the DragonProxy into online mode? Is it in the config file? All I see is my remote authentication switched to offline.

**Comment by james090500** [comment]
> How would you get the DragonProxy into online mode? Is it in the config file? All I see is my remote authentication switched to offline.

This isnt the place for help. Use discord next time.

remote-auth: credentials
