### ISSUE TITLE
Unable to craft

### ISSUE THREAD

**Issue by marcohoovy** [DragonetMC/DragonProxy#495]
![dragonbug](https://user-images.githubusercontent.com/26121378/79604450-01d82f80-80e6-11ea-8f5c-871b85b14aea.png)

Unable to craft, the tools show are given too u by the server

**Comment by joaquinv98** [comment]
when will it be fixed?

**Comment by Elapy** [comment]
> when will it be fixed?

It most likely will never be fixed. DragonProxy is disbanded. The current developers have transitioned to https://geysermc.org there's more info on #announcements on the Dragonet discord server. The link to the GeyserMC discord server is in the website I sent you. :)

**Comment by CombedKnight4** [comment]
Please tell me when it will be fixed. Sorry if I'm rushing you but without crafting, survival won't be the same.

**Comment by CombedKnight4** [comment]
Also is crafting in the dragon proxy rewrite?

**Comment by lukeeey** [comment]
Excuse me I take issue to you advertising on my repo

**Comment by Elapy** [comment]
What DragonProxy rewrite. Bugs won’t be fixed because the project is abandoned.

**Comment by lukeeey** [comment]
The rewrite is the main branch

**Comment by marcohoovy** [comment]
I apologise for advertising here. I believe I have removed my comment, also I am unsure if I should of closed the issue

**Comment by lukeeey** [comment]
It’s okay

**Comment by lukeeey** [comment]
I was joking earlier

**Comment by marcohoovy** [comment]
oh lol my bad

**Comment by CombedKnight4** [comment]
Does "the other thing" have crafting?

**Comment by marcohoovy** [comment]
yes I believe it does
