### ISSUE TITLE
Water Rendering

### ISSUE THREAD

**Issue by Kolya-Borisov** [DragonetMC/DragonProxy#497]
Weird rendering of seagrass and coral where the plants reside in air. If you go inside the air gaps it is as if there is no water present. (Only tested on Mobile)

![IMG_0013](https://user-images.githubusercontent.com/62844138/79620413-ce91a280-80dd-11ea-8377-83a20ce740b6.PNG)

**Comment by lukeeey** [comment]
This should be an easy fix, I’ll do it tomorrow

**Comment by lukeeey** [comment]
The bubbles issue should have been fixed recently so make sure you’re updated

**Comment by Kolya-Borisov** [comment]
I removed the bubbles comment.

**Comment by Kolya-Borisov** [comment]
Resolved in latest commit.
