### ISSUE TITLE
Can't see pc player

### ISSUE THREAD

**Issue by nixerg** [DragonetMC/DragonProxy#498]
Hi,
The server is Spigot v.1.15.2, using current Proxy v.0.4, on the pad I have PE v.1.14.
PC player sees PE player but PE player can't see a PC player.

**Comment by Kolya-Borisov** [comment]
Issue #485 already reported a similar bug. It seems that it has been fixed in the newest update.

**Comment by lukeeey** [comment]
It was only fixed to an extent apparently

**Comment by nixerg** [comment]
It seems so, I have taken proxy just two days ago

**Comment by lukeeey** [comment]
I only fixed the issue 14 hours ago

**Comment by nixerg** [comment]
ok) I will try it

**Comment by nixerg** [comment]
It works ok, they see each other now, thanks, that was quick.

Not a problem but I noticed these lines in the proxy log (I have a turtle nearby)
[20:09:54 INFO]: No mapping for sound: ENTITY_TURTLE_AMBIENT_LAND
[20:09:59 INFO]: No mapping for sound: ENTITY_TURTLE_SHAMBLE
[20:10:10 INFO]: No mapping for sound: ENTITY_TURTLE_AMBIENT_LAND

**Comment by lukeeey** [comment]
Ill work on that at some point

**Comment by nixerg** [comment]
Should I close the issue?

**Comment by Chew** [comment]
If the initial issue is resolved, then yes. If you have additional issues open another issue for them
