### ISSUE TITLE
I see flying cows now !

### ISSUE THREAD

**Issue by jlirochon** [DragonetMC/DragonProxy#5]
I see flying rabbits, pigs and cows. All seems to jump at the same time, which makes me think we don't know which one is actually jumping. They all jump at different heights though (but still very high as said in #3)

**Comment by DefinitlyEvil** [comment]
Entity tied together??

**Comment by jlirochon** [comment]
On vertical axis it seems so

**Comment by DefinitlyEvil** [comment]
Or maybe because I applied velocity every tick is a wrong move.
