### ISSUE TITLE
Custom Name Color

### ISSUE THREAD

**Issue by Kolya-Borisov** [DragonetMC/DragonProxy#500]
I checked the TODO list but didn't see this issue being brought up: I don't play bedrock a lot but I noticed Custom Names for armorstands don't have color(only appear white). I checked other servers and sure enough Custom Names for entities have color. This is only visible to bedrock players while the Java players can see the custom name color.

**Comment by lukeeey** [comment]
Please try the latest commit

**Comment by Kolya-Borisov** [comment]
Will do

**Comment by Kolya-Borisov** [comment]
Appears to be working. Thanks!
