### ISSUE TITLE
Time Difference #2

### ISSUE THREAD

**Issue by Kolya-Borisov** [DragonetMC/DragonProxy#509]
Similar to my previous issue that I closed but I have to manually debug the /gamerule for every world in my server. Example: If the world is supposed to be dusk and I do /gamerule so the bedrockplayer would see the correct time (they see dawn), the first world in the server will no longer be the correct time (From the viewpoint of the bedrock player it should be noon not dusk).

**Comment by Kolya-Borisov** [comment]
Logging out and back in fixes this issue for the first world but when you join the second world and reenter the first world, it is the wrong time. First world is noon > Second world is dusk > First world becomes dusk.

**Comment by lukeeey** [comment]
I may have an idea on how to fix it
