### ISSUE TITLE
Were can I find build ? drone.io not working

### ISSUE THREAD

**Issue by Aang23** [DragonetMC/DragonProxy#51]
I can't build from source, and i can't download builds... Can you help me about that ?

**Comment by DaMatrix** [comment]
It can't do anything yet anyway other than start up and shut down, there's no reason to use this project right now

**Comment by TheDiamondYT1** [comment]
You can find it in the target directory after compiling 😂

**Comment by Aang23** [comment]
I know that, I'm not a maven noob... The code look like broken, I have unexplained errors in the logs when compiling.

**Comment by TheDiamondYT1** [comment]
OK well it's still in development and not suitable to be used get..

**Comment by TheDiamondYT1** [comment]
Yet*

**Comment by Aang23** [comment]
Ok, I wil try to fix the errors, or going to try to get on old build from one of my HDD...
