### ISSUE TITLE
Demo server in China

### ISSUE THREAD

**Issue by PonyPC** [DragonetMC/DragonProxy#51]
I'm a host of Minecraft in China, we offer desktop and pocket version host rent.
We provider user to select more than 80 different version of server cores from 1.4.x to 1.8.x, such as Spigot, PaperSpigot, Cauldron, MCPC+, KCauldron, minecraft_server,minecraft_server with forge,bukkit,BungeeCord,KBungeeCord,Craftbukkit, PM0.10.x,PM0.11.x,PM0.12.x, etc.

We saw that you want a China demo server, at the same time, we want to find a better performance and plugin environment than PocketMine. 

So we want to provider you a long time demo server of your contribution for minecraft pocket edition.

Great job dude.

you can email me: a#nide8.com,  and http://nide8.com is our host homepage, we make greater panel than Multi-craft.

**Comment by DefinitlyEvil** [comment]
Contacting...

**Comment by RandomAltThingy** [comment]
Why close

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy Already contacted via OICQ.
