### ISSUE TITLE
Bungeecord Server Movement Causes Crashes.

### ISSUE THREAD

**Issue by Navoei** [DragonetMC/DragonProxy#516]
Well, the title says it all. When you use DragonProxy to connect to a bungeecord server and try to move from a server to another (say from the hub to a mini games server), the game immediately crashes.

**Comment by lukeeey** [comment]
More info would be nice.

Is there any enchanted items on the target server?

**Comment by Navoei** [comment]
Yes there is enchanted items on the target server.

**Comment by lukeeey** [comment]
Try removing them and see if the issue persists

**Comment by james090500** [comment]
Closing as no response
