### ISSUE TITLE
Invisible players (again)

### ISSUE THREAD

**Issue by Kolya-Borisov** [DragonetMC/DragonProxy#525]
Bedrock players can only see Java players only if they are in the same world when they log in. Example: if bedrock player is in world 1 and the Java player is in world 2, when the bedrock player joins world 2 or vise versa (Java player joins world 1), the Java player is not visible to the bedrock player. However, once the bedrock client logs out and back in with the Java player in the same world, the issue is fixed. Also if the players go into another world then the one they are in, they can still see each other (Assuming that they saw each other in the previous world).

**Comment by Kolya-Borisov** [comment]
Just downloaded the latest build from Jenkins and players cannot see each other even if they log out and back in.

**Comment by lukeeey** [comment]
I haven’t changed anything tho

**Comment by Kolya-Borisov** [comment]
I really don't know, maybe my plugins are interfering somehow?

**Comment by lukeeey** [comment]
Please try the latest build

**Comment by Kolya-Borisov** [comment]
Will do

**Comment by Kolya-Borisov** [comment]
Players can now see each other but the original issue is still there. (Multiworld visibility)

**Comment by james090500** [comment]
closed #550
