### ISSUE TITLE
/title Coloring

### ISSUE THREAD

**Issue by Kolya-Borisov** [DragonetMC/DragonProxy#526]
Really small issue: if I do the command on Java /title [player] title "test" to a bedrock player, the title appears black for whatever reason (should appear white). Can be easily resolved if I add nbt data:  /title [players] title {"text":"test","color":"white"}. Again, very minor bug that probably will not affect 99.9% of people using this proxy.

**Comment by lukeeey** [comment]
This should work perfectly?

**Comment by Kolya-Borisov** [comment]
With the nbt data yes

**Comment by Kolya-Borisov** [comment]
but with the short hand /title it just turns black

**Comment by Kolya-Borisov** [comment]
Github left the player out of the command. It should work now. (Exclude brackets)

**Comment by lukeeey** [comment]
Fixed in #530
