### ISSUE TITLE
Geyser is better than this shit

### ISSUE THREAD

**Issue by ghost** [DragonetMC/DragonProxy#527]
https://github.com/GeyserMC/Geyser

And have a much better developer than this lukeey :)

have a good server guys

**Comment by lukeeey** [comment]
I warned @DoctorMacc about you already. Hopefully this serves as proof. Have a nice day, dickhead 😄

**Comment by Camotoy** [comment]
No need to diss on this project or the developer!

Keep up the good work, DP.

**Comment by ghost** [comment]
not really good work, code sucks but ok

**Comment by lukeeey** [comment]
You know nothing about good code - i've seen your code.

Here's a few examples to humor the readers of this post:

* https://github.com/NycuRO/DonateInfo/blob/master/src/main/java/nycuro/MainClass.java
* https://github.com/NycuRO/OpenInv-MCPE/blob/master/src/main/OpenInv/OpenInv.java
https://github.com/NycuRO/CoronaAddon-Nukkit/blob/master/src/main/java/nycuro/Loader.java

I must say, i am a BIG fan of your indentation style! 
![image](https://user-images.githubusercontent.com/32024335/80228628-30568d00-8647-11ea-8b49-3b29556db3af.png)
Perfection!

Hmm...this is a very useful plugin
![image](https://user-images.githubusercontent.com/32024335/80228728-50864c00-8647-11ea-8f16-daf43c407dc7.png)

I love all this unneeded code! https://github.com/NycuRO/CoronaAddon-Nukkit/blob/master/src/main/java/nycuro/Loader.java

---

Here we can see NycuRO's alt account (i can vouch for this) 
(https://github.com/ClearSkyTeam/ClearSky/pull/687)
![image](https://user-images.githubusercontent.com/32024335/80229035-c5f21c80-8647-11ea-8a57-a2ae0e163e5b.png)
You've got to love the quality of the code there! 

Remember the time you also spam botted the pmmp repo?

**Comment by lukeeey** [comment]
Please, i challenge you to make a good contribution to Geyser and i will discuss it with the team and see if it is good or not

**Comment by WesleyVanNeck** [comment]
tbh lukeeey does good job at it to also why make such issue why do :/

**Comment by Chew** [comment]
bro the real issue is u

**Comment by Kolya-Borisov** [comment]
He is probably insecure about how much Gyser sucks so he has to diss dragon proxy to make himself fell better.

**Comment by lukeeey** [comment]
@Kolya-Borisov there's no need to diss Geyser... Legacy and DoctorMacc are both Geyser contributors defending me lol

**Comment by Kolya-Borisov** [comment]
O shoot my bad

**Comment by Chew** [comment]
Geyser and DragonProxy are both things that exist, they do the same thing in different ways. Matter of preference but no need to hate on the other one because "different bad"

**Comment by Kolya-Borisov** [comment]
What's the difference anyways? Are both Gyser and DragonProxy doing the samething?

**Comment by Chew** [comment]
Like I said, they're both Bedrock -> Java proxies, they just handle it differently

**Comment by lukeeey** [comment]
Geyser has features DragonProxy doesn't, DragonProxy has features and bug fixes Geyser doesn't. It's as simple as that.

**Comment by Kolya-Borisov** [comment]
Ah ok

**Comment by rmellis** [comment]
NycuRO is just being a compleate asshole
DragonProxy still works great for what it is and gets better each update
