### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Kolya-Borisov** [DragonetMC/DragonProxy#528]
Is is possible to have the server online (in order to have skins) and remote authentication offline? When I try logging in it says the authentication key cannot be null or empty. Is this intended or does this have to do with something else i'm not getting?

**Comment by lukeeey** [comment]
That message is from the remote server because when the server is in online mode it checks to make the client is logged in with a valid java account

**Comment by Kolya-Borisov** [comment]
Oh ok. So bedrock technically does not have a valid account?

**Comment by Kolya-Borisov** [comment]
Any way to disable it other than what I described? (putting it into offline mode)

**Comment by Kolya-Borisov** [comment]
I guess my question is if there is a way to keep the server into online mode but not have the valid Java account check for the bedrock players?

**Comment by james090500** [comment]
No, because otherwise players could join bedrock as say your username and then take over your server. 

We are working on a plugin like this at the moment

**Comment by Kolya-Borisov** [comment]
That makes a lot more sense, but how would switching to offline mode for both the server and authentication key avoid that issue?

**Comment by james090500** [comment]
It doesn't. But it resolves the original issue.

**Comment by Kolya-Borisov** [comment]
Oh ok thanks.
