### ISSUE TITLE
Where do I do the java -jar DragonProxy.jar Command?

### ISSUE THREAD

**Issue by tufcat13** [DragonetMC/DragonProxy#529]
I don't know where to do the command, so the plugin won't activate.  I tried typing it in my server console, but it just said unknown command.  Where do I put the command in?

**Comment by Kolya-Borisov** [comment]
What's your operating system?

**Comment by james090500** [comment]
As this was discussed on discord I am closing the issue. For reference:

If you're on windows, make a .bat script in the same directory as your dragonproxy.jar
```
java -jar DragonProxy.jar
pause
```
