### ISSUE TITLE
Can the latest dragonet support the latest version of MCPE?

### ISSUE THREAD

**Issue by uwni** [DragonetMC/DragonProxy#53]
the problem is what the title say

**Comment by DaMatrix** [comment]
The latest DragonProxy can't do anything, and the one version that could do something doesn't exist because the repo was reset.

**Comment by uwni** [comment]
When will I get an useful version?

**Comment by DaMatrix** [comment]
Probably never, PC and PE are too different from a networking perspective to make this practical anyway. If you're looking at hosting a server, look at the `mcpenew` branch on ProtocolSupport (a Spigot plugin).
