### ISSUE TITLE
Spaces in bedrock names.

### ISSUE THREAD

**Issue by Navoei** [DragonetMC/DragonProxy#532]
This is not necessarily an issue, but more of a request. 
It might be an issue on some server though. 
Bedrock clients can have spaces in their name. This can cause severe issues in Java servers where spaces signify the start of a new argument in a command. 
For example, the command '/ban Navoei MC' would not work because the username 'Navoei MC' has a space in it.

**Comment by Chew** [comment]
Duplicate of #255

**Comment by Chew** [comment]
Although I don't know why that one was closed

**Comment by lukeeey** [comment]
It was from 2018

**Comment by james090500** [comment]
Does java even allow players with spaces to connect?

**Comment by Chew** [comment]
can check

**Comment by Chew** [comment]
Yes actually, on offline servers

**Comment by Chew** [comment]
Problem is they're invincible, you can't ban or do anything with them

**Comment by james090500** [comment]
That sounds like a minecraft bug then. Players should be stopped having invalid usernames on java side

**Comment by Chew** [comment]
I made an issue for it https://bugs.mojang.com/browse/MC-180850 but I doubt they'll fix it

**Comment by KanekiOnMC** [comment]
No don't Worry they are not really invicible, you can use that ""
example: /ban "Good Nickname", and not /ban Good Nickname
That option is already in Minecraft Bedrock Edition and Minecraft Java Edition

**Comment by lukeeey** [comment]
I don’t get how people don’t know that

**Comment by james090500** [comment]
Due to the fact this should be handled on Java's side to stop connection with spaces I am closing this issue.
