### ISSUE TITLE
if server player count says the server is full, you can't join

### ISSUE THREAD

**Issue by ayunami2000** [DragonetMC/DragonProxy#534]
You can still join if the server player count and motd haven't loaded yet.
![image](https://user-images.githubusercontent.com/24785136/80423123-69903680-88ad-11ea-9a26-2b7bb1518309.png)

**Comment by lukeeey** [comment]
I thought I fixed this

**Comment by lukeeey** [comment]
Oops, @james090500 changed it

**Comment by ayunami2000** [comment]
oh yeah i was using the release from github not the jenkins build

**Comment by lukeeey** [comment]
Use the latest jenkins build
