### ISSUE TITLE
ANYONE CAN FIX BUILD ERROR?

### ISSUE THREAD

**Issue by ghost** [DragonetMC/DragonProxy#54]
[ERROR] Failed to execute goal on project DragonProxy: Could not resolve dependencies for project org.dragonet.proxy:DragonProxy:jar:0.0.7: Failed to collect dependencies at org.spacehq:mcprotocollib:jar:1.11.2-SNAPSHOT: Failed to read artifact descriptor for org.spacehq:mcprotocollib:jar:1.11.2-SNAPSHOT: Could not transfer artifact org.spacehq:mcprotocollib:pom:1.11.2-SNAPSHOT from/to spacehq (https://repo.spacehq.org/content/repositories/snapshots/): Received fatal alert: internal_error -> [Help 1]

ANYONE CAN FIX?

You put "Donate Button". Ok, you know anyone not donate for one "non-worker" project?

**Comment by TheDiamondYT1** [comment]
Kicked by admin. Reason: caps.

**Comment by ghost** [comment]
Wow, very well. I report one problem and  "kicked by admin". -_-

**Comment by TheDiamondYT1** [comment]
haha this is a known problem and the README states its not ready for use

**Comment by DaMatrix** [comment]
Blame spacehq for breaking their buildserver.

**Comment by DefinitlyEvil** [comment]
why not hosting a mirror somewhere?

**Comment by DaMatrix** [comment]
I could, I'd need to know what files are needed to host a maven repo. I got an underused VPS with 1Gbps up/down, and wouldn't mind mirroring that.

**Comment by DefinitlyEvil** [comment]
@DaMatrix ask Google

**Comment by TheDiamondYT1** [comment]
Yoou can host a maven repo from a github repo lmao

See https://github.com/thediamondyt1/repo.thediamondyt.tk

**Comment by DaMatrix** [comment]
oh lol, i'll just clone that and use it then kek

**Comment by TheDiamondYT1** [comment]
Then just use https://raw.githubusercontent.com/TheDiamondYT1/repo.thediamondyt.tk/master/snapchats (but replace repo with ur own) to access the repo.

**Comment by ghost** [comment]
Ok, anyone can fix?
