### ISSUE TITLE
Allow MOTD editing.

### ISSUE THREAD

**Issue by MrPowerGamerBR** [DragonetMC/DragonProxy#54]
Allow users to edit the MCPE server list message on the config instead of storing the message on the  language file.

**Comment by RandomAltThingy** [comment]
It's in the language file so it can be shown in different languages depending on the users choice.

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy however, wouldn't it be more convenient to be on the config file? Because, you know, the Minecraft PC server list message isn't stored on a language file.

**Comment by TekkitCommando** [comment]
Simply add some code that can allow you to change the message in config. Obviously if say someone that speaks Japanese is editing it from see mc servers they would know what an motd was and would put the motd message in their language anyway.

**Comment by TekkitCommando** [comment]
And if you want it by default to be there language, when you choose the language have a method that checks the chosen language and changes the default message to their language.

**Comment by TekkitCommando** [comment]
They can then still go in the config and change it

**Comment by TekkitCommando** [comment]
I spend nearly $350/month on severs and dragonet uses like 2 of them, we need to try to comply with what users want or the money is going to waste. @RandomAltThing

**Comment by TekkitCommando** [comment]
Also I may have sounded a little rude so sorry :P

**Comment by RandomAltThingy** [comment]
@TekkitCommando Lmao why can't Dragonet use 1 of them for multiple things? Also i am planning on creating mcpe-clans.com where clans can register, update status, post screenshots, post all the members and their info and have a chat area so the clan can chat then I may make an app for chatting after that. But we don't have a Linux vps not even a cheap $5 one :(

**Comment by TekkitCommando** [comment]
I may be able to help you out, we can talk about it on skype sometime

**Comment by RandomAltThingy** [comment]
@TekkitCommando Now? My internet will run out soon I will need to topup later.

**Comment by TekkitCommando** [comment]
If you are asking if we can discuss it now then sure, what's your Skype xD

**Comment by RandomAltThingy** [comment]
goldowl_37

I can only do messages right now

**Comment by TekkitCommando** [comment]
Alright added you.

**Comment by TekkitCommando** [comment]
@MrPowerGamerBR I agree with you on this issue and I'm sure it will be worked on soon enough

**Comment by MrPowerGamerBR** [comment]
@TekkitCommando I'm already doing a pull request for this.

**Comment by TekkitCommando** [comment]
@MrPowerGamerBR oh ok fancy :P

**Comment by MrPowerGamerBR** [comment]
Pull request made: #57

**Comment by MrPowerGamerBR** [comment]
Pull request pulled by @RandomAltThingy , closing the issue.
