### ISSUE TITLE
NPC Rendering

### ISSUE THREAD

**Issue by KatyaBorisova** [DragonetMC/DragonProxy#541]
NPC's in the lobby won't render in. It is one of the only plugins I use that doesn't quite work for Bedrock players. Although the command is executed when clicking where the NPC is supposed to be (using CommandNPC), the NPC itself is nowhere to be found.

**Comment by lukeeey** [comment]
This was fixed recently - are you using the latest build from jenkins or from the release section?

**Comment by KatyaBorisova** [comment]
Will update
