### ISSUE TITLE
Obfuscated Chat Characters

### ISSUE THREAD

**Issue by Kolya-Borisov** [DragonetMC/DragonProxy#542]
Another very minor issue: The bedrock client can't see obfuscated chat characters. In titles for example, the bedrock client registers the appropriate characters but for whatever reason I were to use those characters in the chat, the client can't see it.

**Comment by lukeeey** [comment]
can i see a screenshot?

**Comment by Kolya-Borisov** [comment]
Java:
![2020-04-29_16 39 46](https://user-images.githubusercontent.com/62844138/80644831-49d94980-8a38-11ea-840a-3e8847cd7c68.png)
Bedrock:
![IMG_0025](https://user-images.githubusercontent.com/62844138/80644872-5bbaec80-8a38-11ea-9b47-46e09ffa504f.PNG)
Edit: I am using a plugin for the chat modification but you can also see this issue if you have a nickname, prefix, or suffix when you are on a team.

**Comment by lukeeey** [comment]
That doesn’t look like your usual character set. Bedrock doesn’t like most characters other than the usual symbols you find on your keyboard and a few others of course

**Comment by Kolya-Borisov** [comment]
The bedrock client can see titles properly but that might be different. For example I can do /title @p title {"text":"test","obfuscated":"true"} and the bedrock client would see the characters correctly.

**Comment by james090500** [comment]
> That doesn’t look like your usual character set. Bedrock doesn’t like most characters other than the usual symbols you find on your keyboard and a few others of course

He's using &k in chat to obsofucate.

**Comment by ghost** [comment]
@Kolya-Borisov You have to change the chat's font to "Mojangles" by going into the chat, clicking the cog wheel, and changing the font there.

**Comment by james090500** [comment]
This is an issue with the font. When the font is Mojangles:
![image](https://user-images.githubusercontent.com/20372645/80920093-7e654200-8d65-11ea-844d-e6949124a6a0.png)
When the font is noto sans:
![image](https://user-images.githubusercontent.com/20372645/80920103-891fd700-8d65-11ea-9fad-c6d4130a85b7.png)

Basically, you need to change your font.

**Comment by lukeeey** [comment]
Noto sans should not exist and should NOT BE DEFAULT

**Comment by Kolya-Borisov** [comment]
Can someone explain to me the font change on for example a phone?

**Comment by james090500** [comment]
Open chat, click settings, change font type.

![Screenshot_20200503-210421](https://user-images.githubusercontent.com/20372645/80924618-da3dc400-8d81-11ea-91f1-8d5ef197eefa.png)

**Comment by Kolya-Borisov** [comment]
ah ok cool
