### ISSUE TITLE
Mineplex PE

### ISSUE THREAD

**Issue by ghost** [DragonetMC/DragonProxy#55]
Mineplex pe is running drgonet proxy?

**Comment by DaMatrix** [comment]
No. DragonProxy can't do anything yet, and mineplex pe is a completely different server than the pc one.

**Comment by TheDiamondYT1** [comment]
I think he is talking about the repo description "Yes, even mineplex.".

This was referring to the PC Mineplex server. You could connect to it when this software was *working*, but obviously you can't now.

**Comment by DaMatrix** [comment]
The problem is that the readme conveys the meaning that DragonProxy IS working, even though it hasn't worked for months.

**Comment by DefinitlyEvil** [comment]
lol so convincing 😝
