### ISSUE TITLE
Maven Build Error

### ISSUE THREAD

**Issue by Raphtalia074** [DragonetMC/DragonProxy#557]
When I do "mvn package"

[INFO] ------------------------------------------------------------------------                 [INFO] Building DragonProxy 0.4-SNAPSHOT        [INFO] ------------------------------------------------------------------------                 [INFO]                                                                                          [INFO] ------------------------------------------------------------------------                 [INFO] Building dragonproxy 0.4-SNAPSHOT        [INFO] ------------------------------------------------------------------------                 Downloading: https://repo.nukkitx.com/snapshot/com/nukkitx/protocol/parent/2.5.6-SNAPSHOT/parent-2.5.6-20200523.214425-10.pom                   [INFO] ------------------------------------------------------------------------                 [INFO] Reactor Summary:                         [INFO]                                          [INFO] DragonProxy ........................................ SUCCESS [  0.003 s]                 [INFO] dragonproxy ........................................ FAILURE [  2.251 s]                 [INFO] dragonproxy-bootstrap .............................. SKIPPED                             [INFO] bootstrap-standalone ............................... SKIPPED                             [INFO] bootstrap-bukkit ................................... SKIPPED                             [INFO] ------------------------------------------------------------------------                 [INFO] BUILD FAILURE                            [INFO] ------------------------------------------------------------------------                 [INFO] Total time: 2.650 s                      [INFO] Finished at: 2020-05-29T16:56:05+03:00   [INFO] Final Memory: 11M/31M                    [INFO] ------------------------------------------------------------------------                 [ERROR] Failed to execute goal on project dragonproxy: Could not resolve dependencies for project org.dragonet.proxy:dragonproxy:jar:0.4-SNAPSHOT: Failed to collect dependencies at com.nukkitx.protocol:bedrock-v390:jar:2.5.6-SNAPSHOT: Failed to read artifact descriptor for com.nukkitx.protocol:bedrock-v390:jar:2.5.6-SNAPSHOT: Could not transfer artifact com.nukkitx.protocol:parent:pom:2.5.6-20200523.214425-10 from/to nukkitx-repo (https://repo.nukkitx.com/snapshot/): Failed to transfer file: https://repo.nukkitx.com/snapshot/com/nukkitx/protocol/parent/2.5.6-SNAPSHOT/parent-2.5.6-20200523.214425-10.pom. Return code is: 500 , ReasonPhrase:Internal Server Error. -> [Help 1]                                        [ERROR]                                         [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.             [ERROR] Re-run Maven using the -X switch to enable full debug logging.                          [ERROR]                                         [ERROR] For more information about the errors and possible solutions, please read the following articles:                                       [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException [ERROR]                                         [ERROR] After correcting the problems, you can resume the build with the command                [ERROR]   mvn <goals> -rf :dragonproxy

**Comment by Tim203** [comment]
I have no clue why Luke has no longer labeled the repo as archived, but DragonProxy has been merged into [Geyser](https://github.com/GeyserMC/Geyser) so use Geyser instead.

**Comment by Raphtalia074** [comment]
Thanks for help. I try to use it.
