### ISSUE TITLE
Noooooo

### ISSUE THREAD

**Issue by Lord-Felidae** [DragonetMC/DragonProxy#56]
Tell me what's wrong with the code. I'll try to fork it and (likely unsuccessfully) fix it. Most likely, you'll close the issue, so go ahead

**Comment by TheDiamondYT1** [comment]
I have no idea whats wrong. If we want to do this, in my own opinion, it would need a complete rewrite.

**Comment by Lord-Felidae** [comment]
Great. Now there's nothing I can do. I've never written anything from scratch. I'll just surf the code for now.

**Comment by TheDiamondYT1** [comment]
Ok i woud  try and rewrite it but i never have access to my pc :(

**Comment by Lord-Felidae** [comment]
Right now, all I have is my iPhone, and it's a pain to code on a mobile device.

**Comment by TheDiamondYT1** [comment]
I use a kindle fire hd 8

**Comment by Lord-Felidae** [comment]
That's better than an iPhone when using GitHub

**Comment by Lord-Felidae** [comment]
Aw, forget it. I could never fix DragonProxy

**Comment by DaMatrix** [comment]
Nobody can, it's literally a mess. Use ProtocolSupportPE, it's only been in development for a week and already works as well as DragonProxy when it was at the peak of it's development.

**Comment by DefinitlyEvil** [comment]
@DaMatrix You gotta use caches as I did for entities.

**Comment by DaMatrix** [comment]
@DefinitlyEvil ...or you can use Spigot's entity movement tracker :P

**Comment by Lord-Felidae** [comment]
It feels horrible to be inferior to other things right now. :(

**Comment by DefinitlyEvil** [comment]
@DaMatrix it's been a long time since I last time playin around with Minecraft haha, I am out of style now.

**Comment by Lord-Felidae** [comment]
I do it all the time, except right now I'm on vacation XD

**Comment by Lord-Felidae** [comment]
@definitelyevil tell me the latest versions that it supports, and I'll try to do a thorough test of it.
