### ISSUE TITLE
Add a option in the config file to show the number of players connected to the PC server.

### ISSUE THREAD

**Issue by MrPowerGamerBR** [DragonetMC/DragonProxy#58]
Instead of showing the players connected to the proxy, this new option could show the connected players to the PC server.

**Comment by RandomAltThingy** [comment]
This can be done somehow or just use MinecraftAPI.com. I know how to add it, but you need to add PHP code. There may be a way to do it in java

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy 

1. Send a Server Status Packet to the PC Server
2. Get the Online Players/Max Players
3. Change the Slots on the Proxy
4. Be happy.

Or you could use a external API, as you said, but making the proxy handle everything without depending on external assets is the better way in my opinion.

**Comment by RandomAltThingy** [comment]
@DefinitlyEvil Can you make a team called "admins" and add me with admin access so I can manage other repos, people etc? I can't do anything such as delete the org as I won't have owner access.

**Comment by MrPowerGamerBR** [comment]
DragonProxy uses MCProtocolLib, right? Just use it to ping, there is even a example for that on the MCProtocolLib repo.

**Comment by MrPowerGamerBR** [comment]
Already doing this, wait a minute.

**Comment by MrPowerGamerBR** [comment]
Done, I just need to add a flipswitch on the config file.

**Comment by MrPowerGamerBR** [comment]
Done: https://github.com/DragonetMC/DragonProxy/pull/60

**Comment by MrPowerGamerBR** [comment]
Pull request pulled by @RandomAltThingy , closing this issue.
