### ISSUE TITLE
Is dragonet.org down?

### ISSUE THREAD

**Issue by tdb85** [DragonetMC/DragonProxy#60]
Just discovered this project, awesome stuff!  Happy to contribute in any small way I can, but I can't get signed in.  

Tells me to go to http://auth.dragonet.org and follow instructions but seems to be down.

**Comment by TheDiamondYT1** [comment]
You don't need to be signed in to test it

**Comment by DefinitlyEvil** [comment]
@ktowntbrown and please move step to DragonetMC/UltimateRolesBukkit that's what I'm focusing on ;)
