### ISSUE TITLE
Stuck at Syncing pack with server...

### ISSUE THREAD

**Issue by razorrider7** [DragonetMC/DragonProxy#61]
I know this is a beta version, but I wanted to test this on a little server I run at home. I can't seem to get past
```
Received RakNet packet: RakNetPacket
FIRST BYTE = fe, len = 3978
```
or "Syncing pack with server..." (in MC Win 10). It works sometimes, but I've only gotten through in online mode once or twice out of 25+ or so tries. Not sure why it won't even let me use it, and any help would be appreciated. Also, if I can, I would like to donate once the website and software are up and running.

**Comment by DaMatrix** [comment]
it doesn't work, it probably won't ever work, don't get your hopes up

**Comment by DefinitlyEvil** [comment]
@razorrider7 please use ProtocolSupportPE
