### ISSUE TITLE
Warn the user when the PC Server is unreachable/offline.

### ISSUE THREAD

**Issue by MrPowerGamerBR** [DragonetMC/DragonProxy#64]
This commit 10984b51bae956754d0d417744e6eaacf18bcb4b added support for querying the PC Server so DragonProxy will display the online/max players numbers on the Proxy instead of "-1/-1" (which in, my opinion, is better).

This also allows us to get the Server query response and, if it isn't reachable, we can warn the user on the DragonProxy console that the PC Server is unreachable.

**Comment by RandomAltThingy** [comment]
I can do this after or you can make a PR.

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy I can do this, but Maven can't find the JANSI dependecy, so I can't compile DragonProxy.

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy also FYI, the builds from CircleCI are also failling due to the missing dependency.

```
[ERROR] Failed to execute goal on project DragonProxy: Could not resolve dependencies for project org.dragonet.proxy:DragonProxy:jar:0.0.2: Could not find artifact org.fusesource.jansi:jansi-project:jar:1.11 in sonatype (https://oss.sonatype.org/content/repositories/public/) -> [Help 1]
```

**Comment by RandomAltThingy** [comment]
@MrPowerGamerBR Can you try and fix it? I dont have access to an IDE on my nans slow laptop, only Notepad++. If I search it on maven repository it says it exists.

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy I tried adding this:
```
`        <repository>
            <id>maven2repo</id>
            <name>Maven2 Repo</name>
            <layout>default</layout>
            <url>http://repo1.maven.org/maven2/</url>
        </repository>
```

But it still searchs on Sonatype. (Maybe I need to do a "maven clean", but I'm on a mobile connecting, so that would take a lot of time/will eat a lot of my mobile data)

**Comment by RandomAltThingy** [comment]
@MrPowerGamerBR Maybe add the repository? Google "jansi github"

**Comment by MrPowerGamerBR** [comment]
I'm now going home now, so I can't test this.
Em 17 de jan de 2016 08:02, "Luke" <notifications@github.com> escreveu:

**Comment by RandomAltThingy** [comment]
@MrPowerGamerBR Try it now?

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy Didn't I already implement this in a Pull Request? I forgot to close this issue.

**Comment by RandomAltThingy** [comment]
Yes lmao whoops
