### ISSUE TITLE
new codebase by refactoring Nukkit??

### ISSUE THREAD

**Issue by DefinitlyEvil** [DragonetMC/DragonProxy#64]
#### hey it's an idea 
or base on `PMMP`, replace the world loading part with remote chunks

**Comment by Creeperface01** [comment]
the reason why Jraknet doesn't work is that its outdated or decoding is wrong?

**Comment by TheDiamondYT1** [comment]
Nukkit is gay, PMMP is PHP.

**Comment by DefinitlyEvil** [comment]
@TheDiamondYT1 wtf xD 
@Creeperface01 outdated packet definitions

**Comment by TheDiamondYT1** [comment]
I can ask MarfGamer to update it

**Comment by Creeperface01** [comment]
Maybe you can use base from nemisys

**Comment by DefinitlyEvil** [comment]
@Creeperface01 nope, just stay this way for now
