### ISSUE TITLE
Remapping blocks... A quick question.

### ISSUE THREAD

**Issue by MrPowerGamerBR** [DragonetMC/DragonProxy#65]
Should we remap every block MCPE doesn't have?

Example: https://github.com/ProtocolSupport/ProtocolSupport/blob/mcpe/src/protocolsupport/protocol/typeremapper/id/IdRemapper.java

(I made the MCPE remappers for ProtocolSupport, I remapped every block that doesn't exist in MCPE 0.13.X)

Should we port those remappers to DragonProxy?

**Comment by DefinitlyEvil** [comment]
Maybe, I am not sure. xD I think we should only replace blocks which actually CAN be replaced by a similar block(eg. stained glass as normal glass), in other situations, we keep PC IDs so client display as UpdateBlock block.

**Comment by MrPowerGamerBR** [comment]
Later I will send another PR with new remappers (colored signs, etc)
Em 17 de jan de 2016 09:12, "The Evil Man" <notifications@github.com>
escreveu:

**Comment by DefinitlyEvil** [comment]
@MrPowerGamerBR Signs requires sending NBT things BUT currently our NBT library is seems broken, once we fixed that we can continue most of the jobs and everything will be easier.

**Comment by DefinitlyEvil** [comment]
So closing this if question is solved. xD
