### ISSUE TITLE
Can not connect

### ISSUE THREAD

**Issue by GarryLai** [DragonetMC/DragonProxy#65]
I can't connect to the proxy, it stuck in the loading page and can't join the world, please help me. 
Thank you very much. 
My pc server version is 1.12.1 and my pe client version is 1.0.14.

**Comment by DefinitlyEvil** [comment]
DP is dis-continued.

**Comment by GarryLai** [comment]
Sorry, I would like to ask that which software can instead of it, It is important to our server.
Thank you.

**Comment by DefinitlyEvil** [comment]
@GarryLai you can use ProtocolSupportPE which is almost finished

**Comment by Wesley-Van-Neck** [comment]
@DefinitlyEvil its not finish its like pre pre pre pre alpha

**Comment by DefinitlyEvil** [comment]
@Wesley-Van-Neck but it works

**Comment by GarryLai** [comment]
I have asker the author of that plugin he said that the mcpe branch it is not already to use, could you just help me continue this project I really need it, I can't find anything can instead of it, it is really important.
Thank you very much.

**Comment by ethsmith** [comment]
This project needs a lot of work and the whole team got busy. There isn't a way for us to have the time to recreate this. We can always advice but we don't have the time to code it ourselves at this point. 

I have told multiple people to start on the first connection. I.E. running the TCP server on the port specified, sending and receiving the serializable messages, and than making that handshake connection that will lead to chunk loading.

**Comment by DaMatrix** [comment]
@GarryLai it's not perfect, but this project is much more difficult to make work than PS, and has less (aka 0) active devs whereas PS has 3.

**Comment by ethsmith** [comment]
Sadly for the skill set of most contributors giving advice isn't enough because they don't know how to translate it to code.
