### ISSUE TITLE
Test Servers

### ISSUE THREAD

**Issue by MrPowerGamerBR** [DragonetMC/DragonProxy#67]
mrpowergamerbr.com:19132 - SparklyPower (My public server)

mrpowergamerbr.com:19133 - Hypixel

mrpowergamerbr.com:19134 - GotPvP

mrpowergamerbr.com:19135 - FadeCloud

mrpowergamerbr.com:19136 - ArkhamNetwork

mrpowergamerbr.com:19137 - Omega Realm

They will be open until... I don't know, until I decide they should be closed? :stuck_out_tongue:

**Comment by RandomAltThingy** [comment]
Thanks

**Comment by RandomAltThingy** [comment]
@DefinitlyEvil Can you change the test server IPs to test.dragonet.org

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy What about demo.dragonet.org ?

**Comment by RandomAltThingy** [comment]
Good idea

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy Added, please update related README files and other files. ;)
