### ISSUE TITLE
Site is down?

### ISSUE THREAD

**Issue by ApocalypsjeNL** [DragonetMC/DragonProxy#69]
Hello,
I tried to build and test DragonProxy today, but when I tried to join using MCPE 1.1.4 it kicks me with the message: 'Dragonet CLS system enabled. You can login at http://auth.dragonet.org &3and follow instructions.'
But when I go to that site I get this error:
The webpage at http://auth.dragonet.org/ might be temporarily down or it may have moved permanently to a new web address. (ERR_NAME_RESOLUTION_FAILED). 
Is there a way to use this? or to host it myself? Because I really like the project idea.

Greets,
ApocalypsjeNL

**Comment by Wesley-Van-Neck** [comment]
Its dead
