### ISSUE TITLE
1.12.2 (Java) & 1.2.2 (PE/PC) Support?

### ISSUE THREAD

**Issue by ghostzero** [DragonetMC/DragonProxy#70]
Any planed features?

Contact: GhostZero#0713

**Comment by ethsmith** [comment]
Currently DragonProxy isn't being developed. All of the devs have gotten busy with other life stuff.

**Comment by DefinitlyEvil** [comment]
project dead

**Comment by DaMatrix** [comment]
@DefinitlyEvil just disable the issue tracker
