### ISSUE TITLE
Test server

### ISSUE THREAD

**Issue by Creeperface01** [DragonetMC/DragonProxy#70]
Hi idk why but i can not connect to hypixel on your test server. And if i connect, chunks load very slowly and i can not chat, and i can break blocks etc... Maybe i have slow internet connection but other servers works well for me so idk where is the problem. Maybe your hosting is a bit slow

**Comment by TekkitCommando** [comment]
Not a matter of slow hosting, it's just a proxy matter probably

**Comment by MrPowerGamerBR** [comment]
Try using mrpowergamerbr.com:19133

That's my Hypixel DragonProxy test server, even tho when I tried joining it I couldn't connect sucessfully (however any of the other servers worked)

**Comment by DefinitlyEvil** [comment]
Online mode has a bug after you logging into your primium account, you will be teleported to the actual spawn point of the remote server from the place you do login which is always (0, 72, 0) but the teleportion is too slow idk why.

**Comment by DefinitlyEvil** [comment]
And closing this due to this is not an issue.
