### ISSUE TITLE
Update README screenshots

### ISSUE THREAD

**Issue by MrPowerGamerBR** [DragonetMC/DragonProxy#71]
There is only one screenshot and it is very old (even the chat is white!).

Maybe some new screenshots (after some bugs on DragonProxy are fixed) would be very nice.

**Comment by RandomAltThingy** [comment]
Your servers are down proxy offline.

Make the proxy point to pvp.thearchon.net please so I can test

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy they are online here.

For some reason they stop pinging randomly until I reconnect to the PuTTY screen.

I will change the Hypixel Proxy to go to The Archon, wait a minute.

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy mrpowergamerbr:19133 -> The Archon

**Comment by RandomAltThingy** [comment]
Can't connect

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy whoops, it is mrpowergamerbr.com:19133

Anyway, every test server here is online, if you aren't able to connect, try using the numeric IP: 158.69.120.5:19133

![2016-01-18 16 45 38](https://cloud.githubusercontent.com/assets/9496359/12397121/5a3e188a-bdf2-11e5-83c7-3ce61a00ae71.png)

**Comment by RandomAltThingy** [comment]
Nope

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy then I don't know what is the problem, every proxy is online for me

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy for some reason the proxy stops showing in the server list (but my PC server doesn't hang)

Try now.

**Comment by RandomAltThingy** [comment]
Nope

**Comment by RandomAltThingy** [comment]
Maybe reboot vps with the command "reboot"

**Comment by RandomAltThingy** [comment]
@DragonetMC/developers Should I make a java or C# mcpe server software? And if I made a C# one (Cuz its faster) would you contribute? It can be the new dragonet xD

**Comment by TekkitCommando** [comment]
I don't know C#, My courses and what I have already learned are Java and Python xD I may learn C# and C++ at some point but it will be a while :P Java is the best and Python is OK xD

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy huh https://github.com/Nukkit/Nukkit

Nukkit is a MCPE Server made in Java.
