### ISSUE TITLE
Proxy should never be trusted with user credentials

### ISSUE THREAD

**Issue by Plazmaz** [DragonetMC/DragonProxy#72]
I think devising a system to get a user's access token via the official dragonet website is the only acceptable way to handle this. I'm not sure how mcpe encrypts traffic, but several security issues arise with sending credentials over LAN. Please implement access tokens. Also, perhaps servers should be issued ssl esque certificates so users know they can trust a given server with a fair amount of certainty they won't perform a MITM attack.

**Comment by MrPowerGamerBR** [comment]
The only way is generating a access token with the Mojang API by logging in with your user credentials.

The only other way is changing the authentication to be via a website connected with the proxy, which allows you to login via the website, the website shares the auth token to the proxy (and then the proxy sends the auth token to the server).

It is impossible? No. It is impratical for the normal user? Yes, and possibly very difficult to implement.

**Comment by Plazmaz** [comment]
Or, the website gives you a six character code that gives the proxy access to the access token. Regardless of implementation difficulty, this would be easier for the user and an immense amount safer.

**Comment by MrPowerGamerBR** [comment]
@Plazmaz yeah, this solution also works :+1: 

A external auth is needed, but I don't think it should be implemented now (maybe later, when the project is more stable and... well... working)

**Comment by DefinitlyEvil** [comment]
@MrPowerGamerBR @Plazmaz Once we get SSL cert, we can continue the CLS system development.

**Comment by DefinitlyEvil** [comment]
And also it can fix the screen shaking problem.

**Comment by jython234** [comment]
MCPE network traffic is not encrypted, it is quite easy to use wireshark
and sniff out TextPackets with the credentials.

**Comment by DefinitlyEvil** [comment]
@jython234 So I invented CLS lol but we still lack of a SSL cert.

**Comment by Pet0203** [comment]
Shouldn't it be possible to encrypt the packets and create a Auth server that decrypts it and then sends it to Mojang Auth?

**Comment by DefinitlyEvil** [comment]
@Pet0203 Seemed impossible or we can integrate CLS into a seprate official server?

**Comment by Plazmaz** [comment]
You'd need the client to support encryption, which it doesn't by default apparently.

**Comment by DefinitlyEvil** [comment]
@Plazmaz True.
