### ISSUE TITLE
CLS System Beta Test

### ISSUE THREAD

**Issue by DefinitlyEvil** [DragonetMC/DragonProxy#73]
#### Login process for players: 
- 1. Go to `http://auth.dragonet.org/` and login with their Minecraft premium account. 
- 2. Write down the specialized username. 
- 3. Set the name into MCPE options. 
- 4. Join servers with ease, no anooying login prompts and NO SCREEN SHAKINGS! Yay! 

## Serious Problem:
CLS will display error when you login more than one single time. **(FIXED)**

**Comment by DefinitlyEvil** [comment]
@DragonetMC/developers

**Comment by RandomAltThingy** [comment]
Says invalid credentials

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy I used `MCAuth.class.php` from Github, idk why. It says invalid credentials even when I use my friends account. xD

**Comment by RandomAltThingy** [comment]
<iframe src="http://strawpoll.me/embed_1/6596315/r" style="width: 600px; height: 390px; border: 0;">Loading poll...</iframe>

**Comment by DefinitlyEvil** [comment]
@TekkitCommando @mastercoms Why it will say `invalid credentials` if you login by username more than 1 time on same IP? CLS system is experiencing this problem.

**Comment by TekkitCommando** [comment]
@DefinitlyEvil It may be experiencing a bad login error but there's nothing to handle bad logins in DragonProxy. I am not certain but it seems likely.

**Comment by TekkitCommando** [comment]
Since there is nothing to handle bad login error it returns invalid credentials

**Comment by DefinitlyEvil** [comment]
@TekkitCommando I found it on `wiki.vg`: 
```
This endpoint is severely rate-limited: multiple /authenticate requests for the same account in a short amount of time (think 3 requests in a few seconds), even with the correct password, will eventually lead to an Invalid credentials. response. This error clears up a few seconds later. 
```

**Comment by MrPowerGamerBR** [comment]
@DefinitlyEvil if you are going to authenticate with Mojang using the same IP every time, you are going to have a bad time.

Mojang will rate block you after a lot of authentications from different accounts, it takes 2-3 hours to remove the IP block.

**Comment by spideyroc1** [comment]
Doesnt seem to work  for me because when i go to auth.dragonet.org and register it doesnt send a email and if i try to login i click the login button and get redirected and it gives me a 500 error on the page

**Comment by Pet0203** [comment]
I think that we should get the proxy working before we add encrypted log in methods. There is i lot to do and i think that we are focusing on the wrong thing.

**Comment by MrPowerGamerBR** [comment]
@Pet0203 exactly, the proxy needs to be stable first, after being stable, then those fancy features can be worked on.

**Comment by RandomAltThingy** [comment]
Well we need security and authentication that works

**Comment by DefinitlyEvil** [comment]
@Pet0203 @spideyroc1 @RandomAltThingy @MrPowerGamerBR CLS is still under my development and there are tons of errors. xD

**Comment by MCPEGamerJPatGitHub** [comment]
nope, not working.

**Comment by RandomAltThingy** [comment]
@MCPEGamerJPatGitHub Did you not read @DefinitlyEvil's answer? He said it is **not** working yet.

**Comment by MCPEGamerJPatGitHub** [comment]
@RandomAltThingy That is a general comment. Seems like you don't even understand the British culture.

**Comment by RandomAltThingy** [comment]
@MCPEGamerJPatGitHub *"nope, not working "* just looks like laziness.

**Comment by RandomAltThingy** [comment]
It says it sent me an email to confirm account register but I didn't get an email

**Comment by MCPEGamerJPatGitHub** [comment]
The system is broken, currently coding a script to fix it @RandomAltThingy

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy E-mail registering is fine, check your spambox.

**Comment by RandomAltThingy** [comment]
@DefinitlyEvil Can you make the archon test server (port 19133) online mode cls ain't working

**Comment by MCPEGamerJPatGitHub** [comment]
@RandomAltThingy Irrelevant to this issue. Please post an another issue to ask for an improvement

**Comment by RandomAltThingy** [comment]
@MCPEGamerJPatGitHub Don't tell me what to do.

**Comment by RandomAltThingy** [comment]
@MCPEGamerJPatGitHub What's that? Can't post a reply? Shame!

**Comment by TekkitCommando** [comment]
Don't act childish @RandomAltThingy. He is technically right.

**Comment by DefinitlyEvil** [comment]
Lol people stop arguing...

**Comment by TekkitCommando** [comment]
@MCPEGamerJPatGitHub forgive him please :)

**Comment by MCPEGamerJPatGitHub** [comment]
lol random is like this always

**Comment by DefinitlyEvil** [comment]
@DragonetMC/developers CLS Website and API works now.

**Comment by mastercoms** [comment]
@TekkitCommando Well, he _is_ a child. The twitter linked from his old GitHub account (that he deleted because he incorrectly said someone's code was wrong on a Bukkit PR) says he's 12 years old or something

**Comment by MCPEGamerJPatGitHub** [comment]
@mastercoms actually when I was contributing to RedstoneLamp he got kicked from gitter for being such a jerk.

**Comment by RandomAltThingy** [comment]
What does jerk even mean lmao I'm from UK. And actually I was kicked because I submitted PRs that had Incorrect code as way back then I didn't even know what an "IDE" was.

**Comment by DefinitlyEvil** [comment]
Somebody please help. xD

**Comment by MCPEGamerJPatGitHub** [comment]
@RandomAltThingy I'm an independent englishmen...
You don't even know what you're talking about XD

**Comment by mastercoms** [comment]
@RandomAltThingy Yeah, I know you're from the UK. I even know what private school you go to because you put that on your Twitter...

Judging from what I've seen about your attitude, I'm going to believe @MCPEGamerJPatGitHub on this one.

**Comment by MCPEGamerJPatGitHub** [comment]
This conversation is way too long, copy pasted the issue on a new one

**Comment by mastercoms** [comment]
@MCPEGamerJPatGitHub alrighty

**Comment by MCPEGamerJPatGitHub** [comment]
Thanks. :)

**Comment by RandomAltThingy** [comment]
@MCPEGamerJPatGitHub Close the copy, I will delete comments here.
@TekkitCommando Its not a private school

**Comment by MCPEGamerJPatGitHub** [comment]
CLOSE THIS

**Comment by RandomAltThingy** [comment]
Why

**Comment by St3amer** [comment]
I add my Premium Minecraft Account but get invalid credentials...

**Comment by Aazzinaro** [comment]
the name generated for me is too long to put into PE

**Comment by DefinitlyEvil** [comment]
@St3amer Don't try to login too many times within 1 hour or system will ban our CLS for 1-2 hours so you always get `Invalid Credentials`.

**Comment by DefinitlyEvil** [comment]
@Aazzinaro Hmm, that's your ign?

**Comment by Aazzinaro** [comment]
@DefinitlyEvil no the login generated for me was : DaddySophiaCat_8e299d
PE client cuts off after _

**Comment by DefinitlyEvil** [comment]
Hmm... @Aazzinaro Gonna switch to ID_KeyCode soon.

**Comment by DefinitlyEvil** [comment]
@Aazzinaro Fixed now.

**Comment by 4679** [comment]
Faild to login, error: Invalid credentials.

What should I do?

**Comment by RandomAltThingy** [comment]
@4697 Enter correct credentials

**Comment by 4679** [comment]
@RandomAltThingy I'm sure it's correct.

**Comment by RandomAltThingy** [comment]
@DefinitlyEvil I'm sorry to be such a pain but any chance of making a test server heading to white.thearchon.net so people can checkout an actual factions server and white is OP facs make it like white.Dragonet.org

**Comment by DefinitlyEvil** [comment]
@4679 Wait for one two or three then try again, Mojang will block our service for few hours if you try to login same account too many times.

**Comment by 4679** [comment]
@RandomAltThingy Done. Thanks

**Comment by TheDiamondYT1** [comment]
Beta testing over, all bugs listed here fixed. Closed.
