### ISSUE TITLE
Auth.dragonet.org dont work

### ISSUE THREAD

**Issue by Hundeklemmen** [DragonetMC/DragonProxy#74]
DELETE PLS

**Comment by Hundeklemmen** [comment]
nwm

**Comment by DefinitlyEvil** [comment]
It's down for now

**Comment by ghost** [comment]
@Hundeklemmen Just disable it in config.

**Comment by Bluscream** [comment]
> 
> 
> @Hundeklemmen Just disable it in config.

How? Just make it empty? And can i use auth.mojang.com ?

**Comment by lukeeey** [comment]
Firstly, its nothing to do with Mojang authentication.

Secondly, its dead.

**Comment by Bluscream** [comment]
> 
> 
> Firstly, its nothing to do with Mojang authentication.
> 
> Secondly, its dead.

That does only answer one of two questions.

**Comment by lukeeey** [comment]
Set the auth mode to offline i believe. Or online if that works i cant remember if it does or not
