### ISSUE TITLE
Custom license

### ISSUE THREAD

**Issue by TheDiamondYT1** [DragonetMC/DragonProxy#74]
Firstly, does the GNU Lesser License allow to redistribute the project with a different name and no credit? If it does, we may want to make a custom license or use a different one. It's annoying that this one person took the software, made an app so you can control it and changed the name with no credit to us.

**Comment by MrPowerGamerBR** [comment]
http://choosealicense.com/

**Comment by RandomAltThingy** [comment]
But which one prevents people claiming as their own or not giving us credit

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy it is on the page...

> The MIT License is a permissive license that is short and to the point. It lets people do anything they want with your code as long as they **provide attribution back to you** and don’t hold you liable. 

There is also a lot of other licences here: http://choosealicense.com/licenses/

**Comment by RandomAltThingy** [comment]
MIT license it is. @DefinitlyEvil. Can somebody with a PC ide please change the license headers?

**Comment by RandomAltThingy** [comment]
We should eventually make a custom license

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy We need a lawyer! xD

**Comment by TekkitCommando** [comment]
@DefinitlyEvil I will tell you rn that GPL or MIT is the best. However with GPL I think theres no sublicensing.

**Comment by DefinitlyEvil** [comment]
@TekkitCommando I will leave you guys talk about this. xD I have no idea.

**Comment by TekkitCommando** [comment]
lol ok

**Comment by RandomAltThingy** [comment]
@MrPowerGamerBR Check Reddit msgs
