### ISSUE TITLE
unable to connect to world

### ISSUE THREAD

**Issue by Wqrld** [DragonetMC/DragonProxy#77]
https://hastebin.com/oxacarugab.php config

cant join any servers atleast looks like it.

oh, i see dproxy is 1.2.2 only? is it possible to downgrade win10/upgrade proxy

**Comment by Wqrld** [comment]
pc client to pc server also doesnt seem to work, could this be dragonproxy or my network setup

**Comment by DaMatrix** [comment]
It doesn't work, it never worked well, the only version that ever kinda worked was deleted, and despite the fact that @DefinitlyEvil claims to have revived it it still seems as dead as it was. This project will never get off the ground again, don't get your hopes up.

**Comment by ghost** [comment]
go for pspe #pspe XD

**Comment by DefinitlyEvil** [comment]
It worked for me. :O

**Comment by Wqrld** [comment]
@DefinitlyEvil what is the current bottleneck?

**Comment by DefinitlyEvil** [comment]
Client always floats
