### ISSUE TITLE
Crash when I join the hypixel test server

### ISSUE THREAD

**Issue by spideyroc1** [DragonetMC/DragonProxy#79]
I type in my username/password, it says success on login then it says that it is going to connect to the server and then a crash happens, while I log in my character spins and glitches out. I am on an android 5.1.1 Samsung galaxy s6.
Anyone know the problem?

**Comment by RandomAltThingy** [comment]
Online auth is currently buggy. You also get teleport to the servers spawn point, not the spawn set by the server owner. For example, if the spawn point set by the owner on Hypixel is 130, 20, 130 and the default world spawn is 0, 50, 0 then you will get teleported to the 0, 50, 0 one

**Comment by spideyroc1** [comment]
I also had a few questions about the project, can I use the proxy on any server, like host it on my vps and put in mineplex.com and port 25565 for it and be able to join using my phone?

**Comment by RandomAltThingy** [comment]
No, put it on your vps and enter the vps IP into mcpe with the port in the config at udp_bind_port. By default its 19132.  To connect to mineplex via the proxy change remote_ip to the mineplex. IP and by default the remote_port is 25565

**Comment by DefinitlyEvil** [comment]
Duplicated issue I think, closing this.
