### ISSUE TITLE
13.1 protocol broken

### ISSUE THREAD

**Issue by CAmadeusA** [DragonetMC/DragonProxy#8]
The server was working before I updated the app to 13.1, then on the same server and same settings on attempting to join the server, the MCPE App never locates the server. The server's console does not register a connection either.

**Comment by TheMasterBlaster** [comment]
I too am having this same issue.

**Comment by jlirochon** [comment]
@DefinitlyEvil did you try with 0.13.1 ?

**Comment by TheMasterBlaster** [comment]
That is the version of MCPE Im currently running.

**Comment by DefinitlyEvil** [comment]
Will be checked asap.

**Comment by DefinitlyEvil** [comment]
Found the crap, I forgot to update LoginPacket. ;P

**Comment by KangYui** [comment]
it  seems solved, should close.

**Comment by DefinitlyEvil** [comment]
@KangYui But @TheMasterBlaster still expiriencing this problem. xD
