### ISSUE TITLE
client can't teleport? 

### ISSUE THREAD

**Issue by DefinitlyEvil** [DragonetMC/DragonProxy#80]
everytime I send `MovePlayerPacket` (even with mode TELEPORT), client will go to its join game position from `StartGamePacket`, no idea how and why

**Comment by TheGameratorT** [comment]
Mcprotocollib or MCAuthLib version error just compile with the release versions of them.

**Comment by DefinitlyEvil** [comment]
what? @Tiago1098

**Comment by HoverEpic** [comment]
I think this issue is now outdated.
