### ISSUE TITLE
DragonProxy not working properly.

### ISSUE THREAD

**Issue by TheGameratorT** [DragonetMC/DragonProxy#81]
So as I configured DNMC (dragonetmc) and I started playing I was stuck In an invisible world.

Detailed Video: https://youtu.be/oRfCJ-jXJ5g

**Comment by TheGameratorT** [comment]
Ignore the cls, now I know that is closed. But please fix the loading

**Comment by DaMatrix** [comment]
IT

DOESN'T

WORK

REEEEEEEEE

(you really shouldn't even try to use this unless you're a developer because it's in no way shape or form ready for use, even in creative mode, and it doesn't even launch for anyone except apparently @DefinitlyEvil )

**Comment by DefinitlyEvil** [comment]
@DaMatrix duuuh, it works for me and it should work for anyone

**Comment by egg82** [comment]
Possibly related to #80
The software is still being actively developed and a lot is still missing. We'll get there, though!

**Comment by TheGameratorT** [comment]
Ok, thanks anyways!
