### ISSUE TITLE
CircleCI Producing No Artifacts

### ISSUE THREAD

**Issue by DefinitlyEvil** [DragonetMC/DragonProxy#82]
Idk why this happening, guys plz help!

**Comment by MrPowerGamerBR** [comment]
What?

![http://i.imgur.com/0J16PGv.png](http://i.imgur.com/0J16PGv.png)

I'm missing something or... https://circle-artifacts.com/gh/DragonetMC/DragonProxy/226/artifacts/0/tmp/circle-artifacts.cITfpHB/dragonproxy-0.0.3-preR3.jar

**Comment by DefinitlyEvil** [comment]
Hmm, okay I got it. xD

**Comment by DefinitlyEvil** [comment]
Forgot to login... ;P

**Comment by DefinitlyEvil** [comment]
And we MUST choose the artifact from the commit which is actually the release. 
Corrected link is: 
https://circle-artifacts.com/gh/DragonetMC/DragonProxy/225/artifacts/0/tmp/circle-artifacts.rWWOLrO/dragonproxy-0.0.3-preR2.jar

**Comment by RandomAltThingy** [comment]
I picked wrong link
