### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by TheGameratorT** [DragonetMC/DragonProxy#83]
Build Failure do I need 64-bits Windows?

![image](https://user-images.githubusercontent.com/20758065/32906325-7c79eecc-caf4-11e7-9951-3adb88a76601.png)

**Comment by HoverEpic** [comment]
Not a Java problem, try to add 
```
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
```
in your repositories.
(and maybe "mvn package -U" to force update the dependancies)

**Comment by egg82** [comment]
You're going to want to update Maven deps. I removed the jitpack dep because I uploaded it to a public repo that's defined in the pom.

**Comment by TheGameratorT** [comment]
Thanks! It worked with mcauthlib (1.0) and mcprotocollib (1.12.1-1), I managed to enter the server with very "pls update" blocks, but it worked! (Until I touched the void, that messed up everything, because the pc void kills in creative and in Bedrock Edition not)

**Comment by egg82** [comment]
I'll see if I can repro this specific issue on my end as well

**Comment by DefinitlyEvil** [comment]
@Tiago1098 thanks for da information ;)
