### ISSUE TITLE
Serious problem

### ISSUE THREAD

**Issue by lsw46** [DragonetMC/DragonProxy#83]
The backpack is empty in create mode.
Cannot synthesize items.
Table cannot be used normally.
Trouble to solve these problems.
Thanks!

**Comment by DefinitlyEvil** [comment]
This is in our to-do list and also an existed issue, please check back later. 
Thanks for trying out DragonProxy. ;)

**Comment by lsw46** [comment]
Thank you !

**Comment by lsw46** [comment]
Thank you !

**Comment by DefinitlyEvil** [comment]
You're welcome! ;)
