### ISSUE TITLE
Player cannot tp to other server on Bungeecord

### ISSUE THREAD

**Issue by jiongjionger** [DragonetMC/DragonProxy#84]
When the player is tp to other servers, the client also shows online, but the server has been shown that the player left the server.

**Comment by Pet0203** [comment]
Please, read the other issues before you make a new one. This has already been reported two times. World changing is supported but teleportation is not working for now.

**Comment by MrPowerGamerBR** [comment]
@Pet0203 no, teletransportation is supported, but the player is teletransported before any chunks are sent, this causes a bug.

If you teleport to a location where the client was already been there, the teletransportation works.

But yeah, it is a duplicate issue.

**Comment by jiongjionger** [comment]
@Pet0203 /tp or /tpa is work. But tp to other server did not take effect.

**Comment by Pet0203** [comment]
@MrPowerGamerBR That is exactly What i meant.

@jiongjionger It does work actually. I've successfully logged in to my towny and faction servers from the lobby, just have to write /spawn a few times and then the chunks will load.
