### ISSUE TITLE
Touching the void bugs the account

### ISSUE THREAD

**Issue by TheGameratorT** [DragonetMC/DragonProxy#84]
If I touch the void in Minecraft Java Edition I'm killed (both on creative and survival), but on Bedrock Edition only survival kills. So if you accidentally touch the void on Bedrock Edition on creative you need to open Minecraft Java Edition and click the respawn button, otherwise you can't do nothing even chatting (I get a problem saying that it can't send it). So basically you are dead in Java Edition but alive in Bedrock Edition causing a client-side (Bedrock Edition)/proxy bug.

**Comment by TheGameratorT** [comment]
*you can only walk but no one sees you and you can't interact with nothing.

**Comment by DefinitlyEvil** [comment]
thx for da info! 
and yes interactions are not implemented yet ;)

**Comment by HoverEpic** [comment]
i think it's ok, with the respawn button working.
