### ISSUE TITLE
Client can't see blocks higher than 127 Y

### ISSUE THREAD

**Issue by Pet0203** [DragonetMC/DragonProxy#85]
As the title says, client can't see blocks that are higher than 127 blocks Y. I don't really know if we can fix this somehow, because this is a issue with the client and not server. The height limit for PE is 127 blocks.. http://minecraft.gamepedia.com/Altitude#Pocket_Edition. No chance we can fix this?

**Comment by MrPowerGamerBR** [comment]
No way to fix this, it is a client side limitation.
