### ISSUE TITLE
Could not resolve dependencies

### ISSUE THREAD

**Issue by ogmkp** [DragonetMC/DragonProxy#86]
Hello,

When i do the mvn package, a dependencie failed to collect, do you have a solution for a dependencie replacement please ?
Thank you.

`[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building proxy 0.2.0-preR1
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.github.Steveice10:mcprotocollib:jar:1.12.2-1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.github.Steveice10:mcauthlib:jar:1.1-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.487 s
[INFO] Finished at: 2017-11-21T18:03:30+01:00
[INFO] Final Memory: 7M/110M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project proxy: Could not resolve dependencies for project org.dragonet.proxy:proxy:jar:0.2.0-preR1: The following artifacts could not be resolved: com.github.Steveice10:mcprotocollib:jar:1.12.2-1-SNAPSHOT, com.github.Steveice10:mcauthlib:jar:1.1-SNAPSHOT: Failure to find com.github.Steveice10:mcprotocollib:jar:1.12.2-1-SNAPSHOT in https://oss.sonatype.org/content/repositories/public/ was cached in the local repository, resolution will not be reattempted until the update interval of sonatype has elapsed or updates are forced -> [Help 1]
`

**Comment by ghost** [comment]
already known

**Comment by ghost** [comment]
and if it compile its still bad because its wip

**Comment by TheGameratorT** [comment]
Compile with another version in the pom file

**Comment by TheGameratorT** [comment]
Like 1.12.2-1-snapshot is 1.12.1-1

**Comment by DefinitlyEvil** [comment]
will be solved using jitpack.

**Comment by ogmkp** [comment]
Thank you !
