### ISSUE TITLE
Move problem

### ISSUE THREAD

**Issue by HoverEpic** [DragonetMC/DragonProxy#87]
I started working on the move issue since a day and it's starting make me crazy =P
Im creating this thread to talk about this and our experiments (don't know if this is the right place to do it).

I have some tools that i created for protocol hacking (and bots) :
- a fake client based on MCProtocolLib with IN/OUT packets logging
- a spigot plugin with IN/OUT packets logging
- a Nukkit server with IN/OUT packets logging
- a Forge mod with IN only packets loging

So i started testing these multiple ways to listen PE and PC protocols and try to find out the problem.

I find out mcpe only use the MovePlayerPacket for potition and yaw/pitch, witch is different packets in Java : ClientPlayerPositionPacket & ClientPlayerRotationPacket (and the actual ClientPlayerPositionRotationPacket for pos + with/yaw at the same time).

Normaly, the server will update the player's position in it's data, but the internal player's position is not updated when packets are recieved (and that is crazy !).

We are probably missing something, I'm going to dig in Minecraft Server sources to find what is wrong.

**Comment by DefinitlyEvil** [comment]
thx
(WRONG, NOT WORKING)`I can get player to the right position by sending chunks after changing a dimension(which I can re-spawn the player), then I can do `/spawn` and it works (tested on Performium server)
otherwise it just reset player's yaw and pitch`
update: it's actually not working :(

**Comment by HoverEpic** [comment]
just tested on bukkit, the entity is not valid, that mean the entity is dead or not correctly added to the world (not spawned). when an entity is added to the world, the spawn can fail because of the chunk is not loaded.
Now why the chunk is not loaded on player login....

**Comment by HoverEpic** [comment]
I think i'ts working, my player was dead (even in creative mod) si i just cleared my playerdatas ><
I can now chat / move / break and my player is viewable by a java client.
Lets try @DefinitlyEvil  when you have time.

**Comment by HoverEpic** [comment]
Next thing to fix : player action packet, to be able to respawn =P

**Comment by DefinitlyEvil** [comment]
okay that's a minor problem, the problem more in priority now is the teleportation packet MovePlayerPacket

**Comment by HoverEpic** [comment]
Ok, i'll check that.

**Comment by HoverEpic** [comment]
The probleme is from eid = 0, i've tryed an impl but i think it break some packets, check out my fork.

**Comment by Creeperface01** [comment]
I recommend not to use ID 0 there were problems with it in the past, use any other value

**Comment by HoverEpic** [comment]
Or use the good value if working ^^

**Comment by DefinitlyEvil** [comment]
Then we gotta use a EID map xD

**Comment by DefinitlyEvil** [comment]
fixed thanks to @HoverEpic and @Creeperface01
