### ISSUE TITLE
CLS Beta Testing --- Work In Progress :)

### ISSUE THREAD

**Issue by MCPEGamerJPatGitHub** [DragonetMC/DragonProxy#87]
CLS System Beta Test

Address: http://auth.dragonet.org/

API: http://api.dragonet.org/cls/query_token.php?username=IGN&keycode=SIX_CHARS_CODE

Login process for players:

1. Go to http://auth.dragonet.org/ and login with their Minecraft premium account.
2. Write down the specialized username.
3. Set the name into MCPE options.
4. Join servers with ease, no anooying login prompts and NO SCREEN SHAKINGS! Yay!
Serious Problem:

CLS will display error when you login more than one single time.

Tell me how you feel. @DragonetMC/developers @DragonetMC/watchers

- The other issue is now invalid and closed due to spam.

**Comment by sgdc3** [comment]
No more Win10 edition support? :(

**Comment by MCPEGamerJPatGitHub** [comment]
Win10 is classified as PE.

**Comment by sgdc3** [comment]
We can't change nickname on W10 edition -_- It's associated to our xbox username

**Comment by MCPEGamerJPatGitHub** [comment]
@sgdc3 Then unfortunately you need to make a new account. But it's not much price to pay for the priviledge of being able to join PC servers with ease.

**Comment by sgdc3** [comment]
Why do we need this authentication system for offline servers? -_-

**Comment by MrPowerGamerBR** [comment]
@sgdc3 I didn't test, but, if the proxy is in offline-mode, the authentication is skipped.

**Comment by sgdc3** [comment]
Nope, it requires the CLS authentication.

**Comment by MrPowerGamerBR** [comment]
@sgdc3 then it is a issue.

**Comment by MCPEGamerJPatGitHub** [comment]
@sgdc3 It does, although it is required by Mojang's login servers, or players will be kicked out of any server system

**Comment by MrPowerGamerBR** [comment]
@MCPEGamerJPatGitHub I'm pretty sure he is talking about offline PC servers, you shouldn't need to login via a website if the proxy is in offline mode and the server is in offline mode.

**Comment by MCPEGamerJPatGitHub** [comment]
@MrPowerGamerBR I'm pretty sure online mode isn't supported yet

**Comment by MrPowerGamerBR** [comment]
@MCPEGamerJPatGitHub I'm pretty sure this authentication method was implemented specifically for online mode servers because the method before (Inputting the login/pass in the chat) was a security issue.

@sgdc3 is saying that this method is also enabled for offline mode when it shouldn't be, offline mode doesn't require a auth key from Mojang, this will only create a inconvenience for offline mode proxies.

**Comment by RandomAltThingy** [comment]
Why did you copy it...?

**Comment by MCPEGamerJPatGitHub** [comment]
Shut up

**Comment by RandomAltThingy** [comment]
I have deleted the comments in the original one. Also, why do you think it's alright to randomly recreate an issue originally by the project leader when there is nothing wrong with his issue?
