### ISSUE TITLE
Cannot connect to a 1.12.2 server that's using ProtocolSupport 

### ISSUE THREAD

**Issue by krusic22** [DragonetMC/DragonProxy#88]
Setup:
Dragon Proxy - > Latest Bungee - > Paper 1.12.2 server using ProtocolSupport.
Disconnect msg: Outdated client.

**Comment by DefinitlyEvil** [comment]
try Spigot? Other forks not tested.

**Comment by krusic22** [comment]
Tested with Spigot and got the same error. But the thing is that I get kicked by DragonProxy before it even tries to connect to Bungee or any other server.

`[07:29:55] [INFO] Client null[/111.111.111.111:39423] disconnected! Reason: Client disconnect
PING /111.111.111.111:37050
CLIENT CONNECT
CLIENT PROTOCOL = 140`

**Comment by Redned235** [comment]
Yeah had the same issue aswell. It appears that Minecraft Bedrock when it updated to 1.2.5 had a protocol change. I went into the Versioning.java file and changed the protocol version to 140 before compiling. And when I joined, it didn't kick me but the screen was stuck on "Loading resource packs".

**Comment by DefinitlyEvil** [comment]
Well we haven't updated to 1.2.5 yet.

**Comment by Redned235** [comment]
Alrighty, I was kinda confused because the README said DragonProxy supports 1.2.x

**Comment by Creeperface01** [comment]
I think thé only thing we have to change Is protocol number

**Comment by Creeperface01** [comment]
Btw what servers are tested And proxy Is able to connect to?

**Comment by DefinitlyEvil** [comment]
@Creeperface01 I was able to use MC:Bedrock 1.2.3 to connect to MC:Java 1.12.2.

**Comment by HoverEpic** [comment]
Updated my fork 3 days ago for 1.2.5 see https://github.com/HoverEpic/DragonProxy/commit/3807cc487a58576dcd0ca9684ee0dc33bb140b67#diff-8454b5e68c55d27de4414e2234c59bddL13

**Comment by ogmkp** [comment]
Still on "outdated client" :)
