### ISSUE TITLE
Chat dead again

### ISSUE THREAD

**Issue by DefinitlyEvil** [DragonetMC/DragonProxy#90]
@DragonetMC/developers 

Please notice that DO NOT add variables in translator class because all players share one translator so their data will be fucked. 

So I re-organised them into MessageTranslator but I found I messed up the code. 
Sorry. xD

**Comment by DefinitlyEvil** [comment]
@MrPowerGamerBR

**Comment by MrPowerGamerBR** [comment]
@DefinitlyEvil I don't know what did you do to break the code.

**Comment by RandomAltThingy** [comment]
@MrPowerGamerBR Read his commit where he says in caps about moving the message translator as it fucks it up or something

**Comment by RandomAltThingy** [comment]
https://github.com/DragonetMC/DragonProxy/commit/c43252697137c36c1519f161d5aa4e3f1038fcc5

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy I know why he changed it, but I don't know why it is not working.

Also, I created a global variable like the older code because I couldn't get it to work without it.

**Comment by DefinitlyEvil** [comment]
@MrPowerGamerBR Never use global variables in translators.

**Comment by TheDiamondYT1** [comment]
The chat seems to work so imma close this

**Comment by DefinitlyEvil** [comment]
It doesn't when using colors.

**Comment by MrPowerGamerBR** [comment]
@DefinitlyEvil 
```
/*
 * Created by MrPowerGamerBR for Asriel's DreamProxy
 * 
 * 16/04/2016
 */
public static String toColorizedMessage(Message message) {
	StringBuilder build = new StringBuilder(message.getText());
	for(Message msg : message.getExtra()) {
		build.append(toMinecraftColor(msg.getStyle().getColor()) + toMinecraftFormat(msg.getStyle().getFormats()) + msg.getFullText());
	}
		return build.toString();
}

private static String toMinecraftFormat(List<ChatFormat> formats) {
	String superBase = "";
	for (ChatFormat cf : formats) {
		String base = "§";
		switch (cf) {
		case BOLD:
			base += "l";
			break;
		case ITALIC:
			base += "o";
			break;
		case OBFUSCATED:
			base += "k";
			break;
		case STRIKETHROUGH:
			base += "m";
			break;
		case UNDERLINED:
			base += "n";
			break;
		default:
			break;
		}
		superBase += base;
	}
	return superBase;
}
	public static String toMinecraftColor(ChatColor color) {
	String base = "§";
	
	System.out.println(color);
	switch (color) {
	case AQUA:
		base += "b";
		break;
	case BLACK:
		base += "0";
		break;
	case BLUE:
		base += "9";
		break;
	case DARK_AQUA:
		base += "3";
		break;
	case DARK_BLUE:
		base += "1";
		break;
	case DARK_GRAY:
		base += "8";
		break;
	case DARK_GREEN:
		base += "2";
		break;
	case DARK_PURPLE:
		base += "5";
		break;
	case DARK_RED:
		base += "4";
		break;
	case GOLD:
		base += "6";
		break;
	case GRAY:
		base += "7";
		break;
	case GREEN:
		base += "a";
		break;
	case LIGHT_PURPLE:
		base += "d";
		break;
	case RED:
		base += "c";
		break;
	case RESET:
		base += "r";
		break;
	case WHITE:
		base += "f";
		break;
	case YELLOW:
		base += "e";
		break;
	default:
		break;
	}
	System.out.print(base);
	return base;
}
```

You know, fixing the old code was easy, just change everything to non-global variables and then initialize the class by using new MessageTranslator(String message).translate();

Anyway, I redone the code for my own proxy that I'm creating just for fun, here it is if you want to use it.

**Comment by DefinitlyEvil** [comment]
@MrPowerGamerBR Thanks so much! <3

**Comment by MrPowerGamerBR** [comment]
@DefinitlyEvil also, I didn't test with JSON messages yet, but it does work with normal messages.

**Comment by DefinitlyEvil** [comment]
@MrPowerGamerBR Got it. ;)

**Comment by MrPowerGamerBR** [comment]
@DefinitlyEvil another FYI, your code for loading world's data (the block metadata, the :1, :2, :3, etc) is completly broken, it fails to load some of the block's metadata (Try creating a huge blue wool wall and then reconnect, some of the wools will be white).

See how ProtocolSupport does the data loading for the mcpe branch and do the same thing for DragonProxy, I made my own code but it isn't the best (but it does work).

**Comment by MrPowerGamerBR** [comment]
@DefinitlyEvil maybe I will try to help to improve DragonProxy after the 0.14.1 support is made. (because working with old MCPE versions is a pain and I don't want to downgrade my MCPE version)

**Comment by DefinitlyEvil** [comment]
@MrPowerGamerBR We do need ur help. ;P

**Comment by TekkitCommando** [comment]
It's like 5:50 am, my brain is fried o.0 but I thought I would tell you I can put DragonProxy on another service for server hosting when it's not as incomplete/buggy.  @DefinitlyEvil

**Comment by TheDiamondYT1** [comment]
ni can  get us on a hosting site
