### ISSUE TITLE
Can't connect/Find server

### ISSUE THREAD

**Issue by Eoraptorur** [DragonetMC/DragonProxy#91]
Minecraft Client can't find the server (Dragon Proxy) Everything stands right in the config!

**Comment by DefinitlyEvil** [comment]
don't use the same machine to connect which you host it, you have to use another machine like your phone.

**Comment by Eoraptorur** [comment]
Okay it works for now, But i cant see the java player i can only see the c++ player from Java and not from c++

**Comment by yoft** [comment]
I can not see entities from the proxied player either, using bungeecord and
spigot.

**Comment by Eoraptorur** [comment]
Me to i use bungeecord and spigot 1.12.2 with viaversion and backwards

**Comment by Eoraptorur** [comment]
i can only see the chat on the java version but not on the c++ version i dont see my plugins /pl does not work its not hating but its debugging 👍

**Comment by DefinitlyEvil** [comment]
Other entities are not supported yet, be patient guys. ;)

**Comment by yoft** [comment]
Thanks :) I've only just jumped on board with this, wasn't sure.
Excellent work so far!

**Comment by DefinitlyEvil** [comment]
Thx and I will keep doing it

**Comment by DefinitlyEvil** [comment]
In the mean time, you can check out my other projects as well.

**Comment by Eoraptorur** [comment]
Thanks for reacting 👍 I hope that will look some day amazing news (proxy)

**Comment by HoverEpic** [comment]
I can't work on entities for now, but I'll continue my work in 4 days. Already have theme spawning and moving on my local project.

**Comment by DefinitlyEvil** [comment]
@HoverEpic nice work man!!
