### ISSUE TITLE
Can it connect to bungeecord network?

### ISSUE THREAD

**Issue by kit8379** [DragonetMC/DragonProxy#92]
can?

**Comment by yoft** [comment]
Yes

On 3 Dec. 2017 8:52 pm, "kit8379" <notifications@github.com> wrote:

can?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/DragonetMC/DragonProxy/issues/92>, or mute the thread

**Comment by kit8379** [comment]
what version do i need?

**Comment by kit8379** [comment]
Download Once compiled, run dragonproxy-*.jar in proxy/target where '*' is the version number.

what is the proxy/target mean?

**Comment by yoft** [comment]
I know 1.12.2 works, so any version that uses the most recent protocol.

**Comment by kit8379** [comment]
what is the proxy/target mean?

**Comment by yoft** [comment]
Just download the latest version from
https://github.com/DragonetMC/DragonProxy/releases
And run it with "java - jar dragonproxy-0.2.1-preR1.jar"
Just remember the software is still in development so a lot of features are
still missing.

**Comment by kit8379** [comment]
can't use it to connect the least bungeecord

**Comment by yoft** [comment]
Where are you running dragonproxy? What device are you playing Minecraft
on?

**Comment by kit8379** [comment]
running dragon proxy at the same machine of putting bungeecord. the message shows keep loading but can't enter.

**Comment by kit8379** [comment]
with ios 1.2.5 version

**Comment by kit8379** [comment]
latest bungeecord

**Comment by kit8379** [comment]
bungeecord console didn't show that the player is conecting

**Comment by kit8379** [comment]
the bungeecord shows this error [xxxxxxxx] disconnected with: NativeIoException : syscall:read(..) failed: Connection reset by peer @ io.netty.channel.unix.FileDescriptor:-1

**Comment by kit8379** [comment]
[15:07:40 INFO]: [TonyPak|/127.0.0.1:50264] <-> ServerConnector [lobby] has connected
[15:07:40 WARN]: [/127.0.0.1:50264|TonyPak] -> UpstreamBridge - NativeIoException: syscall:read(..) failed: Connection reset by peer
[15:07:40 INFO]: [TonyPak] disconnected with: NativeIoException : syscall:read(..) failed: Connection reset by peer @ io.netty.channel.unix.FileDescriptor:-1
[15:07:40 INFO]: [/127.0.0.1:50264|TonyPak] -> UpstreamBridge has disconnected
[15:07:40 INFO]: [/127.0.0.1:50264|TonyPak] <-> DownstreamBridge <-> [lobby] has disconnected

**Comment by kit8379** [comment]
I also tried win10 edition. Same.

**Comment by DefinitlyEvil** [comment]
Try install both ViaVersion and ViaBackward

**Comment by kit8379** [comment]
install in where? bungeecord or lobby server? Since now i only install in server but not bungeecord

**Comment by kit8379** [comment]
install in bungeecord?

**Comment by DefinitlyEvil** [comment]
yes

**Comment by kit8379** [comment]
can't. the dragon proxy said it connected but bungee have the same error message like upside.

**Comment by kit8379** [comment]
the lobby shows like this 
[23:14:03 INFO]: [SpawnTP] Sent TonyPak to spawn
[23:14:03 INFO]: TonyPak[/127.0.0.1:56967] logged in with entity id 878 at ([wor
ld]979.5, 12.5, -475.5)
[23:14:04 INFO]: TonyPak lost connection: Disconnected

**Comment by DefinitlyEvil** [comment]
:/

**Comment by yoft** [comment]
So the connection is being created then just *poof*?

**Comment by kit8379** [comment]
i think so

**Comment by kit8379** [comment]
but nothing show in minecraft pe it just keep loading

**Comment by yoft** [comment]
I've had this problem a couple of times now, some times it takes a few attempts to connect to dragonproxy.

**Comment by DefinitlyEvil** [comment]
try out the latest release.
