### ISSUE TITLE
PE Client: "Entity" Problem 2

### ISSUE THREAD

**Issue by Waooto** [DragonetMC/DragonProxy#95]
On PE client, Entities are in different places than on PC.

Like, my PC character would be 5 blocks away, and in PE version, it would be 1 block away from the PE client.

The moving animation for the PC player on the PE client is also buggy, if i move my head up, it would move down on PE, etc.

Is this possible to fix ?

**Comment by Waooto** [comment]
UPDATE:

This also gets spammed on dragonproxy cmd

https://pastebin.com/raw/ZkuKMyv4

**Comment by yoft** [comment]
Looks like it's due to teleporting not being handled correctly...
Just so you know, this software is still in development.
