### ISSUE TITLE
Problems with network

### ISSUE THREAD

**Issue by MrGenga** [DragonetMC/DragonProxy#95]
Hello! When i starting DragonProxy, I see that message: Failed to find a usable hardware address from the network interfaces; using random bytes: (hex bytes). But, when i join the server, i see infinity connection to the server. Please help me!

**Comment by DefinitlyEvil** [comment]
What OS are you using and could you please paste your config file to something like pastie.org?

**Comment by MrGenga** [comment]
Can i paste it here?

**Comment by MrGenga** [comment]
My OS is Ubuntu 14.04
Here is config.properties: http://freetexthost.com/lwd2yy1lrp

**Comment by DefinitlyEvil** [comment]
Type `ifconfig` and check your IP address manually(not the `127.0.0.1` one) and
change this line:
`udp_bind_ip=0.0.0.0`
into
`udp_bind_ip=YOUR_IP_ADDRESS`

Notice: If you use a home router, your IP may can be like `192.168.x.x` or `10.x.x.x`.

**Comment by MrGenga** [comment]
Not work

**Comment by Pet0203** [comment]
(This is a very dumb suggestion and I know that this wouldn't make anything better, but it's worth a try.) Could it be that you have changed the UDP port to 19144?

**Comment by DefinitlyEvil** [comment]
Well it must be your system networking problem not the software.

**Comment by TekkitCommando** [comment]
@DefinitlyEvil yo bud you didn't let me know what you thought on skype :P

**Comment by DefinitlyEvil** [comment]
@TekkitCommando What Skype?
