### ISSUE TITLE
PE Client: Tp Problem

### ISSUE THREAD

**Issue by Waooto** [DragonetMC/DragonProxy#96]
When using /tp all on PC, everyone gets teleported to the same place.

On PE, the PE client will be at the same location and will not get teleported
but on PC it will look like the PE player has been teleported

**Comment by HoverEpic** [comment]
Is the problem exist on latest version?

**Comment by HoverEpic** [comment]
Closed after 10 days with no response. If the problem is present again, i'll reopen it.
