### ISSUE TITLE
A Problem

### ISSUE THREAD

**Issue by lsw46** [DragonetMC/DragonProxy#96]
When to support the creation of synthetic items and support Create Backpack

**Comment by DefinitlyEvil** [comment]
This is a place to track bugs but NOT a forum.

**Comment by DefinitlyEvil** [comment]
Ask here: http://forums.dragonet.org

**Comment by RandomAltThingy** [comment]
@DefinitlyEvil Why not VanillaForums? There is some sweet themes for it and dome flat themes.

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy Host limited CPU usage and VanillaForums will cause over-load and server will give back error code 500.
