### ISSUE TITLE
The permission of new player is "guest"

### ISSUE THREAD

**Issue by GarryLai** [DragonetMC/DragonProxy#97]
The permission of new player is "guest", who can't build and destroy the block. How can I set it??
Thanks

**Comment by mikroskeem** [comment]
Quoting text what was said here earlier

> Just so you know, this software is still in development.

**Comment by GarryLai** [comment]
Ok, I know, I just suggest to add a setting in config file
This project is really grate.

**Comment by HoverEpic** [comment]
I think it's in your plugins configuration.

**Comment by DefinitlyEvil** [comment]
this is the problem of DragonProxy, will be fixed soon.

**Comment by HoverEpic** [comment]
fixed in https://github.com/DragonetMC/DragonProxy/pull/109/commits/9b0e30c8400e880bd21dbd913266c3612525dd18
