### ISSUE TITLE
Create MCPE proxy like BungeeCord.

### ISSUE THREAD

**Issue by MrGenga** [DragonetMC/DragonProxy#98]
Hey, guys! If you know a lot about MCPE/RakLib protocol, can you create proxy server, like BungeeCord, but for MCPE. It is will very usable for big servers.

**Comment by Pet0203** [comment]
As far as I know, DragonProxy will have a feature to add multiple servers.

**Comment by DefinitlyEvil** [comment]
We will make it support multiple servers and supported mixed server types(like a MCPE server and a Spigot server).

**Comment by mastercoms** [comment]
should this issue be open to track progress on multple server support?

**Comment by TekkitCommando** [comment]
Use of milestones more might be a good idea to

**Comment by Janmm14** [comment]
Bug and TODO?

**Comment by TheDiamondYT1** [comment]
Whoops wasn't meant to add bug label

**Comment by Creeperface01** [comment]
But idk how to get PEPacket from Datagram packet and how to make datagramPacket from PEPacket..
