### ISSUE TITLE
[Solved] Question: LAN Stuff

### ISSUE THREAD

**Issue by Waooto** [DragonetMC/DragonProxy#98]
Hello,

I know this is still in development, but i have a question!
How can I port forward the DragonProxy server instead of playing on "LAN"

Because when I go on PE, the DragonProxy shows up in the "Friends" tab, and when I add "localhost" to the server list, it can't connect.

What am I doing wrong ?

**Comment by HoverEpic** [comment]
Is it on w10?

**Comment by yoft** [comment]
Dragonproxy uses the same port Minecraft. Either change from the default
port in dragonproxy or host on another machine.

**Comment by Waooto** [comment]
I went to config and edited the port,

does that mean i have to portforward that port?

the part where it says (udp_bind_port:)

**Comment by yoft** [comment]
And what device are you running dragonproxy on? And which are you running
the Minecraft client on?

**Comment by HoverEpic** [comment]
For w10 localhost connection, see http://pmmp.readthedocs.io/en/rtfd/faq/connecting/win10localhostcantconnect.html

**Comment by yoft** [comment]
That fix it?

**Comment by Waooto** [comment]
@yoft 
I'm using 

Win 8.1
IOS 11

I changed the Port in server config to **udp_bind_port: 19133** 
When I went on my phone, the server (DragonProxy) did not appear like it used to

So I went to the "Servers" tab, and added server

Name: Test
IP: localhost
Port: 19133

I clicked save, and pressed on it and it said "Unable to connect to world", the server is running on my PC fine, but it doesn't say "ping" like it used to (before i changed the port)

_Update:_ Does anyone know when the next update for DragonProxy is coming out :D

**Comment by yoft** [comment]
Okay, because you're connecting to dragonproxy from a different device, you
can still use the default port 19132.

"localhost" is a nickname for "this device", so that only works if the
device you're connecting from and to are the same.
So you need to find the IP of the pc running dragonproxy and use that
instead of "localhost".

**Comment by Waooto** [comment]
Oh yeah! Thanks!

**Comment by yoft** [comment]
Is it working now?
