### ISSUE TITLE
Support of 0.13.2 alpha

### ISSUE THREAD

**Issue by welvinyu** [DragonetMC/DragonProxy#99]
The version works for 0.13.1 before, but the mainstream version is 0.13.2 alpha now, however, I notice some issues with the visibility (players cannot move beyond a small region). I can see the latest version on the project supports 0.14 instead. Is it possible to fix these issues?

**Comment by DefinitlyEvil** [comment]
We don't have spare time to do that, now only focus on 0.14.x and we will try to release a pre version when 0.14.0 alpha come out.

**Comment by welvinyu** [comment]
Thanks for the clarifications. OK, I will stick to 0.13.1 until the 0.14 is out then.

**Comment by welvinyu** [comment]
Another thought after checking PocketMine-MP's 0.13.2 update. In fact they only flit the protocol number from 38 to 39, which looks working. Assuming that Mojang 0.13.2 and 0.14 are using similar network protocol, my worry is that tolerating bugs in 0.13.2 might affect longer term plan of 0.14 support.

**Comment by Pet0203** [comment]
But why so you want to develop a 0.13.2 version? 0.14.0.5 (BETA) is out which means that the 0.14.0 release is coming soon.

**Comment by welvinyu** [comment]
Not sure if porting the changes to 0.14.0.5 back to 0.13.2 could resolve the errors encountered.
